### ISSUE TITLE
pyjwt 2.10: AttributeError: module 'jwt.exceptions' has no attribute 'PyJWTError'

### ISSUE THREAD

**Issue by stevegerrits** [jpadilla/pyjwt#1019]
Summary.

## Expected Result
import jwt.exceptions.PyJWTError should work as expected

What you expected.
Valid import

## Actual Result
AttributeError

What happened instead.
AttributeError

## Reproduction Steps
import jwt.exceptions.PyJWTError 

```python
import jwt.exceptions.PyJWTError 
```

**Comment by benvdh-incentro** [comment]
@stevegerrits you might want to try `jwt.PyJWTError` as the exceptions are all imported in the __init__.py and in that way made available directly on the package...
