### ISSUE TITLE
Setup doesn't list contrib.algorithms packages

### ISSUE THREAD

**Issue by johnlockwood-wf** [jpadilla/pyjwt#117]
This means they don't get installed when someone does `pip install PyJWT` or `python setup.py install`

**Comment by jpadilla** [comment]
@johnlockwood-wf yeah you're right, just fixed it via 882524d845349df532e2a96b30fbe7e74e6ff55c. Will release a new version in a few minutes.

**Comment by michaeldavis-wf** [comment]
@jpadilla What is the process for requesting a release?  I would love to be able to take advantage of this fix.

**Comment by jpadilla** [comment]
@michaeldavis-wf Doesn't v1.0.1 fix this? I just noticed I didn't actually publish the release here on GitHub, but it's published on PyPI.

**Comment by michaeldavis-wf** [comment]
@jpadilla I didn't realize that I needed to manually register the PyCrypto algorithms.  I am up and going now.  Thanks.
