### ISSUE TITLE
Exception during sign. 'SHA512' object has no attribute 'oid'

### ISSUE THREAD

**Issue by johnlockwood-wf** [jpadilla/pyjwt#118]
I created a key pair like so:

    > openssl genrsa -out key.pem 4096
    > openssl rsa -in key.pem -pubout -out pubkey.pem

Then in the python REPL:

    >>> from jwt.contrib.algorithms.pycrypto import RSAAlgorithm
    >>> import jwt
    >>> jwt.register_algorithm('RS512', RSAAlgorithm(RSAAlgorithm.SHA512))
    >>> with open('.keys/key.pem') as fo: private_key_bytes = fo.read()
    ...
    >>> result = jwt.encode({'name':'John'}, private_key_bytes, algorithm='RS512')
    
This raises an exception:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "build/bdist.macosx-10.10-intel/egg/jwt/api.py", line 103, in encode
      File "build/bdist.macosx-10.10-intel/egg/jwt/contrib/algorithms/pycrypto.py", line 44, in sign
      File "site-packages/Crypto/Signature/PKCS1_v1_5.py", line 110, in sign
        em = EMSA_PKCS1_V1_5_ENCODE(mhash, k)
      File "site-packages/Crypto/Signature/PKCS1_v1_5.py", line 211, in EMSA_PKCS1_V1_5_ENCODE
        digestAlgo  = DerSequence([hash.oid, DerNull().encode()])
    AttributeError: 'SHA512' object has no attribute 'oid'

**Comment by johnlockwood-wf** [comment]
Okay, this seems to be a problem with PyCrypto 2.6.1, I installed from master on github and the above worked.

**Comment by johnlockwood-wf** [comment]
Unfortunately PyCrypto 2.6 is what is installed on appengine and this solution won't do it. There must be a way to do it properly the 2.6 way.

**Comment by johnlockwood-wf** [comment]
If I use SHA to instantiate RSAAlgorithm, encoding with it works:

    >>> from Crypto.Hash import SHA
    >>> jwt.register_algorithm('RS512', RSAAlgorithm(SHA))
    >>> result = jwt.encode({'name':'John'}, private_key_bytes, algorithm='RS512')

But at this time, I don't know the implications of SHA vs SHA512 in the new version.

**Comment by johnlockwood-wf** [comment]
I don't think it makes the same hash.

**Comment by mark-adams** [comment]
SHA = SHA1 which is not a valid algorithm for JWT. Only SHA256 (*S256), SHA384 (*S384), or SHA512 (*S512).

I tried your example locally and couldn't duplicate the issue. What version of Python are you running?

**Comment by johnlockwood-wf** [comment]
python 2.7.8, no cryptography package installed, PyCrypto 2.6

**Comment by johnlockwood-wf** [comment]
ok, this is weird, I made a new virtualenv and installed pycrypto 2.6 and then pyjwt and it worked.

**Comment by johnlockwood-wf** [comment]
I used pip installs instead of installing from cloned git repos.

**Comment by johnlockwood-wf** [comment]
PyCrypto just seems to be building badly in this virtualenv, so I'm going to close this. Thanks
