### ISSUE TITLE
non-numeric expiration claim does not raise an error

### ISSUE THREAD

**Issue by kumar303** [jpadilla/pyjwt#121]
I would expect a non-numeric expiration claim to raise an error but it does not. To reproduce, here's a JWT with ``{exp: '<not a number>'}``':

````
>>> import jwt
>>> import calendar, time
>>> iat = calendar.timegm(time.gmtime())
>>> token = jwt.encode({'aud': 'some-aud', 'iss': 'some-iss', 'typ': 'some-typ', 'iat': iat, 'exp': '<not a number>', 'request': {}}, 'secret')
>>> jwt.decode(token, 'secret', verify=True, audience='some-aud')
{u'aud': u'some-aud', u'iss': u'some-iss', u'request': {}, u'exp': u'<not a number>', u'iat': 1427495823, u'typ': u'some-typ'}
````

If a signature checking was somehow bypassed, an expiration like this could maybe allow for replay attacks.

**Comment by mark-adams** [comment]
The spec says: "Its value MUST be a number containing a NumericDate value."

We should definitely fix this. Thanks for reporting.

**Comment by kumar303** [comment]
I also noticed the same behavior when you pass in non-numeric ``iat`` values but I don't think that would lead to any replays. If you're in there, might as well fix those too.
