### ISSUE TITLE
Add more flexible and complete verification options

### ISSUE THREAD

**Issue by mark-adams** [jpadilla/pyjwt#127]
I was thinking that it might be useful for us to implement more flexible verification options.

I propose something like this:

```
def decode(token, secret, options=None)
```

where options is a dict that looks something like this:
```
options = {
   'verify_signature': True,
   'verify_exp': True,
   'verify_nbf': True,
   'verify_iat': True,
   'verify_aud`: True
}
```

This is similar to what [ruby-jwt does](https://github.com/progrium/ruby-jwt/blob/master/lib/jwt.rb#L110)
We could make it where options could be specified globally (at the PyJWT object level) or as an override argument to `decode()`

**Comment by jpadilla** [comment]
@mark-adams yeah I can see how this can be useful. For example that #129 use case could just set `verify_aud` to False.

**Comment by mark-adams** [comment]
I'll take a look

**Comment by michaeldavis-wf** [comment]
@mark-adams I know timelines are to be taken with a grain of salt, but do you have a guesstimate on how long 1.1.0 might be?  I would love to be able to pull in the changes from this PR.

If it is going to be too long, would it be possible to cut a 1.0.2 release with the current master?

**Comment by mark-adams** [comment]
Moved this convo to #137
