### ISSUE TITLE
Removing bin/jwt?

### ISSUE THREAD

**Issue by jpadilla** [jpadilla/pyjwt#130]
Do we want to keep this around or just remove it? How useful is it really? Are people using it?

**Comment by mark-adams** [comment]
I didn't even know it was in there until three days ago. I could see how it might be useful but I feel like we might be able to fill the role by incorporating behavior into `python -m jwt` if people really use it.

**Comment by mark-adams** [comment]
If we have tests for it, I think its not a bad idea to leave it around. I could see it being useful.

**Comment by dresiu** [comment]
Maybe it can be useful, but it destroy my interpreter because if I want to import jwt and for example decode function, it says that "AttributeError: 'module' object has no attribute 'decode'" because te Scripts dir (on Windows) is before site-packages in paths. It could be renamed.
