### ISSUE TITLE
1.1.0 Release

### ISSUE THREAD

**Issue by mark-adams** [jpadilla/pyjwt#137]
This is an issue for discussing the 1.1.0 release

https://github.com/jpadilla/pyjwt/milestones/v1.1.0

**Comment by mark-adams** [comment]
@michaeldavis-wf : Continuing the discussion from #127... it shouldn't be long. Once @jpadilla reviews the remaining PRs and we get the merged; I'll create the release PR.

**Comment by michaeldavis-wf** [comment]
Sounds good.

Thanks.

**Comment by jpadilla** [comment]
@mark-adams just released v1.1.0
