### ISSUE TITLE
'iat' claim

### ISSUE THREAD

**Issue by cilia** [jpadilla/pyjwt#138]
Just noticed something inconsistent in the documentation.

In the `options` overriding example, it lists `verify_iat` field, implying that `iat` claim is supported by the library. However, under section 'Support of registered claim names', it does not list `iat` as a supported claim name.

Some confirmation would be much appreciated. Thanks!

**Comment by mark-adams** [comment]
The `iat` claim is validated by PyJWT if `verify_iat == True`.

The `iat` will fail validation and raise an exception if the `iat` value is in the future (taking into account the specified leeway for clock skew)

The README has been updated as well. Thanks for letting us know!

**Comment by gobengo** [comment]
See #190 . Where did y'all get the rule to validate that iat is not in the future?
