### ISSUE TITLE
Add support for JSON Web Signature (JWS)

### ISSUE THREAD

**Issue by mark-adams** [jpadilla/pyjwt#142]
http://datatracker.ietf.org/doc/draft-ietf-jose-json-web-signature/

**Comment by mark-adams** [comment]
Made some progress with this on #141 . Mostly just splitting out the JWS-logic from the JWT-logic.

**Comment by ashb** [comment]
Has there been anymore progress on this? 

I might attempt this in December (I make no promises, but I need a JWS solution for a Django project I'm working on) and I was wondering if there's been any thought to structure/arch/layout? Any estimates as to how much work it would be?

If this is going to be releases as v2 do we need to worry about keeping backcompat? Or just keep it where sensible but it makes things more complex then we can break it?

(My other side is go and I'll be using https://godoc.org/gopkg.in/square/go-jose.v2 which if in doubt is the sort of API I will model on)

**Comment by mark-adams** [comment]
@ashb I actually believe that I implemented JWS some time ago in the `PyJWS` class but didn't actually close out this issue! If I missed something please let me know and reopen!
