### ISSUE TITLE
Add support for JSON Web Encryption (JWE)

### ISSUE THREAD

**Issue by mark-adams** [jpadilla/pyjwt#143]
http://datatracker.ietf.org/doc/draft-ietf-jose-json-web-encryption/

**Comment by mhahn** [comment]
would love to see this

**Comment by krdeepak** [comment]
Is anyone working on it or planning to work? We have a java auth service using JWE and we are creating a separate python service which will validate JWE in place before processing any requests.
Is there any alternative of pyjwt which supports JWE?

**Comment by clintonb** [comment]
Checkout pyjwkest.

**Comment by mark-adams** [comment]
@krdeepak The issue currently isn't assigned to anyone. However, we are always looking for more contributors to help add this functionality. Feel free to submit a PR if you're interested in helping.

**Comment by r-priyam** [comment]
Any update that when it will be implemented?
