### ISSUE TITLE
Add support for JSON Web Key (JWK)

### ISSUE THREAD

**Issue by mark-adams** [jpadilla/pyjwt#144]
http://datatracker.ietf.org/doc/draft-ietf-jose-json-web-key/

**Comment by mark-adams** [comment]
This will cover the fix for #90 as well

**Comment by bjmc** [comment]
I'm interested in this feature to use with Google's OpenIDConnect implementation, e.g. https://www.googleapis.com/oauth2/v3/certs

Is anyone working on this already, or should I go ahead and start a branch? Any tips for how you'd like to see this implemented?

**Comment by Seraf** [comment]
Hello,

I also need this feature, is there any work done on it yet ?

**Comment by mark-adams** [comment]
Not yet, the plan is to begin doing work on this against the 2.0-develop branch.

**Comment by iiSeymour** [comment]
JWK is something I'd like to see in PyJWT :+1:

**Comment by clintonb** [comment]
@mark-adams is there a timeframe for the release of this work and v2.0?

**Comment by jpadilla** [comment]
Anyone interested in this should take a look at #202

**Comment by bjmc** [comment]
In case anyone else needs this feature, it is supported in https://github.com/mpdavis/python-jose/

**Comment by jpadilla** [comment]
Calling on @clintonb @iiSeymour @seraf and anyone else interested in JWK support to check out #202

**Comment by lookuptable** [comment]
@jpadilla It seems the JWK support is on only when cryptography is available? Any chance that you'll support this feature with pycrypto so that it can be used in GAE environment?

**Comment by mark-adams** [comment]
We don't actually support PyCrypto. We only kept it around for
compatibility since we didn't want to instantly break everyone using GAE
when we switched to cryptography.

I'd recommend that you look into the new GAE flexible environment which
will allow you to use any libraries you want including cryptography.

**Comment by butla** [comment]
@mark-adams shouldn't this issue be closed? The code seems to be functional.

**Comment by evertlammerts** [comment]
I've submitted #303 to support loading ECDSA keys from JWKs.

We use JWK sets to support key rotation and selecting a verify key based on the `kid` property in JWT headers. With the current API of PyJWT the user first needs to call `jwt.get_unverified_header`, grab the key from the keyset and call `jwt.decode`. This means base64 and json decoding the same data twice.

Would it be nice to have first-class support for [JWK sets](https://tools.ietf.org/html/rfc7517#section-5)? Maybe something like like `jwt.keyset(binstring) -> JWKSet`, with `JWKSet.encode(data, kid)` and `JWKSet.decode(jwt)` methods?

**Comment by wichert** [comment]
@evertlammers JWK sets would be very nice. They look pretty essential when using AWS user pools.

**Comment by zulrang** [comment]
+1

**Comment by coopa** [comment]
JWK sets are also part of the OpenID spec (see jwks_uri [here](http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata)), so expanded support for them would be welcome.

This also tangentially ties in with comprehending x5c/x5t fields in JWKs, which the lib does not appear to do at this time.

**Comment by ptdel** [comment]
Okta, OneLogin, Cognito, etc all proffer keys in jwks format.  Not having to convert to PEM would be really appealing.  in addition to the fields that @coopa brings up, some of these providers will only give an exponent (e) and modulus (n) in addition to the algorithm and kid, so there needs to be support for rebuilding from just those components if x5c/x5t aren't available.

**Comment by ptdel** [comment]
Hairy, but this converts from jwks exponent and modulus to PEM format.  Rather pilfered from solutions around the web.

```
import base64, struct
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPublicNumbers
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization

class PublicKey(object):

    def __init__(self, pubkey):
        self.exponent = self.base64_to_long(pubkey['e'])
        self.modulus = self.base64_to_long(pubkey['n'])
        self.pem = self.convert(self.exponent, self.modulus)

    def int_array_to_long(self, array):
        return int(''.join(['{:02x}'.format(b) for b in array]), 16)

    def base64_to_long(self, data):
        data = data.encode('ascii')
        _ = base64.urlsafe_b64decode(bytes(data) + b'==')
        return self.int_array_to_long(struct.unpack('%sB' % len(_), _))

    def convert(self, exponent, modulus):
        components = RSAPublicNumbers(exponent, modulus)
        pub = components.public_key(backend=default_backend())
        return pub.public_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PublicFormat.SubjectPublicKeyInfo)
```
would work with something like:
```
for key in keys:
    print(PublicKey(key).pem)
```
for example.

**Comment by ncknuna** [comment]
In case anyone stumbles across this and just needs to decode a single JWK and got confused as to if that was supported or not, here's all you should need:
```
public_key = jwt.algorithms.RSAAlgorithm.from_jwk(<json-encoded-jwk-string>)
jwt.decode(token, pubkey, algorithm='RS256')
```

JWK Sets, on the other hand, are not supported yet, AFAIK

**Comment by dbanty** [comment]
You can use sets, it's just a bit more work.  I found [this article](https://renzo.lucioni.xyz/verifying-jwts-with-jwks-and-pyjwt/) which gives a great explanation.

Basically, they use the code in the comment above me to get the keys and stick them in a dict (keyed by KID).  Then, when you get a jwt to decode, you determine the KID to use with `jwt.get_unverified_header(token)['kid']`, get the key from the dict you build earlier, and use that key to decode.

@jpadilla any chance we can get a shout out to that article or write similar instructions in the docs?  I know you said in #291 that you're working on easier support, but those instructions are great to have in the meantime.

**Comment by jpadilla** [comment]
Hey all, sorry for the long delay on improving support for JWKs. I've just started putting together a few things for v2. You can follow along on #470. Any feedback would be appreciated.

**Comment by ekevoo** [comment]
I would love it if the JWK Set can be used as a whole to decode instead having to traverse it for decoding. Otherwise it's a great improvement. I didn't find any documentation on JWKs either.

**Comment by jtemporal** [comment]
We already support JWK in PyJWT so I'm closing this one.
