### ISSUE TITLE
Default value for options in _validate_claims is silly

### ISSUE THREAD

**Issue by cancan101** [jpadilla/pyjwt#148]
There is no reason to specify a default value for `options` in the `_validate_claims` method. A value of `None` will just result in an error.

https://github.com/jpadilla/pyjwt/blob/ddbaf0008eac6559da5ebd1f24f68ee99ccb34b0/jwt/api_jwt.py#L76

**Comment by mark-adams** [comment]
Great point. Feel free to submit a PR.

**Comment by jcarizza** [comment]
A silly easy solution is set `options={}` to avoid AttributeError :P. But, by what i see `options` argument always recibe a dict object.
