### ISSUE TITLE
Asymmetric leeways

### ISSUE THREAD

**Issue by cancan101** [jpadilla/pyjwt#150]
Does it make sense to have two leeways, one for validating expiration and the other for validating "not yet valid" / "in the future". (They would default to be being the same if only one is specified.)

The idea here is that the leeways mean slightly different the things. The latter can come up if there is clock skew between issuer and validator. The former is clock skew + any time of queuing or processing delay by the validator.

**Comment by jtemporal** [comment]
I'm closing this one since it has been more than 3 months without a response from the issue author.

Please feel free to submit another issue following the issue template if you still have the question.
