### ISSUE TITLE
Bad token can generate KeyError in _verify_signature

### ISSUE THREAD

**Issue by peter-conalgo** [jpadilla/pyjwt#167]
Little thing: if the header is invalid and does not contain "alg" key, a KeyError occurs.

Example with an empty ({}) header area:

````python
>>> j
'e30.eyJhIjo1fQ.KEh186CjVw_Q8FadjJcaVnE7hO5Z9nHBbU8TgbhHcBY'
>>> jwt.decode(j, 'secret')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/jwt/api_jwt.py", line 61, in decode
    options, **kwargs)
  File ".../site-packages/jwt/api_jws.py", line 115, in decode
    key, algorithms)
  File ".../site-packages/jwt/api_jws.py", line 168, in _verify_signature
    alg = header['alg']
KeyError: 'alg'
>>>
````

**Comment by jpadilla** [comment]
@peter-conalgo thanks!

@mark-adams how about raising `InvalidAlgorithmError` in this case as well?

**Comment by mark-adams** [comment]
That sounds reasonable to me. Forgetting to put algorithm in your header definitely seems to fit within the confines of being an invalid algorithm :+1:

**Comment by jpadilla** [comment]
@peter-conalgo want to put a PR together to fix this? If not I'll get around to it later this week.
