### ISSUE TITLE
ECDSA compatibility broken between Ruby's JWT implementation and PyJWT

### ISSUE THREAD

**Issue by cica-doug** [jpadilla/pyjwt#168]
I've got some code that receives ECDSA signed JWTs and upon upgrading to PyJWT 1.3.0 users submitting JWT's created with Ruby's JWT library (https://github.com/progrium/ruby-jwt) no longer appear valid. I get the following error: "DecodeError: Signature verification failed". Not sure if this is expected behavior as a result of #158 or if there could possibly be a compatibility flag added?

**Comment by mark-adams** [comment]
I think you're right. This appears to be the result of our fix in #158. I've [filed a bug with ruby-jwt](https://github.com/progrium/ruby-jwt/issues/84) so that they can fix their implementation as well. Thanks for contributing! :smile:

**Comment by mark-adams** [comment]
This has been fixed via [an update to ruby-jwt](https://github.com/progrium/ruby-jwt/pull/87)

**Comment by jpadilla** [comment]
@mark-adams thanks following up!
