### ISSUE TITLE
Doesn't respect prefix install option.

### ISSUE THREAD

**Issue by breser** [jpadilla/pyjwt#177]
> $ pip install "--install-option=--prefix=$PWD/pythonlibs" PyJWT
> Downloading/unpacking PyJWT
>   Downloading PyJWT-1.4.0-py2.py3-none-any.whl
> Installing collected packages: PyJWT
> Cleaning up...
> Exception:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
>     status = self.run(options, args)
>   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
>     requirement_set.install(install_options, global_options, root=options.root_path)
>   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
>     requirement.install(install_options, global_options, _args, *_kwargs)
>   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
>     self.move_wheel_files(self.source_dir, root=root)
>   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
>     pycompile=self.pycompile,
>   File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
>     clobber(source, lib_dir, True)
>   File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
>     os.makedirs(destsubdir)
>   File "/usr/lib/python2.7/os.py", line 157, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/PyJWT-1.4.0.dist-info'

**Comment by breser** [comment]
Maybe doesn't matter.  pip --target seems to work fine.

**Comment by mark-adams** [comment]
I wasn't able to duplicate this on my end.

```
$ pip install --install-option="--prefix=$PWD/pythonlibs" pyjwt
/home/mark/.venv/pyjwt/local/lib/python2.7/site-packages/pip/commands/install.py:199: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting pyjwt
  Using cached PyJWT-1.4.0.tar.gz
Skipping bdist_wheel for pyjwt, due to binaries being disabled for it.
Installing collected packages: pyjwt
  Running setup.py install for pyjwt
Successfully installed pyjwt
```

**Comment by mark-adams** [comment]
This doesn't seem to be reproducible.
