### ISSUE TITLE
pytest-runner in test_requires and setup_requires

### ISSUE THREAD

**Issue by mbultrow** [jpadilla/pyjwt#179]
I'm having problems with distributing my app to an offline environment because of pytest-runner in setup_requires.
I doesn't seem like pytest is necessary for installation itself, so I don't want to be forced to package it with my application.

Can you just remove the reference, or am I missing something?

**Comment by mbultrow** [comment]
Wow, I see that there's already a fix waiting - nice!
I've also found [this interesting statement](http://stackoverflow.com/a/27789623), that setup_requires is really kind of incompatible with pip. Is it necessary at all in PyJWT's case?

**Comment by mark-adams** [comment]
Hmmm... I'm not sure where they're getting that from.

I just ran "pip install pyjwt" on a clean install and got the following:

```
$ pip install pyjwt
Collecting pyjwt
  Downloading PyJWT-1.4.0-py2.py3-none-any.whl
Installing collected packages: pyjwt
Successfully installed pyjwt-1.4.0

$ pip freeze
PyJWT==1.4.0
wheel==0.24.0
```

Looks like it doesn't install pytest-runner as that post would suggest.

**Comment by mbultrow** [comment]
Sorry for not responding quickly, I was on vacation (those happen), but this needs to be reopened.
Pip install doesn't install pytest-runner, but wants it to run it's egg_info.

To reproduce my problem do this:
```
$ mkdir vendor
$ pip install --download vendor pyjwt --no-binary=:all:
# clear pip's cache
$ rm -rf $HOME/.cache/pip/*
# now turn off your Internet connection
$ pip install pyjwt --no-index --find-links=vendor/
```

I've worked around it by using PyJWT's wheel, but that forced me to separate my requirements files, because I need some of dependencies (like cryptography) in source form to be multi-platform.

**Comment by ysgard** [comment]
This bug has bit me too.  It's bothersome because even if you provide pytest-runner on an internal pip server,  PyJWT ignores it and tries to install pytest-runner from the internet. 

Thanks @mbultrow for the suggestion about separate requirements files for pre-installing deps - that seems like a decent workaround.
