### ISSUE TITLE
Doc issue : cannot get private key from a certificat

### ISSUE THREAD

**Issue by tgermain** [jpadilla/pyjwt#193]
In the FAQ, the doc says : 

``` python
from cryptography.x509 import load_pem_x509_certificate
from cryptography.hazmat.backends import default_backend

cert_str = "-----BEGIN CERTIFICATE-----MIIDETCCAfm..."
cert_obj = load_pem_x509_certificate(cert_str, default_backend())
public_key = cert_obj.public_key()
private_key = cert_obj.private_key()
```

`public_key = cert_obj.public_key()` is perfectly legit and documented in cryptography.

On the other hand, `private_key = cert_obj.private_key()` does not exist, at least with cryptography 1.0.1. (I did not check older versions of cryptography).
Also I thought the private key was not present in an x509 certificate. 

To get the private key you can use : 

``` python
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization

with open("/path/to/privatekey.pem", "rb") as key_file:
    private_key = serialization.load_pem_private_key(      
        key_file.read(),                                   
        password=None,                                     
        backend=default_backend(),                         
    )                                                      
jwt.encode({'some': 'payload'},private_key, algorithm='RS256')
```

I'll make a PR to update this part of the documentation if you thinks thats useful.

**Comment by tld** [comment]
The private key is never present in the certificate, but it is possible to throw them into the same file (or string in this case).  That could also be the reason that .private_key() doesn't exist (no private key found in cert), but I don't know for sure.

**Comment by mark-adams** [comment]
@tgermain Feel free to submit any PR that you think might improve the documentation :+1:
