### ISSUE TITLE
Why can't I decode this token?

### ISSUE THREAD

**Issue by chrismbeckett** [jpadilla/pyjwt#198]
I go to this site and generate a token:

http://jwtbuilder.jamiekurtz.com/

I go to this site and verify it works and signature is valid:

http://jwt.io/

I try to decode with this library and I get 'signature verification failed'.

**Comment by mark-adams** [comment]
Hi @chrismbeckett,

Thanks for reaching out. I'm able to decode the token without issue:

```python
import jwt
secret = 'qwertyuiopasdfghjklzxcvbnm123456'
token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE0NTU0NTQ4NDEsImV4cCI6MTQ4Njk5MDg0MSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.bkQEFDXsh8Ulwtv7rsbiBe3dmHVSHc5f-zWlu9KOldA'

jwt.decode(token, secret, audience='www.example.com')
``` 

You may be running into trouble with the `audience=` claim. PyJWT validates the `aud` claim in the token against the `audience=` arg to `jwt.decode()`. If you do not specify an `audience=` argument and an `aud` claim is found, you will receive a `jwt.exceptions.InvalidAudienceError` when running `decode()`

Alternatively, you could bypass `aud` verification, by passing `options={'verify_aud': False}` to `jwt.decode()` but that's not recommended since it bypasses a security feature. 

The preferred usage in production is to define a distinct `aud` claim value for your application and then ensure that all tokens meant for your application use this value and you pass the same value to `jwt.decode()`

**Comment by chrismbeckett** [comment]
Thanks for the response. I should be able to get back to this and try out your suggestions today or tomorrow. One note however, is that the error I am getting does say 'signature verification failed'. I am guessing now that is a catch-all for anything wrong with the token?

**Comment by mark-adams** [comment]
Good point! DecodeError('Signature verificiation failed') indicates that one of three scenarios has taken place:

1. The claimset inside the token has been modified so the signature fails to verify
2. The signature inside the token has been modified so the signature fails to verify
3. The wrong key (or no key) is being passed to jwt.decode()

I'd take a look at those and see if any apply.  Most likely, the third one is going to be the reason for the error you're seeing.

**Comment by chrismbeckett** [comment]
Added the audience parameter as you suggested but still getting the error:

```python
token='<copied token from website>'
payload = jwt.decode(token, secret='qwertyuiopasdfghjklzxcvbnm123456', audience='www.example.com')
```

My error log shows:

```sh
2016-02-19 03:09:31,257 WARNI [venusian][waitress] Signature verification failed 
```

**Comment by chrismbeckett** [comment]
Ok, this worked:

```python
options = {'verify_aud': False, 'require_sub': True}
payload = jwt.decode(token, 'qwertyuiopasdfghjklzxcvbnm123456', options=options)
````

**Comment by chrismbeckett** [comment]
I spoke too soon. I moved to another fresh VM to prepare for a deploy and now the same problem is back, even with the addition of the options to ignore audience. Seriously, I have been at this for hours, there has to be a dependency missing, or something that can cause this?

**Comment by chrismbeckett** [comment]
I got it to work with python-jose.

**Comment by mark-adams** [comment]
Hi Chris! That seems really strange. Would you mind pasting a complete example token and secret that are giving you trouble so we can confirm the issue?

Thanks!

**Comment by MUGABA** [comment]
Hey guys, AttributeError: 'AttributeError' object has no attribute 'decode' am getting that error yet i have exported the environment variables 

i can not decode my token

**Comment by chidimo** [comment]
Here in 2024 and I am stuck with this problem.

**Comment by MUGABA** [comment]
> Here in 2024 and I am stuck with this problem.

JWT tokens. If your using the node.js or Javascript. use something called jwt-decode.

**Comment by chidimo** [comment]
> > Here in 2024 and I am stuck with this problem.
> 
> JWT tokens. If your using the node.js or Javascript. use something called jwt-decode.

I'm using pyjwt in python to decode it. When I turn off signature verification it decides it correctly.

I'm not sure what the problem is. I have the correct secret and algorithm. I think it would have been helpful if the error message were more specific.

**Comment by MUGABA** [comment]
> > > Here in 2024 and I am stuck with this problem.
> > 
> > 
> > JWT tokens. If your using the node.js or Javascript. use something called jwt-decode.
> 
> I'm using pyjwt in python to decode it. When I turn off signature verification it decides it correctly.
> 
> I'm not sure what the problem is. I have the correct secret and algorithm. I think it would have been helpful if the error message were more specific.

import jwt
>>> encoded_jwt = jwt.encode({"some": "payload"}, "secret", algorithm="HS256")
>>> print(encoded_jwt)
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb21lIjoicGF5bG9hZCJ9.4twFt5NiznN84AWoo1d7KO1T_yoc0Z6XOpOVswacPZg
>>> jwt.decode(encoded_jwt, "secret", algorithms=["HS256"])
{'some': 'payload'}

**Comment by MUGABA** [comment]
https://pyjwt.readthedocs.io/en/latest/

**Comment by metaladmiral** [comment]
One thing that worked for me:
the "exp" value should always be an integer.

I was using this utility function before to generate token

```
def generate_jwt_token(payload):
    secret_key = settings.SECRET_KEY/

    payload[0]["exp"] = (
        datetime.utcnow() + timedelta(days=7)
    ).isoformat()  # Expiration time

    token = jwt.encode(payload[0], key=secret_key, algorithm="HS256")

    return token
```


and shifted to timestamp() from isoformat(), which returns integer value of time.

This worked:

```
def generate_jwt_token(payload):
    secret_key = settings.SECRET_KEY

    payload[0]["exp"] = (datetime.utcnow() + timedelta(days=7)).timestamp()

    token = jwt.encode(payload[0], key=secret_key, algorithm="HS256")

    return token

```
