### ISSUE TITLE
Critical vulnerabilities in JSON Web Token libraries

### ISSUE THREAD

**Issue by jakubczaplicki** [jpadilla/pyjwt#200]
Have this vulnerability : "[Critical vulnerabilities in JSON Web Token libraries](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/)" been addressed ? If so which commits have fixed it ?

**Comment by jpadilla** [comment]
Yup. https://github.com/jpadilla/pyjwt/releases/tag/1.0.0
