### ISSUE TITLE
Can we force reading expired JWT without throwing "signature has expired" error ?

### ISSUE THREAD

**Issue by lapinvert** [jpadilla/pyjwt#207]
When client send me an expired JWT in my REST API "refresh token" endpoint, I need to read JWT to know if it is valid, and verify some value in the claim before I accept to reissue a new JWT.

However I can't even process it because of the "signature has expired" error raised before I can.

Is there any solution you would advice me ?

**Comment by jpadilla** [comment]
You can do something like:

```python
jwt.decode(jwt_payload, verify=False)
```

or better yet

```python
jwt.decode(jwt_payload, 'secret', options={'verify_exp': False})
```

**Comment by lapinvert** [comment]
Thank you so much !

**Comment by cglacet** [comment]
By the way, don't use `jwt.decode(jwt_payload, verify=False)` it also ignores the secret which means anyone could forge a fake token (most likely you don't want that).

**Comment by maximeish** [comment]
You can encode your token and set a higher expiration period by doing:

`
token = jwt.encode({ 'exp': datetime.datetime.utcnow() + datetime.timedelta(days=**1**, seconds=**10**),
                                     'payload': value
                                  }, 'secret')
`

Here I set the token to expire after 1 day and 10 seconds. Hope this is helpful :)
