### ISSUE TITLE
NotImplementedError thrown for RS256 algorithms

### ISSUE THREAD

**Issue by senyorails** [jpadilla/pyjwt#210]
//sample line of code to reproduce
>>>import jwt
>>>jwt.encode({'email':'testUser@mailinator.com','firstName':'John','lastName':'Doe'}, 'secrets' , algorithm='RS256')

**Comment by mark-adams** [comment]
In order to use RS256, you need to have the `cryptography` package installed per the documentation.

`pip install cryptography`

**Comment by mark-adams** [comment]
@senyorails Since this hasn't been updated in almost a month, I'm closing it.
