### ISSUE TITLE
Bugfix release: 1.4.2

### ISSUE THREAD

**Issue by mark-adams** [jpadilla/pyjwt#215]
@jpadilla Can we do a bugfix release?

**Comment by jpadilla** [comment]
@mark-adams sure thing, want to bump up versions and tags? I'll publish to PyPI soon after

**Comment by mark-adams** [comment]
@jpadilla Its done: https://github.com/jpadilla/pyjwt/releases/tag/1.4.2

**Comment by jpadilla** [comment]
@mark-adams just published v1.4.2, thanks again for all the hard work. Yeah, good catch regarding our changelog. Haven seen `pbr` yet, got a link to a project that uses it?
