### ISSUE TITLE
'module' object has no attribute 'decode'

### ISSUE THREAD

**Issue by huzhenjie** [jpadilla/pyjwt#224]
> 'module' object has no attribute 'decode'

```
>>> jwt.decode(encoded, 'secret', algorithms=['HS256'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'decode'
```

**Comment by mark-adams** [comment]
Do you by any chance have a `jwt` directory or a `jwt.py` file in your PYTHONPATH anywhere? These can override the `jwt` import and cause this problem.

An easy way to check would be to give us the output you see when you run:

```
import jwt
print(jwt.__file__)
```

**Comment by mark-adams** [comment]
Is there any chance your project contains a folder called "jwt"? If so,
Python will import that module instead.

You could also check this by seeing what the value of jwt.__file__ is.
