### ISSUE TITLE
Is algorithm 'RS256' working

### ISSUE THREAD

**Issue by nv2908** [jpadilla/pyjwt#230]
Is 'RS256' algorithm working? Giving 'Algorithm not supported' exception.

**Comment by vimalloc** [comment]
Looks like you might need another dependency installed to use that RS256: https://github.com/jpadilla/pyjwt/issues/210

**Comment by nv2908** [comment]
It worked. Thanks

**Comment by jpadilla** [comment]
I've seen many people getting tripped by this. We should definitely improve error message here to suggest installing missing dependencies for those algorithms. Anyone want to tackle this?

**Comment by vimalloc** [comment]
I could create a PR for this. Can likely have it done later today (if no
one else is actively working on it).
