### ISSUE TITLE
Encrypt tokens

### ISSUE THREAD

**Issue by daredevil82** [jpadilla/pyjwt#233]
Reading the documentation, one can be excused if the impression is given that the contents of a JWT are encrypted during the encoding process.  However, they are not, and if a developer includes sensitive information in the payload of a token, it is _very_ easy to retrieve the data.

	import jwt, base64

	token = jwt.encode({'some':'payload'}, 'secret', algorithm='HS512')
	algo, text, signature = token.split(b'.')
	decoded_text = base64.decodebytes(text)
	print(decoded_text)
	> b'{"some":"payload"}

In fact, you don't even need to split the token up to get the information!

    In [10]: base64.decodebytes(token)
    Out[10]: b'{"typ":"JWT","alg":"HS512"}{"some":"payload"}\x12\x03\'\xcd\xc2X\xacIN7OA\xc0\xec\x1a\xa9\x16{\n\xad\xf4\x9f\xb7 M\x91\x89\xaa\xd2\xb5`w\xc6\xd5\xc1\xa7\x18\x9a\t\x1b\x03\x8b\x8f\xa0\x16\x83\xdbZ;"M\xdc9\xeaw\xd3Wy0\xa3L,\x00'

This is a very significant issue, since the encoding process gives a false sense of security.

**Comment by vimalloc** [comment]
That is how JSON Web Tokens work, it's part of their specification. If you want the token to be encrypted, you should use JSON Web Signature (JWS) instead of JWT.

If I'm not mistaken, this library includes options for both. 

Note: JWTs are secure from tampering, but like you said, they aren't secure from someone looking at what data is stored on the token, which could be problematic if sensitive data is stored on the token.

**Comment by mark-adams** [comment]
@daredevil82 To clarify, there are three main components to the JOSE specification.
- JSON Web Signature (JWS)
- JSON Web Tokens (JWT)
- JSON Web Encryption (JWE)

All three are very similar but all have distinctly different characteristics.

A [JSON Web Signature](https://tools.ietf.org/html/rfc7515) (JWS) allows you to create a digital signature over some data (a string, some bytes, key-value pairs, etc.) to ensure data integrity and authenticity. (i.e. the payload data has not been modified and it can be verified that it came from a specific entity. The JWS does NOT protect the confidentiality of the data. Anyone who can get ahold of the JWS can decode and read the bytes that were signed. You should not put secret data in a JWS.

A [JSON Web Token](https://tools.ietf.org/html/rfc7519) (JWT) is a JSON Web Signature where the payload is a series of key-value pairs known as the claims. Some claims have specific value that triggers validation logic (like the `exp` claim which defines when the token should expire and no longer be considered valid). Just like the JWS, a JWT is used to ensure integrity and authenticity but does NOT protect the confidentiality of the data. Anyone who gets ahold of the JWT can decode and read the claims contained in the JWT. You should not put secret data in a JWT.

A [JSON Web Encryption](https://tools.ietf.org/html/rfc7516) (JWE) is a JSON-based data structure which protects the confidentiality of the payload by encrypting it and can sometimes ensure integrity of the payload data (depending on the algorithm chosen). A JWE can be used to store / transport secret data.

PyJWT currently supports creation and verification of JWS and JWTs but not JWEs.

For more information, check out the RFCs linked above.
