### ISSUE TITLE
Getting NotImplementedError: Algorithm not supported for EC256 with cryptography installed

### ISSUE THREAD

**Issue by colemeister** [jpadilla/pyjwt#240]
I've installed both pyjwt and cryptography using pip install, yet I'm still getting NotImplementedError when I try calling jwt.encode() passing 'EC256' as the algorithm. Any idea why this could be the case? After reading similar issues i'm certain it should be working the way I have it.

**Comment by vimalloc** [comment]
Are you meaning to use ```ES256``` instead of ```EC256```? There is a list of algorithms here: https://pyjwt.readthedocs.io/en/latest/algorithms.html

**Comment by colemeister** [comment]
Wow... Definitely feel like a noob but I guess that's how it's not gonna happen again! That was it, thank you for your help!
