### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jpadilla** [jpadilla/pyjwt#241]
We're a bit overdue with releasing a new version. I've created a [new milestone](https://github.com/jpadilla/pyjwt/milestone/5?closed=1) to keep track of the things that are going into this version. This will also help me update the changelog.

@mark-adams whenever you got a chance, could you take a look at it and see if there's anything else missing? Also are we ok bumping a patch version? Now that I think of it it might be a minor.

**Comment by lookuptable** [comment]
When does v1.4.3 is planned to be released?

**Comment by jpadilla** [comment]
@lookuptable thanks for the nudge.

@mark-adams I think we should just bump up a minor version instead, since theres a couple new things in there. Thoughts?

**Comment by mark-adams** [comment]
@jpadilla Yea, bumping the minor version works for me. I created a PR: #255 that is waiting on your approval now

**Comment by jpadilla** [comment]
Just released [v1.5.0](https://github.com/jpadilla/pyjwt/releases/tag/1.5.0). Thank you all! 🎉
