### ISSUE TITLE
RS256 Public Key issue

### ISSUE THREAD

**Issue by dbinetti** [jpadilla/pyjwt#247]
When I follow the docs [here](https://github.com/jpadilla/pyjwt/blob/master/docs/faq.rst#how-can-i-extract-a-public--private-key-from-a-x509-certificate) I get the following error: `TypeError: initializer for ctype 'char[]' must be a bytes or list or tuple, not str`.  

My ultimate goal is to figure out how to populate the JWT_PUBLIC_KEY in djangorestframework-jwt so that I can use RS256 encryption.  But I'm getting stuck because I'm wholly unfamiliar with cryptography.  I believe I'm doing everything properly, but how do I debug  this?  Is it a bug on PyJWT?  Or is the certificate malformed (this is from Auth0, my identity provider?) Certificate attached, thanks.

```
-----BEGIN CERTIFICATE-----
MIIC+jCCAeKgAwIBAgIJbuZM6FlzJ6TDMA0GCSqGSIb3DQEBBQUAMCQxIjAgBgNV
BAMTGWJhcmJlcnNjb3JlLWRldi5hdXRoMC5jb20wHhcNMTYxMDI2MjAzNDE0WhcN
MzAwNzA1MjAzNDE0WjAkMSIwIAYDVQQDExliYXJiZXJzY29yZS1kZXYuYXV0aDAu
Y29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArktLSct+7BT6SDLJ
k6P7esPEk2rWTd6+S97gB8oZ9I4WTiGx7jsPgoYn9pUltnHF2r0N1WuOM8UCUMfk
b/lwHcpBGsNx2cxsvr0oVsgKEynJNn0ynRCR2EH7b/iYrtOtMyE1CXtMMgT9vMhS
e/mE8VxsTvgev1nQmR8lq/jXZvLY068/BbicWsrJ11/7toSiJEMH3yEwzlK7ZRDj
Oorp0sp3//ZCZeP4ep9SwK/dNthUgAe1yfQokKQCnW5aMYYZgMG4RDIKND28PGMe
7QmesTbSzoXTPDZBMLJC0o/CSZlQrPzg5SmfyGO0sl+ZnWt9PBeCYjLgtBbKDOH9
o8gNTQIDAQABoy8wLTAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBS9m0sa23+rX1a1
3/2+h9f2UTlrzDANBgkqhkiG9w0BAQUFAAOCAQEALsbWOoKVb4hEFl7akai9bqRK
DMxXf6ZBu7tQMFVDE3xr5Rzc11aeyUCWA9oIrv07JNHQI1OPrXHSKdd+UDAiO2N1
pTIfrOjySNxBoTkr0IJWp+SQjiNr+vvbJGSgThvebHmxNVIQ+WQosVmWHobuZ+tF
LXyoMAxse01/vNGW3LqsMWG32icIQ4Xra2wKmXag/oQGlu4NASRuEhtP8Lp47v1D
m+rablf5MmFd3dtErVU9a3cqeGUEIjYhTK18slv55LOEdMPklRgkDUlvCIxd3RA1
yZw/f9vAojVPQmXNY95Kzg14aqhiRGSeNhG6BRMnDvzm3/rx4UezNmLxT6F1cg==
-----END CERTIFICATE-----
```

**Comment by mark-adams** [comment]
PyJWT expects public keys to be in either PEM or SSH format. The example you posted is actually a x509 certificate in PEM format; not a public key in PEM format. 

You can extract the public key from the certificate using the following OpenSSL command:
```
openssl x509 -pubkey -noout -in cert.pem  > pubkey.pem
```
