### ISSUE TITLE
PyJWT-1.4.2 doesn't work with cryptography-1.7.2 properly.

### ISSUE THREAD

**Issue by sumitb** [jpadilla/pyjwt#250]
`import jwt`
`jwt.encode(payload, self.signing_key, algorithm=self.jwt_algo)`
I get this error: 
File ".../egg/jwt/api_jwt.py", line 56, in encode
  File ".../egg/jwt/api_jws.py", line 98, in encode
  File ".../egg/jwt/algorithms.py", line 171, in prepare_key
TypeError: Expecting a PEM-formatted key.

The issue started occurring as I introduced cryptography-1.7.2 to the system. Earlier it was using the PyCrypto module.

**Comment by mark-adams** [comment]
@sumitb It's hard to analyze this further without knowing what `type(self.signing_key)` is. Can you provide more detail?

**Comment by mark-adams** [comment]
Closing due to lack of response
