### ISSUE TITLE
Bad name reference of the CLI command and no information in the DOCs about it

### ISSUE THREAD

**Issue by mrsarm** [jpadilla/pyjwt#259]
Release https://github.com/jpadilla/pyjwt/releases/tag/1.5.0 says that the new name of the CLI is `jwt-cli`, but the real name is `pyjwt`.

Also, it would be useful if in the README file and in the [documentation](https://pyjwt.readthedocs.io/en/latest/) pages to have a reference about the command and its usage.

**Comment by jpadilla** [comment]
@mrsarm ah you're right about that. I'lll update the release note, would you want to send over a pull request adding the CLI to the docs?

**Comment by jpadilla** [comment]
https://pyjwt.readthedocs.io/en/latest/
