### ISSUE TITLE
Token expiration is not checked if token doesn't have an `exp` value.

### ISSUE THREAD

**Issue by rinatio** [jpadilla/pyjwt#261]
Hi,

If someone generates a token without expiration date, then expiration will not be checked. Is it by design? See https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L103.

Originally found via [django-rest-framework-jwt](https://github.com/GetBlimp/django-rest-framework-jwt/issues/331)

**Comment by jgehrcke** [comment]
Yes. this is by design. If no `exp` claim is encoded in the token then this token is meant to have an infinite lifetime. RFC 7519 says 

>  Use of this claim is OPTIONAL.

(https://tools.ietf.org/html/rfc7519#section-4.1.4)

**Comment by rinatio** [comment]
@jgehrcke Thanks for clarification!
