### ISSUE TITLE
Mind if I add type annotations for this library to typeshed?

### ISSUE THREAD

**Issue by toolness** [jpadilla/pyjwt#265]
Hello!

I'm interested in adding [mypy](http://www.mypy-lang.org/) type annotations for this library to the repository of third-party typings at https://github.com/python/typeshed/pull/1281.

Do you mind if I do this?

I can also contribute the typings to this repository if you like, just let me know!

**Comment by jpadilla** [comment]
@toolness I'm definitely good with this, but would keep the typings only on python/typeshed. Thanks!
