### ISSUE TITLE
(InvalidIssuedAtError) not implemented for future iat's ?

### ISSUE THREAD

**Issue by marcelofern** [jpadilla/pyjwt#266]
Hi,

According to the docs, jwt.exceptions.InvalidIssuedAtError should be raised when iat has a future date.
[reference](https://pyjwt.readthedocs.io/en/latest/api.html)

**Issue**: 
I am trying to raise: InvalidIssuedAtError

**What I am doing**: 

I am using a token with a future iat timestamp, something like:
```
future_payload = {
                        'username': 'test@test.com',
                        'iat': datetime.now() + timedelta(seconds=500),
                        'exp': datetime.now() + timedelta(seconds=1000)
                        }

future_token = encode(future_payload, TOKEN_SECRET, algorithm=TOKEN_ALGORITHM)
decoded = decode(future_token, TOKEN_SECRET, algorithms=[TOKEN_ALGORITHM])
```
well, this works perfectly, the problem is that it shouldn't :P 
I looked at the code and the only reference for this exception that i have found is this one:
`raise InvalidIssuedAtError('Issued At claim (iat) must be an integer.')`

Am I correct? Or I am very blind-sided here? =P

**Comment by mark-adams** [comment]
We removed that functionality because it was not very standard and tripped up a lot of people. See #190.

A pull request would be welcome to update the docs.
