### ISSUE TITLE
Prefer pycryptodome over pycrypto

### ISSUE THREAD

**Issue by nueverest** [jpadilla/pyjwt#268]
pycrypto is no longer actively maintained.  

pycryptodome has stepped up to take its' place as an up-to-date drop in replacement for pycrypto https://github.com/Legrandin/pycryptodome

**Comment by mark-adams** [comment]
We don't support PyCrypto currently. The PyCrypto support has been left in solely to allow for backward compatiblity with Google App Engine which doesn't support compiling C extensions. `cryptography` is the supported library to use with PyJWT.

**Comment by nueverest** [comment]
Okay. Thanks for the clarification.
