### ISSUE TITLE
How can I shorten the length of the token ?

### ISSUE THREAD

**Issue by omidraha** [jpadilla/pyjwt#283]
Hi,
I have the same issue as [#73](https://github.com/tymondesigns/jwt-auth/issues/73), my token with HS256 algorithm has length of around 256 bytes.
I want to write this token to one device, and since reading on this device is slow ( 16 seconds for 1024 bytes),
It takes nearly 5 (4+1) seconds to read every token.
Is there a way for that or not? 
Thanks.

**Comment by jpadilla** [comment]
Same conclusion as that issue. You might need to use some other mechanism to fit your constraints.
