### ISSUE TITLE
Release v1.5.3

### ISSUE THREAD

**Issue by mark-adams** [jpadilla/pyjwt#288]
I think we have enough to do a release. 

In particular, I think some users are waiting on 3def8d80eb3936dbcead07e86b6aee96ba07bfe9 to upgrade `cryptography`.

Thoughts? @jpadilla

**Comment by jpadilla** [comment]
@mark-adams thanks, just released v1.5.3 https://github.com/jpadilla/pyjwt/releases/tag/1.5.3
