### ISSUE TITLE
Inconsistent documentation around IATs in the future

### ISSUE THREAD

**Issue by maxrothman** [jpadilla/pyjwt#290]
I can see that in #190, you decided to stop validating that IATs are not in the future. There was also some discussion about adding an option to turn that validation back on, but it didn't seem to make it into the final PR. In any case, [the documentation](http://pyjwt.readthedocs.io/en/latest/api.html?highlight=iat#jwt.exceptions.InvalidIssuedAtError) still indicates that the validation is done. Where does IAT validation currently stand?

**Comment by mark-adams** [comment]
The current behavior is that the IAT claim is not checked to see if it's in the future. The documentation should be changed to match.

**Comment by maxrothman** [comment]
Is there interest in adding back an optional check?
