### ISSUE TITLE
Verifying a JWS when decoding it triggers an error

### ISSUE THREAD

**Issue by bogdanpetrea** [jpadilla/pyjwt#293]
I am getting the following message when trying to decode a JWS string:
```python
>>> assert payload == json.loads(PyJWS().decode(jws=jws, key=key, algorithms=['RS256']))

    def verify(self, msg, key, sig):
        try:
>           key.verify(sig, msg, padding.PKCS1v15(), self.hash_alg())
E           AttributeError: '_RSAPrivateKey' object has no attribute 'verify'
```
Skipping the verification part with `options={'verify_signature': False}` works as expected.

I might be wrong but, in the [cryptography docs](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#verification) it's stated that the public key should be used for verification. I assume a check should be made in the `RSAAlgorithm.verify` method (which can be found [here](https://github.com/jpadilla/pyjwt/blob/master/jwt/algorithms.py#L317)).

```python
def verify(self, msg, key, sig):
    if isinstance(key, RSAPrivateKey):
        key = key.public_key()
    try:
        key.verify(sig, msg, padding.PKCS1v15(), self.hash_alg())
    [...]
```

Tested with cryptography versions 2.0.3, 1.9 and 1.8.2.

**Comment by cwiki** [comment]
I'm having similar issues. I am able to verify my certificate on the JWT.io site.

**Comment by Sebubu** [comment]
Same here
