### ISSUE TITLE
Conda Install failure of noarch/pyjwt 1.5.3 on Windows 7

### ISSUE THREAD

**Issue by tbsnell** [jpadilla/pyjwt#294]
Attempted to install pyjwt with Anaconda and received this error:

-----------------------------------------------------------------------------------
ERROR conda.core.link:_execute_actions(337): An error occurred while installing
package 'conda-forge::pyjwt-1.5.3-py_0'.
CondaError: Cannot link a source that does not exist. C:\Users\tsnell\AppData\Lo
cal\Continuum\Anaconda2\Scripts\conda.exe
Attempting to roll back.

CondaError: Cannot link a source that does not exist. C:\Users\tsnell\AppData\Lo
cal\Continuum\Anaconda2\Scripts\conda.exe
-----------------------------------------------------------------------------------

Current conda Install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : C:\Users\tsnell\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\tsnell\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\tsnell\AppData\Local\Continuum\Anaconda2\envs
                          C:\Users\tsnell\AppData\Local\conda\conda\envs
                          C:\Users\tsnell\.conda\envs
          package cache : C:\Users\tsnell\AppData\Local\Continuum\Anaconda2\pkgs
                          C:\Users\tsnell\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\tsnell\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/2.7.13 Windows/7 Windows/6.1.7601    
          administrator : False
-----------------------------------------------------------------------------------------

As a work-around, I installed the 1.5.2 version for windows (win-64/pyjwt-1.5.2.py36_1.tar.bz2) and that installed fine.

**Comment by whimian** [comment]
Same problem on Windows 10 x64

**Comment by jpadilla** [comment]
Haven't used conda before, so anyone is welcome to debug this further.
