### ISSUE TITLE
Can't use EllipticCurvePrivateKey to encode token with algorithm ES256

### ISSUE THREAD

**Issue by emmlejeail** [jpadilla/pyjwt#311]
I am trying to use an EllipticCurvePrivateKey read from a .key file to encode a token using algorithm ES256, but I always get back the following error happening in algorithms.py:
Here is my python code:
```
token = jwt.encode({"scope": [ "apps" ]}, key, algorithm="ES256")
```
Here is the error I get back:
```
in encode
    json_payload, key, algorithm, headers, json_encoder
in encode
    signature = alg_obj.sign(signing_input, key)
in sign
   der_sig = key.sign(msg, ec.ECDSA(self.hash_alg()))
AttributeError: '_EllipticCurvePrivateKey' object has no attribute 'sign'
```
Where is it coming from?

**Comment by ogudino** [comment]
I would make sure that you have cryptography installed.

pip install cryptography 

I can encode using ES256 but decoding doesn't seem to work for me. I opened a new issue for that.

**Comment by P3nt3st3r123** [comment]
Just fix this in file jwt/algorithm.py
class ECAlgorithm
```
try:
--      key.verify(der_sig, msg, ec.ECDSA(self.hash_alg()))
++    key.public_key().verify(der_sig, msg, ec.ECDSA(self.hash_alg()))
    return True
except InvalidSignature:
    return False
```
