### ISSUE TITLE
Python type hints

### ISSUE THREAD

**Issue by mark-adams** [jpadilla/pyjwt#312]
[PEP 484](https://www.python.org/dev/peps/pep-0484/) and [PEP 526](https://www.python.org/dev/peps/pep-0526/) introduced the concept of "type hints" which allow Python code to have inline type declarations to make it easier for editors and static analysis tools to work with Python code.

```python
def add(a: int, b: int) -> int:
    return a + b
```

To maintain Python 2.7 compatibility, we'd have to use the comment-based syntax:

```python
def add(a, b):
    # type: (int, int) -> int
    return a + b
```

Is this something that might be worthwhile for us to implement?

**Comment by dmwyatt** [comment]
You can run mypy against the code and it will tell you if your types don't make sense.

**Comment by jacopofar** [comment]
I'm happy to give it a try, and hopefully include mypy to travis config

**Comment by jacopofar** [comment]
Opend PR #344

**Comment by aklim007** [comment]
@jacopofar hello, in `decode` methods `jwt` and `jws` parameters may by bytes, not only str.

**Comment by jdufresne** [comment]
Python type hints have since been added and are being improved upon. Perhaps it is okay to close this?
