### ISSUE TITLE
Using PyJWT on App Engine

### ISSUE THREAD

**Issue by intonarumori** [jpadilla/pyjwt#317]
As suggested by the documentation PyJWT could be used in environments where `cryptography` cannot be installed (ex. App Engine).

In a local virtualenv I installed `cryptography`, `ecdsa`, `pycrypto` to test my code.

Code using the default implementation works as expected:
```
import jwt
key = "<key read from .p8 file>"
alg = 'ES256'
headers = { "alg": alg, "key": "value" }
payload = {"key": "value"}
token = jwt.encode(payload, key, algorithm=alg, headers=headers)
```

However using the suggested workaround registering the `ecdsa` algorithm and using the exact same code and key results in an error:
```
import jwt
from jwt.contrib.algorithms.py_ecdsa import ECAlgorithm

jwt.unregister_algorithm('ES256') # needs to be unregistered first for some reason
jwt.register_algorithm('ES256', ECAlgorithm(ECAlgorithm.SHA256))

key = "<key read from .p8 file>"
alg = 'ES256'
headers = { "alg": alg, "key": "value" }
payload = {"key": "value"}
token = jwt.encode(payload, key, algorithm=alg, headers=headers)
```
Error:
```
Traceback (most recent call last):
...
  File "./ENV/lib/python2.7/site-packages/jwt/api_jwt.py", line 56, in encode
    json_payload, key, algorithm, headers, json_encoder
  File ".../ENV/lib/python2.7/site-packages/jwt/api_jws.py", line 102, in encode
    key = alg_obj.prepare_key(key)
  File ".../ENV/lib/python2.7/site-packages/jwt/contrib/algorithms/py_ecdsa.py", line 44, in prepare_key
    key = ecdsa.SigningKey.from_pem(key)
  File ".../ENV/lib/python2.7/site-packages/ecdsa/keys.py", line 159, in from_pem
    privkey_pem = string[string.index(b("-----BEGIN EC PRIVATE KEY-----")):]
ValueError: substring not found
```

As I understand it `ecdsa` expects a different key format.
- so I either convert my key to the expected format (still looking into this, suggestions welcome)
- or PyJWT handles that conversion to provide a hassle-free fallback when needed

This issue might be `ecdsa` specific and considered out of scope for this project, but I would love to hear suggestions.

As a side note: I had to use `unregister_algorithm` before `register_algorithm` which wasn't mentioned in the documentation.

**Comment by danielkramer** [comment]
Were you ever able to get this working? I'm getting the same error:

```
File ".../ENV/lib/python2.7/site-packages/ecdsa/keys.py", line 159, in from_pem
    privkey_pem = string[string.index(b("-----BEGIN EC PRIVATE KEY-----")):]
ValueError: substring not found
```

**Comment by danielkramer** [comment]
I was able to get this working by converting the key to the EC format.  On my mac:

`openssl ec -in AuthKey.p8 -out AuthKey.pem
`

I found the info for converting between key formats here:

[Command_Line_Elliptic_Curve_Operations](https://wiki.openssl.org/index.php/Command_Line_Elliptic_Curve_Operations)
