### ISSUE TITLE
Can't use EllipticCurvePrivateKey to decode token with algorithm ES256

### ISSUE THREAD

**Issue by ogudino** [jpadilla/pyjwt#318]
This is the stack trace that I get 

  File "music_token.py", line 35, in <module>
    jwt.decode(token, secret, algorithms=[alg])
  File "/Library/Python/2.7/site-packages/jwt/api_jwt.py", line 78, in decode
    jwt, key=key, algorithms=algorithms, options=options, **kwargs
  File "/Library/Python/2.7/site-packages/jwt/api_jws.py", line 140, in decode
    key, algorithms)
  File "/Library/Python/2.7/site-packages/jwt/api_jws.py", line 206, in _verify_signature
    if not alg_obj.verify(signing_input, key, signature):
  File "/Library/Python/2.7/site-packages/jwt/algorithms.py", line 370, in verify
    key.verify(der_sig, msg, ec.ECDSA(self.hash_alg()))

And the relevant code

alg = 'ES256'

time_now = datetime.datetime.now()
time_expired = datetime.datetime.now() + datetime.timedelta(hours=12)

headers = {
        "alg": alg,
        "kid": keyId
}

payload = {
        "iss": teamId,
        "exp": int(time_expired.strftime("%s")),
        "iat": int(time_now.strftime("%s"))
}

if __name__ == "__main__":
        """Create an auth token"""
        token = jwt.encode(payload, secret, algorithm=alg, headers=headers)

        jwt.decode(token, secret, algorithms=[alg])

I have cryptography install. I am trying to get this to work with Python 3.

**Comment by canoeist2018** [comment]
you must use public key to decode jwt token, and this:
jwt.decode(token, public)

the public is come from:
from cryptography.x509 import load_pem_x509_certificate
from cryptography.hazmat.backends import default_backend
public = load_pem_x509_certificate(ecc_public_key_in_bytes, default_backend()).public_key()
