### ISSUE TITLE
Problem decoding token

### ISSUE THREAD

**Issue by Oxyrus** [jpadilla/pyjwt#319]
Hello, thanks for making pyjwt!

I've been trying to use it in my Django application, however, something weird is happening: I can't decode the token!

This is how I'm creating the token

```
token = jwt.encode({
    'user_id': user.id
}, key='secret', algorithm='HS256')
```

And creating a token with `user_id: 1` gives me this token `b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.J_RIIkoOLNXtd5IZcEwaBDGKGA3VnnYmuXnmhsmDEOs'`, however it says invalid signature in [https://jwt.io/](https://jwt.io/) for some reason.

Trying to decode my token in the server throws this error:

```
Traceback (most recent call last):
  File "/home/andres/venv/zyru/lib/python3.6/site-packages/jwt/api_jws.py", line 170, in _load
    header_data = base64url_decode(header_segment)
  File "/home/andres/venv/zyru/lib/python3.6/site-packages/jwt/utils.py", line 42, in base64url_decode
    return base64.urlsafe_b64decode(input)
  File "/home/andres/venv/zyru/lib/python3.6/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/home/andres/venv/zyru/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andres/Code/Python/zyru-api/members/schema.py", line 41, in get_user
    decoded = jwt.decode(token, 'secret')
  File "/home/andres/venv/zyru/lib/python3.6/site-packages/jwt/api_jwt.py", line 70, in decode
    payload, signing_input, header, signature = self._load(jwt)
  File "/home/andres/venv/zyru/lib/python3.6/site-packages/jwt/api_jws.py", line 172, in _load
    raise DecodeError('Invalid header padding')
jwt.exceptions.DecodeError: Invalid header padding
``` 

Why is the exception happening?

Thanks a lot!

**Comment by vimalloc** [comment]
Try decoding the token to utf-8:

```python
jwt.encode(data, secret, algorithm).decode('utf-8')
```

**Comment by Oxyrus** [comment]
Didn't work @vimalloc here's the code I'm using:

```python
def get_user(info):
    token = info.context.META.get('HTTP_AUTHORIZATION')

    if not token:
        return

    try:
        decoded = jwt.decode(token, 'secret', 'utf-8')
        user = User.objects.get(username=decoded['username'])
        return user
    except:
        raise Exception('User not found')
```

I'm definitely getting the token, because if I check with:

```python
def get_user(info):
    token = info.context.META.get('HTTP_AUTHORIZATION')
    print(token)
```

I get it printed in the console

```
System check identified no issues (0 silenced).
December 15, 2017 - 01:16:27
Django version 2.0, using settings 'zyru.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.J_RIIkoOLNXtd5IZcEwaBDGKGA3VnnYmuXnmhsmDEOs'
```

**Comment by vimalloc** [comment]
This isn't right:
```python
decoded = jwt.decode(token, 'secret', 'utf-8')
```

You want to create the token like such:

```python
data = {'foo': 'bar'}
encoded_token = jwt.encode(data, 'secret', 'HS256').decode('utf-8')
```

and decode it like:

```python
decoded_token = jwt.decode(encoded_token, 'secret', algorithms=['HS256'])
```

**Comment by Oxyrus** [comment]
Thanks a lot @vimalloc that solves the issue!

**Comment by jpadilla** [comment]
@vimalloc thank you for helping out, really appreciate it 🥇

**Comment by akash1551** [comment]
Thanks @vimalloc , You saved me.

**Comment by PauloViniciusBaleeiro** [comment]
Thanks @vimalloc, after spent a whole day in this, i found this issue and, principally, your ask.

**Comment by rahul6612** [comment]
> This isn't right:
> 
> ```python
> decoded = jwt.decode(token, 'secret', 'utf-8')
> ```
> 
> You want to create the token like such:
> 
> ```python
> # The decode call here doesn't decode the jwt, it converts the encoded jwt from
> # a byte string to a utf-8 string.
> data = {'foo': 'bar'}
> encoded_token = jwt.encode(data, 'secret', 'HS256').decode('utf-8')
> ```
> 
> and decode it like:
> 
> ```python
> decoded_token = jwt.decode(encoded_token, 'secret', algorithms=['HS256'])
> ```



> Thanks a lot @vimalloc that solves the issue!

where we will apply this?

**Comment by egor83** [comment]
Thanks again @vimalloc, and for future googlers, this solves the following exceptions:

```
binascii.Error: Invalid base64-encoded string: number of data characters (37) cannot be 1 more than a multiple of 4
...
jwt.exceptions.DecodeError: Invalid header padding
```

**Comment by verhovensky** [comment]
> This isn't right:
> 
> ```python
> decoded = jwt.decode(token, 'secret', 'utf-8')
> ```
> 
> You want to create the token like such:
> 
> ```python
> # The decode call here doesn't decode the jwt, it converts the encoded jwt from
> # a byte string to a utf-8 string.
> data = {'foo': 'bar'}
> encoded_token = jwt.encode(data, 'secret', 'HS256').decode('utf-8')
> ```
> 
> and decode it like:
> 
> ```python
> decoded_token = jwt.decode(encoded_token, 'secret', algorithms=['HS256'])
> ```

Thanks for clarification! Btw if someone using HTTTpie instead of curl - you should NOT include  auth param in quotes " "
