### ISSUE TITLE
Why use local timezones for expiration?

### ISSUE THREAD

**Issue by dmitrybelyakov** [jpadilla/pyjwt#321]
It seems that when passing a UTC datetime object or timesatmp to `encode`, it gets converted to local timezone (by the use of `calendar.timegm` I presume) which results in tokens having local timezone instead of UTC one.

What was the reason for such implementation? Would it not cause problems for cross-timezone applications? Why not just use UTC for everything?

**Comment by jpadilla** [comment]
Hm, can you demonstrate this behavior your seeing?

The standard for JWT defines an `exp` claim for expiration. The expiration is represented as a NumericDate:

> A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds. This is equivalent to the IEEE Std 1003.1, 2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in which each day is accounted for by exactly 86400 seconds, other than that non-integer values can be represented. See RFC 3339 [RFC3339] for details regarding date/times in general and UTC in particular.

This means that the `exp` field should contain the number of seconds since the epoch. We currently convert `exp` datetime to an int here:

https://github.com/jpadilla/pyjwt/blob/7f7d524b78ab98e42e9064f4f2bab5b6e126f766/jwt/api_jwt.py#L43-L46

**Comment by dmitrybelyakov** [comment]
Hi!

Sure, it's actually quite easy:

```python
exp = datetime.datetime.utcnow()
token = jwt.encode(dict(exp=exp), '', 'HS256')
decoded = jwt.decode(token, '', 'HS256')

print(int(exp.timestamp()))
print(decoded['exp'])
```
The last two lines will print a UTC timestamp vs. what is set in the token, which is local time that is off UTC by several hours.

More specifically, when I do `timegm` with a UTC timetuple input (just as you do when encoding) it returns local time:

```python
print(datetime.datetime.fromtimestamp(calendar.timegm(exp.utctimetuple())))
```

**Comment by jpadilla** [comment]
According to [`datetime.timestamp()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp) you'd have to make sure your `datetime` specifies `tzinfo=timezone.utc`. 

```python
>>> exp = datetime.datetime.utcnow()
>>> token = jwt.encode(dict(exp=exp), '', 'HS256')
>>> decoded = jwt.decode(token, '', 'HS256')
>>> assert int(exp.replace(tzinfo=datetime.timezone.utc).timestamp()) == decoded['exp']
```

Also, [`datetime.datetime.fromtimestamp`](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) by default returns the local date and time if `tz` is not specified.

**Comment by dmitrybelyakov** [comment]
You are absolutely right! Thank you!
