### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by mani1950** [jpadilla/pyjwt#325]
We receive a JWT token and we need to decode it, We are able to successfully decode it in jwt.io

token=<<My JWT token>>
public_key=<<'-----BEGINPUBLICKEY-----' \
                     public key goes here  
                   '-----ENDPUBLICKEY-----'

decoded=jwt.decode(token,public_key,algorithms='RS256')

We then get the error. 
binascii.Error: Incorrect padding

Please help. We are stuck with this error since 2 days.  I am unable to post the key or the token for safety reasons.

**Comment by lutzhorn** [comment]
Is the JWT correct? Did you check it using the https://jwt.io/ debugger?

**Comment by mani1950** [comment]
Yes. We are able to see the payload in the debugger. The payload is correct

**Comment by lutzhorn** [comment]
Well, without the JWT and the public key it is hard to tell what is going wrong. Can you include those?

**Comment by jpadilla** [comment]
Make sure your public key is a byte string.

https://pyjwt.readthedocs.io/en/latest/usage.html#encoding-decoding-tokens-with-rs256-rsa
