### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by FilimonovAP81** [jpadilla/pyjwt#330]
Hello,

I have a problem with this lib
I use python 2.7.10 and djangorestframework 3.3.2
I have installed last release pyjwt and if i import jwt then I have MemoryError. If I comment import line then no error messages.

Do you know potentional problem places or may be how I can localized  it?

**Comment by jpadilla** [comment]
Is there a stack trace available, not aware of what in this library might cause an error like that.

**Comment by FilimonovAP81** [comment]
Yes, sorry
It looks like problem in the "/usr/lib64/python2.7/ctypes/__init__.py in _reset_cache, line 279" but this is standard python lib.
full stack trace in attachment
[New Text Document (4).txt](https://github.com/jpadilla/pyjwt/files/1734158/New.Text.Document.4.txt)

**Comment by jpadilla** [comment]
Closing, as I don't see this library being used through that stack trace.

**Comment by FilimonovAP81** [comment]
Hm, but if I remove string "import jwt" from my code then all work fine (exclude decoding my jwt string).
May be your library need some specific access or has conflict this this (ctypes) module?
This is really strange.
