### ISSUE TITLE
JWT strings different between python 2 and 3

### ISSUE THREAD

**Issue by anurag90x** [jpadilla/pyjwt#331]
Because python dictionaries arent ordered by default in 2 and are ordered by default in 3, pyjwt generates different jwt strings because of https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jws.py#L83. This affects applications and libs that are doing jwt comparisons.

Would it be acceptable to change that to use an OrderedDict instead? That way, the jwt strings will be the same between 2 and 3.

**Comment by jpadilla** [comment]
This is not a problem. Spec does not require implementation to order keys.

Here are some previous conversations related to this.

https://github.com/jpadilla/pyjwt/issues/172

https://github.com/jpadilla/pyjwt/issues/248
