### ISSUE TITLE
Unable to verify ES512 token generated by JJWT/java-jwt

### ISSUE THREAD

**Issue by m1schka** [jpadilla/pyjwt#338]
Hey,
I am unable to verify a JWT token generated by JJWT/java-jwt when using the ES512 algorithm.
the token:
```
eyJhbGciOiJFUzUxMiJ9.eyJzdWIiOiIzMjMzMDgzMy00MmUwLTQwYWItYjhiMC02MGVmOTY1MzNiYzUiLCJ0eXBlIjoiU0VTU0lPTiIsImV4cCI6MTUyNDY3NzE4OCwiaWF0IjoxNTIyMDg1MTg4fQ.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMcQj05tszYM0GiPC8kdgFElNUbRvvF178M16QEoZ3j9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJCu8xy4s61cnOtolMSP5ZzpzmLVn0Ovnknf7Bh2w8c
```
pub key:
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJBC9GxLqlGBUjUwGQQnAJgyKxrKu
K0w7W46QcOJ16Q9je8nDtwkos6Rcel+S9iiSe3McaYc/wV2q82FXrrifzg==
-----END PUBLIC KEY-----
```
it looks a bit weird because there are so many null bytes (here in base64 the A), so I decoded the signature, took out the nullbytes with a hex editor and base64 encoded it again and then pyjwt accepts the signature. After reading a lot there seem to be differences in the format of the signature (ASN.1 vs DER vs R+S) but I'm too much of a cryptography noobie to tell the difference. [here is some explanation of the jjwt library](https://github.com/jwtk/jjwt/blob/master/CHANGELOG.md#elliptic-curve-signature-length-bug-fix), [an issue on python-jose](https://github.com/mpdavis/python-jose/issues/47) and [python-ecdsa](https://github.com/warner/python-ecdsa/issues/67)

I don't know if this is an issue with pyjwt, cryptography or openssl (I could trace it down to [this call](https://github.com/jpadilla/pyjwt/blob/54a39aec6a0289ad0fa920dff214753cab9339b9/jwt/api_jws.py#L208)) but I thought it's a good starting point.

Thx a lot in advance,
Michael

**Comment by azizabah** [comment]
@m1schka  - Hey I'm having a very similar issue consuming a JWT that's been created by a Java library utilizing pyJwt. The crazy part for me is that it's okay with the JWT like ~70% of the time but fails the validation otherwise. It ends up failing this check here:
```
def raw_to_der_signature(raw_sig, curve):
    num_bits = curve.key_size
    num_bytes = (num_bits + 7) // 8

    if len(raw_sig) != 2 * num_bytes:
        raise ValueError('Invalid signature')

    r = bytes_to_number(raw_sig[:num_bytes])
    s = bytes_to_number(raw_sig[num_bytes:])

    return encode_dss_signature(r, s)
```
inside utils.py. Good JWTs end up having a length of 132 and pass that math check. The bad ones end up being 130 and failing it. It is absolutely baffling to me what's going on.
