### ISSUE TITLE
Can't use encrypted private key to encode token with RS256

### ISSUE THREAD

**Issue by qwez** [jpadilla/pyjwt#342]
I have an encrypted private key and try to encode token with RS256:
`encoded = jwt.encode({'some': 'payload'}, private_key, algorithm='RS256')`
And got:
`TypeError: Password was not given but private key is encrypted`

Please add argument `password` to `encode()` method

**Comment by jpadilla** [comment]
https://github.com/jpadilla/pyjwt/issues/320#issuecomment-353236716
