### ISSUE TITLE
What do you mean by this?

### ISSUE THREAD

**Issue by cppg** [jpadilla/pyjwt#343]
path： jwt/api_jws.py  
 line:+98 ==》segments.append(base64url_encode(payload))
If you do this, what's the point of encryption? The data was completely exposed

**Comment by vimalloc** [comment]
This is simply not how JWT works. it does encrypt the data, it only verifies that the data in a token has not been tampered with (see https://jwt.io/introduction/). If you want to encrypt the data in a token you should use JWE instead.

**Comment by cppg** [comment]
thanks

**Comment by jpadilla** [comment]
@vimalloc thank you
