### ISSUE TITLE
How to extend the effective duration of the token

### ISSUE THREAD

**Issue by 52lemon** [jpadilla/pyjwt#349]
How to extend the effective duration of the token? can you give me an example!!! thanks

**Comment by mark-adams** [comment]
Hi @52lemon,
If you'd like to generate a token with a longer expiration, simply set the `exp` claim in your token.
For instance:
```
import jwt
import datetime
jwt.encode({'exp': datetime.datetime.now() + datetime.timedelta(days=1)}, key='somesecret')
```
