### ISSUE TITLE
1.6.1 --> 1.6.3 introduced breaking API changes: .decode(token=) vs .decode(jwt=)

### ISSUE THREAD

**Issue by dlopuch** [jpadilla/pyjwt#351]
PR #344 renamed some arguments on `api_jwt` ([for example](https://github.com/jpadilla/pyjwt/pull/344/files#diff-00ea5fc2260636f8d87435daf8c3b4c7R69)).  This is a breaking API change -- although the argument normalization is appreciated and an improvement, this should have triggered a major version bump (eg 1.6.1 --> 2.0.0) or there should have been a deprecation warning when using the old arg.

## Expected Result

[Semver](https://semver.org/) states:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

My dependency manager matches pyjwt on 1.6.*, so I expected a patch version bump to be not breaking.

Given the [wide usage](https://libraries.io/pypi/PyJWT/usage) of PyJWT, API should be stable across patch releases.

## Actual Result

My dependency manager pulled in 1.6.3, and suddenly my build broke.

**Comment by mark-adams** [comment]
I agree. I'll submit a pull request to revert that change.
