### ISSUE TITLE
Problem upgrading package

### ISSUE THREAD

**Issue by SrChip15** [jpadilla/pyjwt#354]
Summary
===
Tried updating package with the following command:
`pip3 install pyjwt -U`

I am using Python 3.6.5

Below is the dir level permissions info:
`rw-r--r--    admin    1 KiB  Tue Dec  5 15:00:12 2017   DESCRIPTION.rst `

Also ran with sudo, like so:
`sudo pip3 install pyjwt -U`

which yielded,
`The directory '/Users/<user>/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`

So, I checked the permissions for the above-mentioned dir too, I seem to have all permissions (rwx) and the dir is owned by me.

## Expected Result
Successfully installed PyJWT-1.6.4

## Actual Result
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/PyJWT-1.5.3.dist-info/DESCRIPTION.rst'

**Comment by jpadilla** [comment]
Feel free to open again if this is still an issue...

**Comment by SrChip15** [comment]
Can I take it that it's been fixed?!

**Comment by jpadilla** [comment]
Not particularly. I have not reproduced this issue or seen any other reports.
