### ISSUE TITLE
EC Signature allows to use ssh pub key format but HMAC doesn't check invalid secret key.

### ISSUE THREAD

**Issue by bongtrop** [jpadilla/pyjwt#362]
The ECDSA algorithm allows to use ssh public key format `ecdsa-sha2` but HMAC doesn't check invalid secret key. If users use ECDSA algorithm and they don't identify algorithm on decode, the attacker can tamper algorithm to HS. Then the server will use ECDSA public key with HMAC secret key.

**Comment by jtemporal** [comment]
I'm closing this one since it has been more than 3 months without a response from the issue author.

Please feel free to submit another issue following the issue template if the problem persists.
