### ISSUE TITLE
Will pyjwt support "sub: The subject of the token"?

### ISSUE THREAD

**Issue by xsank** [jpadilla/pyjwt#369]
The full claim attributes as follows:

iss: The issuer of the token

`sub`: The subject of the token

aud: The audience of the token

qsh: query string hash

exp: Token expiration time defined in Unix time

nbf: “Not before” time that identifies the time before which the JWT must not be accepted for processing

iat: “Issued at” time, in Unix time, at which the token was issued

jti: JWT ID claim provides a unique identifier for the JWT

**Comment by jonobrien** [comment]
#339 related
