### ISSUE TITLE
inconsistent results in Python2 - Python3

### ISSUE THREAD

**Issue by macmichael01** [jpadilla/pyjwt#371]
When I run the following command below. I receive inconsistent results.

## Expected Result

The same token should be returned. There is one noticeable difference in the second token which is the b (byte) prefixed to the string.

## Actual Result

two different strings

## Reproduction Steps

```
# Python 2.7.15
# Name: PyJWT
# Version: 1.6.4

>>> import jwt
>>> jwt.encode({'transaction': '6fa459ea-ee8a-4ca4-894e-db77e160355e', 'exp': 1497965640}, 'a') 
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmFuc2FjdGlvbiI6IjZmYTQ1OWVhLWVlOGEtNGNhNC04OTRlLWRiNzdlMTYwMzU1ZSIsImV4cCI6MTQ5Nzk2NTY0MH0.-bpx5A3DfSe3-HO6aH_glS8adcCxUn8lSK1-RPxohhI'

# Python 3.7.0
# Name: PyJWT
# Version: 1.6.4
>>> import jwt
>>> jwt.encode({'transaction': '6fa459ea-ee8a-4ca4-894e-db77e160355e', 'exp': 1497965640}, 'a')
b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0cmFuc2FjdGlvbiI6IjZmYTQ1OWVhLWVlOGEtNGNhNC04OTRlLWRiNzdlMTYwMzU1ZSIsImV4cCI6MTQ5Nzk2NTY0MH0.NuqwXlHt27nRxg5W2hHoP5ugnLmw-7QYBumO7lRa1i0'
```

## System Information

    $ python -m jwt.help

Tested on Mac OS
```
{
  "cryptography": {
    "version": "2.2.2"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.0"
  },
  "platform": {
    "release": "17.7.0",
    "system": "Darwin"
  },
  "pyjwt": {
    "version": "1.6.4"
  }
}
```
Tested on Ubuntu 16.04
``` 
{
  "cryptography": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.2"
  },
  "platform": {
    "release": "4.15.13-x86_64-node584",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "1.6.4"
  }
}
```

This command is only available on PyJWT v1.6.3 and greater. Otherwise,
please provide some basic information about your system.

**Comment by mark-adams** [comment]
The reason you see different tokens is that Python's `dict` datatype (used for storing JWT claims) does not guarantee ordering of the keys. As a result, changes to the internal `dict` implementation between Python versions can cause two dict literals to have keys that are ordered differently even though the dicts are equivalent to one another.

**Comment by macmichael01** [comment]
You are referring to an internal dict in the pyjwt library or the dict that I passed? 

When testing between versions, this becomes an issue.

What about using OrderedDict?

**Comment by macmichael01** [comment]
Oh ok I see what was happening now. The solution is to first assign the dict to a variable. Explicitly passing a dictionary in the way that I did will not guarantee order between python versions (which I still find a bit odd but I am sure there is a reason internally or this). It's best to assign a dict to a variable and pass that variable along. 

```# Do this:
data = {'transaction': '6fa459ea-ee8a-4ca4-894e-db77e160355e', 'exp': 1497965640}
jwt.encode(data, 'a')
# Instead of:
jwt.encode({'transaction': '6fa459ea-ee8a-4ca4-894e-db77e160355e', 'exp': 1497965640}, 'a')
```

This will only ever be an issue if you need to support python2 and python3 and need to verify the returned string. If that doesn't matter, strings all decode in the same way they always have but potentially might not match if its a dict you are passing.

Thanks @mark-adams for explaining this.

**Comment by jadhavmanoj** [comment]
Hello @macmichael01,

I am using flask and pyjwt python2.x version. Now I am upgrading python 2.x to python3.x. Should I go with pyjwt or use flask jwt?

**Comment by vimalloc** [comment]
You should not use Flask-jwt, it has been abandoned for years. Flask-jwt-extended or flask-jwt-simple are both actively maintained flask extensions, and use PyJWT behind the scenes. There is also nothing wrong with using PyJWT directly in your flask application if you want to go that route.

**Comment by macmichael01** [comment]
@jadhavmanoj I don't think this will be a common bug that most developers will run into. 

I would recommend identifying in your code where PyJWT is being called and run some tests on those specific parts of code both in py2 and py3 and verify that you are receiving expected results. 

If you have already developed an app using Flask + PyJWT, I wouldn't recommend converting to another 3rd party library which wraps PyJWT unless there is a valued added for doing so. Perhaps the value added for the above libraries recommended would help to mitigate the issues that I ran into but then again maybe it wouldn't. If it doesn't, converting might cost you more time than it's worth. The decision is up to you to decide.

**Comment by justmobilize** [comment]
The other thing to note is that your data is the same:

`eyJ0cmFuc2FjdGlvbiI6IjZmYTQ1OWVhLWVlOGEtNGNhNC04OTRlLWRiNzdlMTYwMzU1ZSIsImV4cCI6MTQ5Nzk2NTY0MH0`

It's the first part, which is the header.
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9` >> `b'{"alg":"HS256","typ":"JWT"}'`
or
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9` >> `b'{"typ":"JWT","alg":"HS256"}'`
