### ISSUE TITLE
The old token will not fail, when I generate a new token.

### ISSUE THREAD

**Issue by MonkeyInWind** [jpadilla/pyjwt#373]
I generate a token named 'a' and expire for one day, then I generate a token named 'b',use the same object, the difference is 'iat' and 'exp'.
Now the two token are effective.
But I only need one token to work.
Can you add a API that makes token invalid or invalidation of old ones when new token is generated?
thanks!

**Comment by vimalloc** [comment]
Nope, that’s fundamentaly not how JWTs work. 

If you want to not allow the old token when creating a new token, you will need to create a blacklist on your backend where you mark the old token as revoked, then manually check that blacklist every time a request comes in to see if the token is revoked or not.

**Comment by MonkeyInWind** [comment]
Ok, thanks.

发自我的 iPhone

在 2018年9月18日，21:51，Landon <notifications@github.com<mailto:notifications@github.com>> 写道：


Nope, that’s fundamentaly not how JWTs work.

If you want to not allow the old token when creating a new token, you will need to create a blacklist on your backend where you mark the old token as revoked, then manually check that blacklist every time a request comes in to see if the token is revoked or not.
