### ISSUE TITLE
AttributeError: module 'jwt' has no attribute 'encode'

### ISSUE THREAD

**Issue by asajuenitan** [jpadilla/pyjwt#374]
Using 
`import jwt`

`encoded = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')`
**Traceback (most recent call last):
    File "< stdin >", line 1, in <module>
AttribureError: module 'jwt' has no attribure 'encode'**

Same issue with using `decode`

**Comment by vimalloc** [comment]
Do you have a file called jwt.py in the same directory where you are trying to run the code?

**Comment by southwolf** [comment]
You might have installed another package [jwt](https://github.com/GehirnInc/python-jwt)

Did you run `pip install jwt`? @heroh9

**Comment by venkat-pixelbrook** [comment]
use "pip install pyjwt"

**Comment by lfshammu** [comment]
Had a similar issue. Accidentally installed jwt first. Just removing jwt and installing PyJWT did not help.
Recreating my virtual environment and installing PyJWT fixed the issue.

**Comment by godspeedcurry** [comment]
uninstall all of them then "pip install pyjwt"

**Comment by martinoywa** [comment]
Uninstalling "jwt" then installing "pyjwt" worked for me.

**Comment by sandbbk** [comment]
I have this problem on win10, but on debian9.9 code works correctly. In my `requirements.txt` present both `jwt` and `pyjwt` and it works on linux. When i had relocated my code from linux on windows, it didn't worked before i uninstalled `jwt`. Thanks for resolving!

**Comment by huakaidaojia** [comment]
@lfshammu 我与你的情况一样，安装你的方法，一块完美解决，感谢

**Comment by Reclu3e** [comment]
If your python file name is jwt.py, you may have this problem.

**Comment by parin13** [comment]
`pip3 install pyjwt==1.5.3`

did the magic

**Comment by Royzzz21** [comment]
thanks it works

**Comment by Royzzz21** [comment]
> `pip3 install pyjwt==1.5.3`
> 
> did the magic

thanks

**Comment by vungsung** [comment]
> Had a similar issue. Accidentally installed jwt first. Just removing jwt and installing PyJWT did not help.
> Recreating my virtual environment and installing PyJWT fixed the issue.

For anyone installed `jwt` directly and the Python environment cannot be easily reset:
Try this:
```bash
pip uninstall jwt
rm [Python Home Directory]/Lib/site-packages/jwt
pip uninstall pyjwt
pip install pyjwt
```

The problem is at the `site-packages/jwt` folder.
After runs `pip uninstall jwt`, the folder still exists. You have to remove it manually.
And then, the `PyJWT` folder is still stuck in `site-packages`.
You have to reinstall it in order to move it to the default `jwt` folder.

**Comment by DestyNova** [comment]
I had the same problem (but with 'decode'). The fix was as @vungsung said, but you can fix PyJWT in one step with:
```
pip install --force PyJWT
```

**Comment by PropeReferio** [comment]
Can someone explain how Python is able to import jwt after you install pyjwt? Thanks.

**Comment by tonsV2** [comment]
I had named my script "token.py" and that caused this error

**Comment by lugodev** [comment]
> `pip3 install pyjwt==1.5.3`
> 
> did the magic

This solved my issue. Thanks!

**Comment by pcty-kk** [comment]
> `pip3 install pyjwt==1.5.3`
> 
> did the magic

it works!!

**Comment by 0ccupi3R** [comment]
> > `pip3 install pyjwt==1.5.3`
> > did the magic
> 
> it works!!

it worked for me too, only by keeping `pip3 install pyjwt==1.5.3` package.

**Comment by BainesySP** [comment]
Hi all. I'm having this issue too. I've tried all the suggestions recommended so far and none have worked. What's even more confusing is that after uninstalling pyjwt and jwt, when I search for the jwt dir to remove it using 'locate' my terminal outputs the path but when I attempt to remove it I'm told the directory doesn't exist. I've updated my system using 'apt update' but doesn't seem to make any difference either. I'm on Python 3.9.2.

**Comment by varunlohade** [comment]
pip3 install pyjwt==1.5.3 
worked for me.

**Comment by Muhammadali-Akbarov** [comment]
I used all methods in comments but all does not work?

```
File "/home/muhammadali/mytaxi/jwt-custom-user/myapp/models.py", line 77, in _generate_jwt_token
    token = jwt.encode({
AttributeError: module 'jwt' has no attribute 'encode'
```

**Comment by DestyNova** [comment]
> I used all methods in comments but all does not work?
> 
> ```
> File "/home/muhammadali/mytaxi/jwt-custom-user/myapp/models.py", line 77, in _generate_jwt_token
>     token = jwt.encode({
> AttributeError: module 'jwt' has no attribute 'encode'
> ```

So you tried `pip install --force PyJWT` and it didn't work? You may have to uninstall whatever package is currently providing the `jwt` module.

Alternatively you can use `virtualenv` to get a fresh virtual environment, then install PyJWT there.

**Comment by Muhammadali-Akbarov** [comment]
DestyNova  thanks I'll try

**Comment by svetlanama** [comment]
> > `pip3 install pyjwt==1.5.3`
> > did the magic

I works, thanks.
because of incopatibility `djangorestframework-jwt 1.11.0 requires PyJWT<2.0.0,>=1.5.2, but you have pyjwt 2.3.0 which is incompatible`

**Comment by s2t2** [comment]
GitHub Actions "Python Application" is throwing this error.

**Comment by sonnguyenHT** [comment]
It's work with me when I remove all jwt, pyjwt packet and install only pyjwt

**Comment by DerekNoguera** [comment]
> I had the same problem (but with 'decode'). The fix was as @vungsung said, but you can fix PyJWT in one step with:
> 
> ```
> pip install --force PyJWT
> ```

Thank you very much, this helped me a lot
