### ISSUE TITLE
python 2.6 support for v1.5.3 not working on fedora

### ISSUE THREAD

**Issue by infohack1** [jpadilla/pyjwt#377]
As per pypi link https://pypi.org/project/PyJWT/1.5.3/ , python 2.6 is supported for version 1.5.3, but
rpm at https://fedora.pkgs.org/26/fedora-updates-x86_64/python2-jwt-1.5.3-1.fc26.noarch.rpm.html
shows python2-jwt-1.5.3 requires Python(abi) = 2.7 .

Can you please guide me on how to install and use pyjwt for python 2.6 on fedora.

**Comment by carlwgeorge** [comment]
Fedora 26 has Python 2.7, not 2.6.  The python2-jwt package is built against the system version of Python 2, hence the requirement you observed.  If you somehow managed to downgrade Fedora 26's Python to 2.6, you're going to see lots of problems like this.

Fedora 26 is end of life.  If you need to run on Python 2.6, I suggested switching to RHEL/CentOS 6, which still uses 2.6 and is [supported until 2020-11-30](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates).

Regardless, this isn't an upstream issue, this should be closed by the maintainers.  If you need help with the Fedora/RHEL/CentOS ecosystem and Python come by `#fedora-python`, `#centos`, or `#rhel` on Freenode.

**Comment by jdufresne** [comment]
Both Fedora 26 and Python 2.6 are end of life. Further, this project no longer supports Python 2.

I think this issue should be closed.
