### ISSUE TITLE
DeprecationWarning ... but algorithms are defined.

### ISSUE THREAD

**Issue by ahopkins** [jpadilla/pyjwt#383]
I am receiving a `DeprecationWarning` on my tests for [`sanic-jwt`](https://github.com/ahopkins/sanic-jwt/) even though `algorithms` is explicitly set.

## Expected Result

Tests to run without `DeprecationWarning`

## Actual Result

```
DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
```

## Reproduction Steps

The code is essentially this:

```python
import jwt

token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NDE2ODAzOTZ9._7O4mvy_uytWuxC-vZHqZ8i0oVpr63Jb6PYd0-njdNw"
secret = "This is a big secret. Shhhhh"
algorithm = "HS256"
verify = True

decoded = jwt.decode(
    token,
    secret,
    algorithms=[algorithm],
    verify=verify,
)
```

Running just this is fine.

[See the actual code here](https://github.com/ahopkins/sanic-jwt/blob/dev/sanic_jwt/authentication.py#L168)

But, when I run my tests:

```
tox
```

I receive:

```
  /home/adam/Projects/sanic-jwt/.tox/py37/lib/python3.7/site-packages/jwt/api_jwt.py:82: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning
  /home/adam/Projects/sanic-jwt/.tox/py37/lib/python3.7/site-packages/jwt/api_jws.py:146: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
    DeprecationWarning
```

## System Information

My `tox` tests run on python 3.5, 3.6, and 3.7. My local machine is running Ubuntu 18.04, but I see this also on other flavors of Linux machines and in Travis.

**Comment by vimalloc** [comment]
You have places in your unit tests where you are calling decode directly without specifying algorithms: 
https://github.com/ahopkins/sanic-jwt/blob/9dd5d1a016281c76e53311b5d3f29b18f244a9aa/tests/test_claims.py#L16

**Comment by ahopkins** [comment]
🤦‍♂️🥴🙄😶

Thanks. me == embarrassed.
