### ISSUE TITLE
PyJWT in AWS Lambda

### ISSUE THREAD

**Issue by AntonOellerer** [jpadilla/pyjwt#386]
I want to use PyJWT in an aws lambda function. 
This fails without any helpful error messages from aws.

I created a serverless project (` sls create ---template aws-python3`), a script importing the library, freezing the requirements to a `requirements.txt` file and then deploying it.

## Expected Result
I expect nothing out of the ordinary here, since local invocation of the `handler` function run without a problem.

## Actual Result

What happened instead.

When I deploy the function and invoke it with `sls invoke -f main`, I get the error "Syntax error in module 'handler".
I was able to pinpoint the problem to the `jwt` import.

## Reproduction Steps

```python
import jwt

def hello(event, context):
    return "hello"
```

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.1"
  },
  "platform": {
    "release": "4.19.8-300.fc29.x86_64",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "1.7.1"
  }
}

```

**Comment by jpadilla** [comment]
@AntonOellerer how exactly are you packaging your deployment? I wonder if you might need need to use https://github.com/UnitedIncome/serverless-python-requirements

A full stack trace might also be useful.

**Comment by AntonOellerer** [comment]
I'm just doing it with `sls deploy` rn.
I will take a look at sls python requirements, thank you!
How do I get a full stacktrace?

**Comment by AntonOellerer** [comment]
thank you, with serverless-python-requirements it worked for `sls invoke -f main`
Sadly I can't test via http requests now due to upload limitations.
