### ISSUE TITLE
The old expired token is passed and didn't throw ExpiredSignatureError 

### ISSUE THREAD

**Issue by ziaul-haque** [jpadilla/pyjwt#387]
Summary
1. Created email signup link with ttl_sec = 5
2. After 5 secs of expired token, jwt decode the token as passed not throwing expired signature error.
3. jwt 1.4.2
Payload: {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYXV0aDB8NWMyMzY1Zjg3ZTg1ZGUzMWI5ZjNjYzliIiwiZW1haWwiOiJkZW1vX3VzZXJfMTBAeW9wbWFpbC5jb20ifQ.1z9g9PUA304SOnXozI3vPKvtUoD-Z4oLWGaRNkGT0s8","password":"*******"}

## Expected Result
Expired token should through ExpiredSignature error.

## Actual Result
JWT token doesn't through any exception.

## Reproduction Steps

```python
import jwt

        try:
            decoded_token = jwt.decode(token, private_secret_key)
        except jwt.ExpiredSignatureError:
            raise TokenExpireError("This token is expired.")
        except jwt.InvalidTokenError:
            raise TokenInvalidError("This token is invalid.")
        except Exception as e:
            raise TokenDecodeError("Error in token decode : " + str(e))

```

## System Information

    $ python -m jwt.help

```
<paste here>
```

This command is only available on PyJWT v1.6.3 and greater. Otherwise,
please provide some basic information about your system.

**Comment by vimalloc** [comment]
`ttl_sec` is not a registered claim name that is automatically validated. The claim you are looking for is `exp`.

**Comment by jpadilla** [comment]
@ziaul-haque what @vimalloc comments is correct. Furthermore, your sample token's payload does'nt event contain `exp` nor `ttl_sec`.
