### ISSUE TITLE
Toggle validation of specific claims

### ISSUE THREAD

**Issue by qilyn** [jpadilla/pyjwt#389]
We currently use this library (and JWTs) to retrieve some information from an outside system, which is independent of us. The trouble is that that system doesn't generate a unique token each time one is requested--it caches them, so occasionally a token's `audience` claim will belong to a different project. 

It's great to be able to provide a list of possible values this field could contain (thanks #205!), but having to maintain a list of them would introduce a point of failure if, say, the issuer suddenly added a new project and forgot to notify us or update the documentation. They do sign their tokens. 

The best-case solution for us would be to be able to accept all values of the `audience` claim. If this sounds reasonable, I'd be happy to work on it!

Edit: forgot to say: thank-you! This is a real nice package to use, it's been a huge help :smile:

**Comment by jpadilla** [comment]
You can actually do this already. Although we should do a better job at documenting it(help wanted 😃)

```python
jwt.decode(token, 'secret', options={'verify_aud': False})
```

**Comment by qilyn** [comment]
Oops! Thanks so much, that would do it! (Maybe I'll help with that instead :joy:)
