### ISSUE TITLE
RFE: Support for multiple signatures

### ISSUE THREAD

**Issue by lbragstad** [jpadilla/pyjwt#390]
The [JWS RFC section 7](https://tools.ietf.org/html/rfc7515#section-7) details optional support for multiple signatures, depending on the serialization approach.

I'm checking to see if it would be feasible to support passing multiple private keys into ``encode()`` as a way to generate multiple signatures for a JWS. A benefit of using multiple signatures is that it would allow for a graceful transition from one private key to another.

**Comment by randomstuff** [comment]
Multiple signatures is only possible with JWS JSON serialization (i.e. [not the Compact one](https://tools.ietf.org/html/rfc7515#section-7.1)):

> Only one signature/MAC is supported by the JWS Compact Serialization

JWT on the other hand is [restricted to the Compact serialization](https://tools.ietf.org/html/rfc7519#section-1):

> JWTs are always represented using the JWS Compact Serialization or the
> JWE Compact Serialization.

Thus, it is not possible to use multiple signatures with JWT. It probably does not make much sense to add support for multiple signatures in a JWT implementation.
