### ISSUE TITLE
jwt.encode generating bytes instead of a string

### ISSUE THREAD

**Issue by shughes-uk** [jpadilla/pyjwt#391]
The documentation example seems to indicate the result of jwt.encode is a string. The actual result with Python 3.7.1 is bytes. If this is just a documentation issue i'm happy to submit a small PR.
## Expected Result

```
>>> import jwt
>>> encoded = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb21lIjoicGF5bG9hZCJ9.4twFt5NiznN84AWoo1d7KO1T_yoc0Z6XOpOVswacPZg'

>>> jwt.decode(encoded, 'secret', algorithms=['HS256'])
{'some': 'payload'}
```

## Actual Result

```
Python 3.7.1 (default, Dec 14 2018, 13:28:58)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import jwt

In [2]: encoded = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')

In [3]: encoded
Out[3]: b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzb21lIjoicGF5bG9hZCJ9.Joh1R2dYzkRvDkqv3sygm5YyK8Gi4ShZqbhK2gxcs2U'
```

## System Information

```
{
  "cryptography": {
    "version": "2.4.2"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.1"
  },
  "platform": {
    "release": "18.2.0",
    "system": "Darwin"
  },
  "pyjwt": {
    "version": "1.7.1"
  }
}
```

**Comment by brandonmbanks** [comment]
Also having the same issue. Any news on this?

@shughes-uk It is possible to decode the byte string by appending `.decode('utf-8')`. It will keep the same string and signature.

**Comment by shughes-uk** [comment]
Oh I know, it's just a docs fix I think

**Comment by Samarpitr** [comment]
Same issue!

**Comment by Samarpitr** [comment]
Thanks @brandonmbanks `.decode('utf-8')` is working!

**Comment by richey-v** [comment]
Personally, I think this is a Python3 compatibility issue and that `encode()` should return the Python string type for both Python2 and Python3.

On my machine:
```
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jwt
>>> type(jwt.encode({'some': 'payload'}, 'secret'))
<type 'str'>
```
but
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jwt
>>> type(jwt.encode({'some': 'payload'}, 'secret'))
<class 'bytes'>
```

**Comment by prsolucoes** [comment]
I have the same problem -,-

**Comment by fgimian** [comment]
Came across this too, really would be nice to have the returned result be a string to avoid an unnecessary encode / decode cycle.

**Comment by jpadilla** [comment]
I'm all for improving this if anyone want's to work on it, it would most likely be considered a breaking change so it would require a major version bump. Now that Python 2 is reaching it's EOL, it might be a good time to do so.

**Comment by atleta** [comment]
I've looked into the code and it's a rather trivial change - if we just add the (ascii) decoding step to PyJWS.encode. If you really want to spare the decoding, that's a lot more work as the base64 module (and the binascii module it uses) works with bytearrays. (Which makes sense for the input, since you should be able to b64 encode binary data. As for why it returns a bytearray, that might be some optimization technique, but that's happaning in native code and I didn't look into that.)

**Comment by stefann01** [comment]
Same issue! Could not jsonify a token if it's a bite object.
![image](https://user-images.githubusercontent.com/30937067/73122852-1a76f480-3f92-11ea-874a-18eb862a2df7.png)

**Comment by vinhphat89** [comment]
> encoded_jwt.decode('UTF-8')
```
jwt_secret = 'xxxx'
jwt_payload = {'sub': self.sender_id,'iat': datetime.datetime.utcnow(),'exp': datetime.datetime.utcnow() + datetime.timedelta(seconds=6),'iss': 'chatbot','usr': self.sender_user}
jwt_encoded = jwt.encode(jwt_payload, jwt_secret, algorithm='HS256')
encoded_jwt = jwt_encoded.decode('UTF-8')
```
It also solved my problem too.

**Comment by jdufresne** [comment]
I believe this has been fixed and this can be closed.

Since e3a1ba52b5926bd419a5bab73c64d7bce1089958, mypy now checks the return type.
