### ISSUE TITLE
RFC7797 - Unencoded Payload Option

### ISSUE THREAD

**Issue by livespotty** [jpadilla/pyjwt#397]
Suggest an idea for this project.

https://tools.ietf.org/html/rfc7797. Support for JSON Web Signature (JWS) Unencoded Payload Option

**Comment by randomstuff** [comment]
The name of this library is `PyJWT` and Unencoded Payload Option is [explicitely excluded for being used in JWT](https://tools.ietf.org/html/rfc7797):

> This specification updates RFC 7519 by stating that JSON Web Tokens
   (JWTs) MUST NOT use the unencoded payload option defined by this
   specification.

Is non-JWT JWE and JWS in scope of this library?

**Comment by fviard** [comment]
The support for RFC7797 was added with the following commit:
https://github.com/jpadilla/pyjwt/commit/1e7915613f4962d793b97a0db7bbe1661a59fa5a
I think that you can now close this ticket as "resolved" :-)
