### ISSUE TITLE
{"hash":"md4","alg":"HS256","typ":"JWT"}

### ISSUE THREAD

**Issue by Mr-artist** [jpadilla/pyjwt#404]
token = 'eyJoYXNoIjoibWQ0IiwiYWxnIjoiSFMyNTYiLCJ0eXAiOiJKV1QifQ.eyJzaWQiOiIzNTI3MzRkMTM4ZTU0MTczYzFjNzhiYThkZTM5ZmYyYiIsImV4cGlyZSI6MTU1MjQ2NDU2NX0.Le4K9oJaP3rMMW6kVjKhyPgJ1JxWKDW5M9nMnBeWUqI' 

'hash' in header dict, Is it the same way?,Must I get secret value?

**Comment by jpadilla** [comment]
I'm not sure what you're asking. Closing for now, feel free to give an update.
