### ISSUE TITLE
Encode via command line cannot set headers

### ISSUE THREAD

**Issue by Botono** [jpadilla/pyjwt#406]
There is no way to set headers on a token when encoding via the command line.

## Expected Result

Command line arguments should accept some kind of headers input and pass it to `encode()`.

## Actual Result

Headers cannot be set.

## Reproduction Steps

```
pyjwt --key=secret --alg='RS256' encode iss=issuer aud=audience sub=subject exp=123456789 headers=foo
```
`headers` value will appear in the payload.

You can see that no header value is passed to `encode()` here: https://github.com/jpadilla/pyjwt/blob/6845515ed8490045aa175580304bf8ebeec805ff/jwt/__main__.py#L46-L50

But `encode()` supports header information: https://github.com/jpadilla/pyjwt/blob/6845515ed8490045aa175580304bf8ebeec805ff/jwt/api_jwt.py#L45

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": "2.6.1"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.0"
  },
  "platform": {
    "release": "17.7.0",
    "system": "Darwin"
  },
  "pyjwt": {
    "version": "1.7.1"
  }
}
```

**Comment by jpadilla** [comment]
@Botono wanna put together a pull request?

**Comment by justinbaur** [comment]
I'd like to help out with this.

**Comment by jpadilla** [comment]
@justinbaur that'd be awesome, thanks!

**Comment by benclark0** [comment]
Is there any chance you'd consider making a new version with this change?  It'd make my life considerably easier.
