### ISSUE TITLE
jwt.encode throws exception due to datetime not serializable

### ISSUE THREAD

**Issue by khteh** [jpadilla/pyjwt#407]
I have datetime data in the payload to be jwt-encoded and it throws non-json-serializable exception. Any advice and insight is appreciated.

**Comment by jpadilla** [comment]
@khteh instances of `datetime.datetime` aren't serializable by default with Python's `json.dumps()` You could pass in a custom `json_encoder` to `jwt.encode()`. 

https://github.com/jpadilla/pyjwt/blob/ed28e495f937f50165a252fd5696a82942cd83a7/jwt/api_jwt.py#L40-L66

**Comment by mahee96** [comment]
Latest Documentation still says that datetime.datetime results are applicable for 'exp' field.

![image](https://user-images.githubusercontent.com/47920326/235376436-fdbe47bc-8dbd-4c76-8e07-b682ed821ba7.png)

but the implementation throws error.
![image](https://user-images.githubusercontent.com/47920326/235376493-4c673095-a16e-4db4-9bc5-da24ac182705.png)

@jpadilla please take a look and see if either doc or the implementation can be updated to be in sync.

the decoder throws error for `exp` field, when using string value of datetime.datetime.utcnow() while encoding.
