### ISSUE TITLE
Why not read when not a TTY?

### ISSUE THREAD

**Issue by jaraco** [jpadilla/pyjwt#410]
I was looking to experiment with PyJWT's command-line interface, and I thought a thing to try would be to encode a token and then decode it immediately, so I did this:

```
~ $ pyjwt --key='foo' encode user_id=123456 name="jaraco dev" admin=true | pyjwt decode                                                                                        
There was an unforseen error:  Cannot read from stdin: terminal not a TTY
usage: 
...
```

But as you can see, that generated an error. Is there a reason to reject the stdin if it's not a TTY?

**Comment by jpadilla** [comment]
@jaraco want to put together a PR for this?

**Comment by jaraco** [comment]
I've started working on a PR, but I've encountered another issue (#412).
