### ISSUE TITLE
Decoding a string JWT

### ISSUE THREAD

**Issue by HadeelElbitar** [jpadilla/pyjwt#420]
Can I use this library to decode a JWT that wasn't generated using that library? The JWT is in string format. It seems like I can't (or at least I haven't been able to do so, so far..) so I would like to get a confirmation.

Thanks!

**Comment by jpadilla** [comment]
> Can I use this library to decode a JWT that wasn't generated using that library? 

Yes.

> It seems like I can't (or at least I haven't been able to do so, so far..)

Any particular error?

Closing this for now as a usage question / issue. Feel free to reply if you're still having problems.

**Comment by HadeelElbitar** [comment]
> > Can I use this library to decode a JWT that wasn't generated using that library?
> 
> Yes.
> 
> > It seems like I can't (or at least I haven't been able to do so, so far..)
> 
> Any particular error?
> 
> Closing this for now as a usage question / issue. Feel free to reply if you're still having problems.

Yes I get an error saying the jwt has to of type bytes `"Invalid token type. Token must be a <class \'bytes\'>"`

**Comment by HadeelElbitar** [comment]
@jpadilla
