### ISSUE TITLE
-bash: lspyjwt: command not found

### ISSUE THREAD

**Issue by kevinmustaqim** [jpadilla/pyjwt#422]
I have installed and it doesn't seem to work. The detail error as below:

-bash: lspyjwt: command not found

My OS: Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 (2018-01-08) x86_64 GNU/Linux

**Comment by jpadilla** [comment]
@kelvintaywl did you try `pyjwt` instead of `lspyjwt`?
