### ISSUE TITLE
ES256 Verification Failing

### ISSUE THREAD

**Issue by azizabah** [jpadilla/pyjwt#428]
It appears that PyJwt is failing to validate *some* JWTs that are encoded using ES256 through a separate API Gateway (written in Java, not Python). The issue appears to occur when the signature portion of the JWT is created at 174 characters instead of 176 and is padded with two "=" by PyJwt before validation. The Java services we have using these JWTs do not have issues with the 174 character or the 176 character signature portions.

## Expected Result

I expected either all keys to validate or all keys to fail.

## Actual Result

Most keys validate. Validation fails in the scenario described above.

## Reproduction Steps

```python
import jwt
key = """-----BEGIN PUBLIC KEY-----
MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBIHbvEjK0a4sg604hauxj5vQcPUxR
x7yNLdcTSRo4ULcPALsFkU6zaiEW7SEwOvdfocenplOIvSq6xzrDA3gN8gABD5tQ
9Ih7u3uzB0JvmMhm0SMVM8SJioyatxSZSzW0lhfcWfLei4egB54QaUZZ7iETGHlS
f7jYHT6s1I9WChAhVnA=
-----END PUBLIC KEY-----"""
# good jwt
payload = 'eyJhbGciOiJFUzI1NiJ9.eyJpYXQiOjE1NjExMjY5NzMsImV4cCI6MTU2MTEyODE3MywiYXVkIjoidGVzdCIsImp0aSI6ImIxOWJjM2VkLWQ5N2YtNDI5ZC1iODBlLWJkN2Q2Yjc1OWUyMSIsImlzcyI6Ind3dy50ZXN0LmNvbSIsIm5iZiI6MTU2MTEyNjk3Mywic3ViIjoiam9obi5kb2VAdGVzdC5jb20iLCJyb2xlcyI6WyJST0xFX0FQUF9BRE1JTiIsIlJPTEVfQVBQX0NMSUVOVDFfRU5WX1VTRVIiXX0.ATJyX7yqVi_J2U5MqATaO7PSmdHiEfIdkYD0hUR5TNQgYVvud4-h2YvkULvdUD01YMCk-ktw28lqnVr2apb37qprAOv_HDH_tzybI3IgdUNBxaymiYljRUxrhvYLUd9KTxM98GGLC5bu0mcXbWYIDmBItLJ58YrFPJ2bT6W_NR4gEKF7'
jwt.decode(payload, key, algorithms=['ES256'])
# jwt.exceptions.ExpiredSignatureError: Signature has expired. This is expected. 

# failing jwt
payload = 'eyJhbGciOiJFUzI1NiJ9.eyJpYXQiOjE1NjExMzU4NjksImV4cCI6MTU2MTEzNzA2OSwiYXVkIjoidGVzdCIsImp0aSI6IjgwNDE4NjgyLTM4MzEtNDkwZi05YmExLTlmODcxNzc3YTlmMiIsImlzcyI6Ind3dy50ZXN0LmNvbSIsIm5iZiI6MTU2MTEzNTg2OSwic3ViIjoiam9obi5kb2VAdGVzdC5jb20iLCJyb2xlcyI6WyJST0xFX0FQUF9BRE1JTiIsIlJPTEVfQVBQX0NMSUVOVDFfRU5WX1VTRVIiXX0.HWgwVE98Wh4H629-m02z3cC1E5PlIWIAjjpAVh-BS1NPBZamKldtp4dIm5TEaG2_NjmxkEDk0wGrtwpLOyhfvYyzRpdkyM3qs3msTXY3FkleEn9L__Y4-Uraxm2RtehRI1fUjCK2vhPYGk2PTkQyWKnh0vFIl9fZusJPzYONBJuVYw'
jwt.decode(payload, key, algorithms=['ES256'])
# jwt.exceptions.InvalidSignatureError: Signature verification failed
```

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.0"
  },
  "platform": {
    "release": "16.7.0",
    "system": "Darwin"
  },
  "pyjwt": {
    "version": "1.7.1"
  }
}
```

This command is only available on PyJWT v1.6.3 and greater. Otherwise,
please provide some basic information about your system.

**Comment by tscrypter** [comment]
What is this particular [snippet](https://github.com/jpadilla/pyjwt/blob/3d47b0ea9e5d489f9c90ee6dde9e3d9d69244e3a/jwt/utils.py#L107) doing? `if len(raw_sig) != 2 * num_bytes:` seems to always be applied and fails, even though the signature is valid.

**Comment by tscrypter** [comment]
Similarly, maybe adding a comment behind this [line of code](https://github.com/jpadilla/pyjwt/blob/3d47b0ea9e5d489f9c90ee6dde9e3d9d69244e3a/jwt/utils.py#L105). What does adding 7 and floor dividing by 8 do?

**Comment by azizabah** [comment]
In utils.py, if we modify raw_to_der_signature like so:
```
if (len(raw_sig) == 130):
        num_bytes = 65
```
it works every time. This seems incredibly odd and feels like a bug somewhere else in the code.

**Comment by aaknitt** [comment]
Seems like this could be similar or same as described [here](https://github.com/zelloptt/zello-channel-api/issues/91#issuecomment-622576383).  Related to whether or not url-safe base64 encoding/decoding is used or not.  Perhaps a flag to direct PyJWT to use one or the other during encode and decode is a potential solution?

**Comment by P3nt3st3r123** [comment]
https://github.com/jpadilla/pyjwt/issues/311#issuecomment-798830656
