### ISSUE TITLE
 Encoding with RSA  says, Unable to parse an RSA_JWK from key: <cryptography.hazmat.backends.openssl.rsa._RSAPrivateKey object at 0x0000000007643390>

### ISSUE THREAD

**Issue by IrvinCrespo** [jpadilla/pyjwt#430]
i have been trying to encode jwt with private key by this way, but i have this error

> jose.exceptions.JWSError: Unable to parse an RSA_JWK from key: <cryptography.hazmat.backends.openssl.rsa._RSAPrivateKey object at 0x0000000007643390>

i think that is because i passed an object RSAPrivateKey. what is the correct way to do this.

        import os
        pwd = os.path.dirname(__file__)
        private_key = open(pwd + '/authkey').read().encode('ascii')

        priv_rsakey = load_pem_private_key(private_key, password='smashedintopieces'.encode('utf-8'), backend=default_backend())
        #print(priv_rsakey.__dict__)
        token = jwt.encode({'id':'the_id'},priv_rsakey,algorithm='RS256')#.decode('utf-8')
        return token
`

**Comment by dimaqq** [comment]
After playing a bit with EC keys (not RSA, sorry), I've discovered that:
* PEM file content (as `str`) can be passed directly to `jwt.encode` as key argument
* FWIW, I have `PyJWT==1.7.1 cryptography==2.8` installed and backend is openssl

**Comment by joshfriend** [comment]
I got a very similar error using the cryptography backend:

```
jose.exceptions.JWSError: Unable to parse an RSA_JWK from key: <jose.backends.cryptography_backend.CryptographyRSAKey object at 0x10c4de6a0>
```

```python
rsa_key = {
    "p": "...",
    "kty": "RSA",
    "q": "...",
    "d": "...",
    "e": "AQAB",
    "use": "sig",
    "kid": "test",
    "qi": "...",
    "dp": "...",
    "alg": "RS256",
    "dq": "...",
    "n": "..."
}
test_key = jwk.construct(rsa_key)
jws.sign({}, test_key, headers={'kid': 'test'}, algorithm=ALGORITHMS.RS256)
```

Note that i can call `test_key.sign()` just fine.
