### ISSUE TITLE
Allow multiple issuers?

### ISSUE THREAD

**Issue by qilyn** [jpadilla/pyjwt#433]
Does it seem reasonable to allow PyJWT to accept a list of possible `iss`uer arguments, in the same way that `aud` does?  (It's possible I'm just lazy and trying to avoid try-catch blocks :joy:)

**Comment by peterfarrell** [comment]
@jpadilla Could we get this PR merged and released?  It's blocking support for multiple IDPs:

https://github.com/snok/django-auth-adfs/pull/201
