### ISSUE TITLE
Add correct ssh-keygen command to docs

### ISSUE THREAD

**Issue by cal97g** [jpadilla/pyjwt#435]
It's actually quite difficult to find information on different key formats for Asymmetric keys. Add an example key format or at least a command to generate one correctly; eg:

`ssh-keygen -t rsa -b 4096 -m PEM`

**Comment by assman** [comment]
I agree, such a snippet should be added to the docs as guidance. Will help newbies to get started quickly.

**Comment by auvipy** [comment]
contributions are welcome
