### ISSUE TITLE
[Feature Request] Adding support for JWE

### ISSUE THREAD

**Issue by Lagicrus** [jpadilla/pyjwt#445]
Are there any plans to implement JSON Web Encryption to pyjwt?
I love using this lib and I want to move to add JWE as a layer of additional security to my application so I was wondering if there were any ideas in the pipeline for adding support for JWE rather then potentially having to swap libs or implement myself.

Thanks in advance

**Comment by malewars** [comment]
Any updates if this will be added?
Thanks!
