### ISSUE TITLE
Python 2 support ?

### ISSUE THREAD

**Issue by Djailla** [jpadilla/pyjwt#453]
Hello,

Python 2 support is almost over, do you think you should remove this support in the next major release ? It would allow extensive usage of mypy and f-strings and facilitate compatibility checks.

If agreed, I could provide a PR.

Regards

**Comment by KingDarBoja** [comment]
I do think the next major release should remove it as stated on [this anaconda post](https://www.anaconda.com/end-of-life-eol-for-python-2-7-is-coming-are-you-ready/).

Most packages already participating on it as seen [here](https://python3statement.org/).

Cheers!

**Comment by michael-k** [comment]
@Djailla can you close this issue?
