### ISSUE TITLE
Better documentation: complete encode and decode docs

### ISSUE THREAD

**Issue by dimaqq** [jpadilla/pyjwt#459]
https://pyjwt.readthedocs.io/en/latest/index.html has examples 😄
https://pyjwt.readthedocs.io/en/latest/api.html has only exceptions 😕

I wish there was complete documentation for `jwt.encode` and `jwt.decode` high level methods / public API.

Specifically, there are keyword arguments which are not trivial and `options=` which have defaults, but it takes digging into the source code to understand how the earlier work and what the latter are.

**Comment by tobni** [comment]
Agreed, was bit by the lack of docs and received deprecation warnings for 
```python
jwt.decode(msg, verify=False)
```
Had to consult source to find the use of the favored 
```python
jwt.decode(msg, options='verify_signature': False})
```
