### ISSUE TITLE
leeway is ignored

### ISSUE THREAD

**Issue by dimaqq** [jpadilla/pyjwt#460]
`leeway` is accepted as part of `**kwargs` in `.decode`, is passed to `_validate_claims()`, is forwarded to `_validate_iat|nbf|exp`:

https://github.com/jpadilla/pyjwt/blob/c404473271a199a7445b0e2a348e47893988bbc7/jwt/api_jwt.py#L141-L142

And then ignored:

https://github.com/jpadilla/pyjwt/blob/c404473271a199a7445b0e2a348e47893988bbc7/jwt/api_jwt.py#L166-L172

In fact the only test is that the value is sorta-numeric, the value itself is not checked.
The code will accept a very wide range of data: string `"42"`, int `42`, float `42.42`, boolean `true` and well as negative `"-42"` 😲

**Comment by dajiaji** [comment]
To my understanding, leeway is not ignored at the current implementation. @jpadilla @auvipy I think you can close this issue.

**Comment by dimaqq** [comment]
* `nbf` validation takes `leeway` into account
* `exp` validation takes `leeway` into account
* `iat` validation doesn't take current time into account, I guess that's OK? 🤷🏿
