### ISSUE TITLE
How to implement refresh token after access token expires?

### ISSUE THREAD

**Issue by ngc2392** [jpadilla/pyjwt#464]
I was hoping someone could help me with this. I have looked quite about online for this answer and am surprised I can't find an example somewhere. I am trying to implement a login view. If a user submits a username and password that matches a User in the database, then I create a token and return it to the frontend, and store it somehow in the browser. Now, the user does something else (edits some field) which requires a POST request. Enough time has passed so that the Access token is expired. How do I get a new one?

**Comment by vimalloc** [comment]
There are multiple ways this could be done such as having a separate refresh token or creating a new token before the old one expires. This stackoverflow answer is for flask + flask_jwt_extended, but should hopefully be generalized enough to give you some ideas: https://stackoverflow.com/questions/46197050/flask-jwt-extend-validity-of-token-on-each-request/46284627#46284627

**Comment by ngc2392** [comment]
@vimalloc thanks for the response. The second method makes the most sense to me and seems like what other libraries do. I'm going to give that a shot. Also, I have to write my own Authentication class for JWT to work, correct?

**Comment by jpadilla** [comment]
Thanks @vimalloc
