### ISSUE TITLE
Issue with decoding sequential arrays

### ISSUE THREAD

**Issue by bshaffer** [jpadilla/pyjwt#476]
### Summary.

See https://github.com/firebase/php-jwt/issues/259 for reference

It seems that there is an issue where sequential arrays (defined in JSON as `["item1", "item2", "item3"]` are not decoding as expected in this library, and instead the object notation of `{"0":"item1", "1": "item2", "2": "item3"}` is required.

## Expected Result

JSON sequential arrays should be encoded/decoded as expected (`["item1", "item2", "item3"]`)

## Actual Result

JSON sequential arrays are being encoded/decoded as objects, which presents discrepancies with other libraries (`{"0":"item1", "1": "item2", "2": "item3"}`)

**Comment by jpadilla** [comment]
I'm not sure about this. Based on https://tools.ietf.org/html/rfc7519#section-2

A JWT Claim Set has to be JSON object.

```
JWT Claims Set
  A JSON object that contains the claims conveyed by the JWT.

Claim
  A piece of information asserted about a subject.  A claim is
  represented as a name/value pair consisting of a Claim Name and a
  Claim Value.

Claim Name
  The name portion of a claim representation.  A Claim Name is
  always a string.

Claim Value
  The value portion of a claim representation.  A Claim Value can be
  any JSON value.
```

You can probably do something like the following though:


```python
import json
from jwt import PyJWS

jws = PyJWS()


def test_encode_decode():
    payload = ["item1", "item2", "item3"]

    secret = "secret"
    jwt_message = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.WyJpdGVtMSIsIml0ZW0yIiwiaXRlbTMiXQ.bla4vI5zqDa6p5NC9-Z5FYmqzvMUxc4n9snuPiFkpGk"
    decoded_payload = jws.decode(jwt_message, secret, algorithms=["HS256"])

    assert json.loads(decoded_payload) == payload
```
