### ISSUE TITLE
Commercial Usage rights for pyjwt

### ISSUE THREAD

**Issue by hi2rashid** [jpadilla/pyjwt#480]
We are using this module in our application with Django.

Can you please confirm if its okay to be used commercially.

Thank you in advance

**Comment by vimalloc** [comment]
This is using the MIT license, which does grant commercial use: https://github.com/jpadilla/pyjwt/blob/master/LICENSE

**Comment by jpadilla** [comment]
what @vimalloc said (thanks!)
