### ISSUE TITLE
validate nbf uses local timezone for its current time. I believe it should use UTC

### ISSUE THREAD

**Issue by matt-coppola** [jpadilla/pyjwt#487]
Summary.
_validate_nbf uses the local timezone for now when verifying whether the token is valid but should be using UTC time.

## Expected Result

The time validation should be using UTC.

## Actual Result

The validation uses the local timezone when determining the current time. This occurs in jwt/api_jwt.py ~line 154 when the call to timegm() converts to calendar time. Because I am in EST the time now is earlier than the nbf time set and thus validation fails. The NBF time was set to UTC time. 

I think this is a larger consistency issue at play. Any token that was created in a different timezone than that token is being decoded in will have varying results on whether the token is valid or not. 

## Reproduction Steps

1. Change your system timezone to be something earlier than GMT (Mine is EST)
2. Create a JWT with it's nbf set to the current UTC time (datetime.datetime.utcnow()).
3. Attempt to decode the token with validation for nbf. The validation will fail because the time now is earlier than the NBF time.

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": "2.5"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.2"
  },
  "platform": {
    "release": "5.4.0-25-generic",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "1.7.1"
  }
}
```

**Comment by auvipy** [comment]
any failing testcase?

**Comment by matt-coppola** [comment]
Not a failing unit test. I believe the reason you won't see any failures in UT is because the test is doing both the encoding and decoding. Given that it will be doing this UT on the same machine (with the same system timezone) you won't observe this error. The issue is that decode assumes the current system timezone is the same as the timezone the token was encoded in.

**Comment by matt-coppola** [comment]
Some additional details.
From the spec. https://tools.ietf.org/html/rfc7519 
An NBF must be a NumericDate https://tools.ietf.org/html/rfc7519#section-4.1.5 and a NumericDate must be in UTC https://tools.ietf.org/html/rfc7519#section-2

If you manually were to create a token with the NBF set to a utc time, and then tried to decode the token in a timezone such as EST the verification would fail because the time we are comparing against has been converted to EST by the call to timegm

**Comment by m10d** [comment]
I believe i encountered the same underlying issue upgrading an old project.

note there is likely a bug in decode today; handling of timezones is broken if the jwt is not encoded in a UTC localtime.

```    
# note this object has NO tz ... so below, "timegm()" interprets it as localtime
utc_now = datetime.utcnow()

# PyJwt's treatment of timezone creating the epoc time; api_jwt.py::decode()
pyjwt_now_ts = timegm(utc_now.utctimetuple()) 
pyjwt_now = datetime.fromtimestamp(pyjwt_now_ts).astimezone(timezone.utc)

# and the correctly handled (I believe) time
this_mod_now_ts = timegm(utc_now.astimezone(timezone.utc).utctimetuple())
this_mod_now = datetime.fromtimestamp(this_mod_now_ts).astimezone(timezone.utc)

print(
        f"""COMPARE PARSED TIMES:
    raw utc_now:             {utc_now}
    pyjwt:       {pyjwt_now_ts:10}=={pyjwt_now}
    correct:     {this_mod_now_ts:10}=={this_mod_now}
    """
    )
```

outputs:
```
    COMPARE PARSED TIMES:
        raw utc_now:             2020-10-26 22:01:39.225997
        pyjwt:       1603749699==2020-10-26 22:01:39+00:00
        correct:     1603771299==2020-10-27 04:01:39+00:00
```
