### ISSUE TITLE
Option require does not work if exp claim is absent

### ISSUE THREAD

**Issue by tohin** [jpadilla/pyjwt#488]
I assumed there will be an error in case if the `exp` claim is not provided in the token payload, If `require` option is enabled for `exp` claim.

## Expected Result

Exception in `decode` function.

## Actual Result

Token decoded successfully.

## Reproduction Steps

```python

import jwt

key = "foo"
token = jwt.encode({"foo": "bar"}, key, algorithm="HS256")
jwt.decode(token, key, options={"require": ["exp"]}, algorithms="HS256")
```

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.8"
  },
  "platform": {
    "release": "4.15.0-101-generic",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "1.7.1"
  }
}
```

**Comment by daniel-demelo** [comment]
`options={"require": [<whatever_claims>]}`

Does not work for me at all.
I even took a look at how you guys were testing this and your test doesn't even work when I tried.
It does not raise the exception.

```
        claim = "sub"
        payload = {
            "some": "payload",
            # claim not present
        }
        token = jwt.encode(payload, "secret")

        with pytest.raises(MissingRequiredClaimError) as exc:
            jwt.decode(token, "secret", options={"require": [claim]})

        assert exc.value.claim == claim
```

**Comment by vimalloc-mavenlink** [comment]
The latest release, `1.7.1`, does not include the the `require` option. You will need to wait for a new version to be released before being able to use it. You should make sure you are referring to the `stable` version of the documentation instead of the `latest` which is built from master: https://pyjwt.readthedocs.io/en/stable/usage.html#requiring-presence-of-claims

**Comment by tohin** [comment]
Oh, thanks for the clarification.
