### ISSUE TITLE
why does jwt.encode return a bytes string despite the "readthedocs" stating that it returns a string

### ISSUE THREAD

**Issue by pytheous** [jpadilla/pyjwt#505]
Please refer to our [StackOverflow tag](https://stackoverflow.com/questions/tagged/pyjwt) for guidance.

**Comment by Curiouspaul1** [comment]
> Please refer to our [StackOverflow tag](https://stackoverflow.com/questions/tagged/pyjwt) for guidance.

I swear i was about to raise this issue. Been having my jwt turned into bytes every time. However if you're looking for a quick fix (I'm not) you could use the "decode method" to decode according to utf-8 standard

`
import jwt
encoded = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')**.decode('utf-8')**

**Comment by Curiouspaul1** [comment]
> Please refer to our [StackOverflow tag](https://stackoverflow.com/questions/tagged/pyjwt) for guidance.

I swear i was about to raise this issue. Been having my jwt turned into bytes every time. However if you're looking for a quick fix (I'm not) you could use the "decode method" to decode according to utf-8 standard


`import jwt`
`token = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')**.decode('utf-8')** `
Dont add the asterisk o, it was only meant to indicate what's being done differently
so when you decode the token as follows:
jwt.decode(token,'secret') => you'd get it as string type

**Comment by jdufresne** [comment]
The last line of `PyJWT.encode()` calls the parent implementation:

https://github.com/jpadilla/pyjwt/blob/db4d2f09a1e5ba0b9fdab49d9e51006c60de2b63/jwt/api_jwt.py#L63-L65

The last line of `PyJWS.encode()` is:

https://github.com/jpadilla/pyjwt/blob/db4d2f09a1e5ba0b9fdab49d9e51006c60de2b63/jwt/api_jws.py#L125

The `.decode()` implies the return type is `str`, not `bytes`. 

IMO, the docs are correct and therefore this issue should be closed.

**Comment by francoisfreitag** [comment]
For future reference, the behavior was changed to return `str` in https://github.com/jpadilla/pyjwt/commit/5d33b041f2aeccc653436958c08187f1bd538d94 on August 24th, 2020.
