### ISSUE TITLE
Documentation and release out of sync

### ISSUE THREAD

**Issue by salcedo** [jpadilla/pyjwt#507]
The feature documented by [Requiring Presence of Claims](https://pyjwt.readthedocs.io/en/latest/usage.html#requiring-presence-of-claims) is not implemented in the current release version (1.7.1)

This was result of pull #280 as proposed #279

## Expected Result

>>jwt.decode(encoded, options={'require': ['any, 'claim', 'here']})
Should raise MissingRequiredClaimError

## Actual Result

The documentation states that options can be set to require any claim. However, the current latest release of pyJWT (1.7.1), only validates the presence of 'exp', 'iat', 'nbf'

```
    def _validate_required_claims(self, payload, options):
        if options.get('require_exp') and payload.get('exp') is None:
            raise MissingRequiredClaimError('exp')

        if options.get('require_iat') and payload.get('iat') is None:
            raise MissingRequiredClaimError('iat')

        if options.get('require_nbf') and payload.get('nbf') is None:
            raise MissingRequiredClaimError('nbf')
```

## Reproduction Steps

N/A

## System Information

```
{
  "cryptography": {
    "version": "2.9.2"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.4"
  },
  "platform": {
    "release": "5.7.10-zen1-1-zen",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "1.7.1"
  }
}
```

**Comment by vimalloc** [comment]
You should refer to the `stable` version of the documentation, instead of the `latest` version which is built from master. See https://pyjwt.readthedocs.io/en/stable/usage.html#requiring-presence-of-claims

**Comment by salcedo** [comment]
[https://github.com/jpadilla/pyjwt/blob/1.7.1/README.rst#documentation](https://github.com/jpadilla/pyjwt/blob/1.7.1/README.rst#documentation)

**Comment by vimalloc** [comment]
Yeah, that seems like a good candidate to be fixed. I imagine if you made a PR to update that to stable @auvipy or @jpadilla would be willing to merge it! :+1:

**Comment by salcedo** [comment]
If a user of this library simply follows the links from README.rst or "About", they could incorrectly assume the Require Presence of Claims functionality is working properly.

In the stable version, the `_validate_required_claims` method will only raise exception if 'exp', 'iat', or 'nbf'. 'required' key is ignored without error.

**Comment by salcedo** [comment]
Thanks @auvipy
