### ISSUE TITLE
Accept piped stdin with pyjwt cli usage

### ISSUE THREAD

**Issue by rezen** [jpadilla/pyjwt#509]
**Use case**
I'd love to use curl and pass on the content to `pyjwt` for decoding, instead of getting the error `Cannot read from stdin: terminal not a TTY`.

```sh
curl -u 'azurediamond:hunter2' -X POST "https://x.com/token" \
	--header "Content-Type: application/x-www-form-urlencoded" 
	--data-urlencode 'grant_type=client_credentials' \
	--data-urlencode 'scope=alligators:dance' \
	| jq -r '.access_token' |  pyjwt decode --no-verify 
```

**Change**. 
I think the change below would do the trick, but I'm not 100% sure.
https://github.com/jpadilla/pyjwt/blob/master/jwt/__main__.py#L71
```
- raise IOError('Cannot read from stdin: terminal not a TTY')
+ token = sys.stdin.readline()
```

**Comment by rezen** [comment]
Anything I can do to move this along?

**Comment by jdufresne** [comment]
The CLI entry point was removed in 8a14f087c285bbe2f6e85ba4818e6c620b708d5d. So perhaps this should be closed?
