### ISSUE TITLE
jwt.encode returns different result in python 2 and python 3

### ISSUE THREAD

**Issue by niinpatel** [jpadilla/pyjwt#517]
The following code returns a completely different result in python 2 and python 3

```python
import jwt
import collections
print(jwt.encode(collections.OrderedDict({'some': 'payload'}), 'secret', algorithm='HS256'))

```

in Python 3 it returns `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzb21lIjoicGF5bG9hZCJ9.Joh1R2dYzkRvDkqv3sygm5YyK8Gi4ShZqbhK2gxcs2U` 

and in the older version, it returns `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb21lIjoicGF5bG9hZCJ9.4twFt5NiznN84AWoo1d7KO1T_yoc0Z6XOpOVswacPZg` 

I think the difference is because of the order of headers, the module does json.dumps on headers on this line https://github.com/jpadilla/pyjwt/blob/66e39be5349f4671b9f6cca8974691070406fa92/jwt/api_jws.py#L104

in Python 2, json.dumps messes up the order of keys so it while python 3 doesn't, which results in this discrepancy.

**Comment by auvipy** [comment]
do you have any fix in mind?

**Comment by niinpatel** [comment]
> do you have any fix in mind?

Yes, using OrderedDict for headers would be a quick fix. Want me to raise a PR?

**Comment by auvipy** [comment]
sure but with unit test :1st_place_medal:

**Comment by niinpatel** [comment]
Okay, I'm on it!

**Comment by jpadilla** [comment]
Are there any concrete example/scenarios where this is issue? You should still be able to decode both those tokens across other systems/implementations/languages.

**Comment by jdufresne** [comment]
Python 2 is no longer supported.

Since Python 3.6+, [dict key order is preserved](https://docs.python.org/3.9/whatsnew/3.6.html#new-dict-implementation) and since Python 3.7+ [that is a language specification](https://docs.python.org/3.9/whatsnew/3.7.html#summary-release-highlights). Should this be closed?

**Comment by niinpatel** [comment]
> Should this be closed?

I think that is fine.
