### ISSUE TITLE
ECAlgorithm.from_jwk(key) gives a NotImplementedError()

### ISSUE THREAD

**Issue by dh-check** [jpadilla/pyjwt#518]
I've been attempting to use PyJWT for JWT authentication and was unable to use ECAlgorithm for verifying a JWT with a JWK. Every attempt to use `jwt.algorithms.ECAlgorithm(ECAlgorithm.SHA256).from_jwk(key)` results in a `NotImplementedError()`. I am able to call the right functions from `algorithms.py` with `RSAAlgorithm`. What is the correct way to call `ECAlgorithm`.

**Comment by jpadilla** [comment]
That will soon be available in v2

**Comment by dh-check** [comment]
Hi @jpadilla ,

Is there an estimated release date for v2? In addition, do you recommend another way to deserialize a JWK with PyJWT's current version for `ES256`?
