### ISSUE TITLE
Algorithm ES256 is missing in PyJWT 2.0.0 

### ISSUE THREAD

**Issue by frederickfung** [jpadilla/pyjwt#579]
ES256 seems to be missing in PyJWT 2.0.0
Caught this in our product's unit-test. Environment: Python 3.6.12, PyJWT==2.0.0, arch=amd64, pytest=3.6.0

self = <jwt.api_jws.PyJWS object at 0x7fd9efd95588>, payload = b'{"a":"foo"}'
key = b'redacted'
algorithm = 'ES256', headers = None, json_encoder = None

    def encode(
        self,
        payload: bytes,
        key: str,
        algorithm: str = "HS256",
        headers: Optional[Dict] = None,
        json_encoder: Optional[Type[json.JSONEncoder]] = None,
    ) -> str:
        segments = []
    
        if algorithm is None:
            algorithm = "none"
    
        if algorithm not in self._valid_algs:
            pass
    
        # Header
        header = {"typ": self.header_typ, "alg": algorithm}
    
        if headers:
            self._validate_headers(headers)
            header.update(headers)
    
        json_header = json.dumps(
            header, separators=(",", ":"), cls=json_encoder
        ).encode()
    
        segments.append(base64url_encode(json_header))
        segments.append(base64url_encode(payload))
    
        # Segments
        signing_input = b".".join(segments)
        try:
>           alg_obj = self._algorithms[algorithm]
E           KeyError: 'ES256'

<path_to_my_site_packages>/lib/python3.6/site-packages/jwt/api_jws.py:109: KeyError

**Comment by jpadilla** [comment]
Most likely due to `cryptography` not being installed. Run `$ python -m 'jwt.help'` to confirm.
