### ISSUE TITLE
PyJWT 2.0.0 leads to Error while login

### ISSUE THREAD

**Issue by CleoArcher** [jpadilla/pyjwt#583]
## Summary:
In my project we have a Django backend and a react Frontend. While using `django-graphql-jwt ==0.3.1` without specifying the `PyJWT` version it uses the latest version 2.0.0.
This leads to the Error: 
```
GraphQL error: 'str' object has no attribute 'decode'
```
I fixed the problem by manually setting the version of `PyJWT==1.7.1`.
I think the problem is in `def encode()` 
 
## Expected Result

Login via the react frontend while using JWT

## Actual Result
```
'str' object has no attribute 'decode'
```
Maybe it has something to do with the other packages, but see Fix.

## Reproduction Steps
Pipfile:
```
django-graphql-jwt = "==0.3.1" 
```
 

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.9"
  },
  "platform": {
    "release": "4.19.104-linuxkit",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "2.0.0"
  }
}
```

## Fix:

Pipfile:
```
django-graphql-jwt = "==0.3.1" 
PyJWT = "==1.7.1"
```

    $ python -m jwt.help
```
{
  "cryptography": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.9"
  },
  "platform": {
    "release": "4.19.104-linuxkit",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "1.7.1"
  }
}
```

**Comment by jpadilla** [comment]
`django-graphql-jwt` doesn't currently guard against installing a different major version of pyjwt, all new installations of that library will probably have the same issue.

Fix is most likely simple enough: https://github.com/flavors/django-graphql-jwt/blob/master/graphql_jwt/utils.py#L37-L42 and https://github.com/flavors/django-graphql-jwt/blob/master/setup.py#L41
