### ISSUE TITLE
PyJWT 2.0.0 causes issues

### ISSUE THREAD

**Issue by laurent-brisbois** [jpadilla/pyjwt#589]
I'm using django-graphql-jwt that deep inside uses PyJWT. When it was using `PyJWT 1.7.1` it was working fine. But when upgrading to `PyJWT 2.0.0` it gives error when I try to log in.

## Expected Result

No error when trying to log in.

## Actual Result

```
in jwt_encode
    jwt_settings.JWT_ALGORITHM,
graphql.error.located_error.GraphQLLocatedError: 'str' object has no attribute 'decode'
```

I can give more info if needed.

**Comment by jpadilla** [comment]
See https://github.com/jpadilla/pyjwt/issues/583#issuecomment-750362022
