### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by thenewguy** [jpadilla/pyjwt#594]
Just got hit with logins failing due to `It is required that you pass in a value for the "algorithms" argument when calling decode().`  I am guessing this is due to the change in v2.0.0.

I am not up to date on which algorithms are safe.  I am assuming this restriction was put into place because some of the available algorithms are no longer safe?

What is the best way to allow all safe algorithms for `payload = jwt.decode(token.token, **kwargs)`? 

For example, is this okay?
```
from jwt.algorithms import get_default_algorithms

allow_algorithms = [algo for algo in get_default_algorithms().keys() if algo.lower() != 'none']
```

**Comment by jpadilla** [comment]
@thenewguy I'd say try to explicitly list only algorithms that your application supports, instead of everything(unless that's what you really want).

**Comment by mcejp** [comment]
When using `PyJWKClient`, it would be super convenient to be able to say "accept whatever my IdP declares".
