### ISSUE TITLE
jwt.decode returns Signature has expired

### ISSUE THREAD

**Issue by mirajehossain** [jpadilla/pyjwt#601]
I expect the decoded result of JWT, but it returns an error `Signature has expired`

## Reproduction Steps
```python
  import jwt

  try:
      payload: Dict = jwt.decode(token_obj[1], SECRET_KEY, algorithms=['HS256'], verify=True)
  except Exception as err:
      return JsonResponse(data={
          'message': err,
          'success': False,
      }, status=401)
```

## System Information

    $ python -m jwt.help

```json

{
  "cryptography": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.12"
  },
  "platform": {
    "release": "4.19.121-linuxkit",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "2.0.0"
  }
}
```

**Comment by mchasej** [comment]
Verify that your token is not expired.  Use https://jwt.io/ or https://jwt.ms/ to check the claims of the token and that the `exp` parameter is not in the past.  Tokens are often short-lived for security reasons.

If you are simply testing code with expired tokens, try using the `verify_exp` option:

```
jwt.decode(token_obj[1], SECRET_KEY, algorithms=['HS256'], verify=True, options={'verify_exp':False})
```

**Comment by jpadilla** [comment]
Also note that `verify` param is deprecated in 2.0 https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.rst#dropped-deprecated-verify-param-in-jwtdecode
