### ISSUE TITLE
Pip Install will not install versions greater than or equal to 2.0 after 2.0.1 release

### ISSUE THREAD

**Issue by goneall** [jpadilla/pyjwt#607]
Summary.

Attempting to install pyjwt version >= 2.0 results in an error.

## Expected Result

Installation of the 2.0.1 version

## Actual Result

The following error: 

```
Could not find a version that satisfies the requirement PyJWT>=2.0.0
```

## Reproduction Steps
```
pip install "PyJWT>=2.0.0"
```
First discovered installing social-auth-core>=3.3.0 which has PyJWT as a dependency.

See [SPDX online tools issue 284](https://github.com/spdx/spdx-online-tools/issues/284) for the original error details.

## System Information

Both on Ubuntu and Windows within a virtual environment.

Python version 2.7.

Pip version 20.0.2.

I noticed that version 2.0.1 was release just 4 hours ago - perhaps this is related?

**Comment by lucasvazq** [comment]
Same problem here
```
ERROR: Could not find a version that satisfies the requirement PyJWT==2.0.1 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 1.0.0, 1.0.1, 1.1.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.3, 1.6.4, 1.7.0, 1.7.1)
```

**Comment by jpadilla** [comment]
Dropped support for Python 2 starting in PyJWT 2.0.0 https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.rst#drop-support-for-python-2-and-python-30-35

**Comment by goneall** [comment]
@jpadilla Thanks for the pointer.  It looks like the problem I'm running into is related to changes in the requirements for [python-social-auth](https://github.com/python-social-auth/social-core) and not related to changes in pyjwt.

**Comment by lucasvazq** [comment]
@jpadilla The 4.0.3 version of social-core (released 6 days ago) uses `PyJWT>=2.0.0`
See changelog: https://github.com/python-social-auth/social-core/releases/tag/4.0.3

The penultimate version, 4.0.2 (released 8 days ago) uses `PyJWT>=1.4.0,<2` and is Python 2 compatible

**Comment by lucasvazq** [comment]
@goneall The 4.0.3 version of social-core (released 6 days ago) uses `PyJWT>=2.0.0`
See changelog: https://github.com/python-social-auth/social-core/releases/tag/4.0.3

The penultimate version, 4.0.2 (released 8 days ago) uses `PyJWT>=1.4.0,<2` and is Python 2 compatible

**Comment by goneall** [comment]
Thanks @lucasvazq 

The social-core is a dependency of [social-auth-app-django](https://github.com/python-social-auth/social-app-django) which specifies the dependency as `social-auth-core >= 3.3.0`.  It looks like it is picking up the latest version making several versions of social-app-django incompatible.

Do you know if there is a way to work-around this without changing social-app-django requirements file?

I'll also add an issue to the social-app-django.

**Comment by lucasvazq** [comment]
@goneall Yes, you can install first `social-auth-core==4.0.2`, and then install `social-auth-app-django`

**Comment by goneall** [comment]
> you can install first social-auth-core==4.0.2, and then install social-auth-app-django

@lucasvazq Thanks for the tip - that worked.
