### ISSUE TITLE
ImportError: cannot import name 'AsymmetricPadding' (most likely due to a circular import)

### ISSUE THREAD

**Issue by derkkila** [jpadilla/pyjwt#613]
## Summary
Due to project requirements, all libraries must be included in the project, rather than being installed via pip. When doing this, I get an ImportError: cannot import name 'AsymmetricPadding' from partially initialized module 'cryptography.hazmat.primitives.asymmetric.padding' (most likely due to a circular import).

## Expected Result

Expect the library to be imported without issue.

## Actual Result

When importing jwt, I get the following error message:
`Traceback (most recent call last):
  File "C:\project\script.py", line 12, in <module>
    import jwt
  File "C:\project\lib\jwt\__init__.py", line 1, in <module>
    from .api_jws import (
  File "C:\project\lib\jwt\api_jws.py", line 6, in <module>
    from .algorithms import (
  File "C:\project\lib\jwt\algorithms.py", line 20, in <module>
    from cryptography.hazmat.primitives.asymmetric import ec, padding
  File "C:\project\lib\cryptography\hazmat\primitives\asymmetric\padding.py", line 9, in <module>
    from cryptography.hazmat.primitives.asymmetric import rsa
  File "C:\project\lib\cryptography\hazmat\primitives\asymmetric\rsa.py", line 20, in <module>
    from cryptography.hazmat.primitives.asymmetric.padding import AsymmetricPadding
ImportError: cannot import name 'AsymmetricPadding' from partially initialized module 'cryptography.hazmat.primitives.asymmetric.padding' (most likely due to a circular import) (C:\project\lib\cryptography\hazmat\primitives\asymmetric\padding.py)`

If I install cryptography via pip, everything works fine, however the target destination cannot use pip and external libraries need to be included in the project (which I am doing). Importing cryptography via this method has no issues either, only the import of jwt.

## Reproduction Steps

```python
import os
import sys
import time
import datetime

dir = os.path.join(os.path.join(os.getcwd()),'lib')
if not dir in sys.path:
    sys.path.append(dir)

from cryptography.hazmat.backends import default_backend

import jwt
```

**Comment by derkkila** [comment]
I even went with using 'pip install -t lib pyjwt' and get the same behavior.

**Comment by derkkila** [comment]
I was able to fix it by re-installing via pip to a local directory.

**Comment by 9sVYLuLL** [comment]
@derkkila which version of crypto were you using?
