### ISSUE TITLE
how can i encode mongodb object id

### ISSUE THREAD

**Issue by abhishekdhadwal** [jpadilla/pyjwt#618]
how can i encode mongodb object id. when i try to encode it returns empty object

**Comment by auvipy** [comment]
Share your code snippets, please

**Comment by abhishekdhadwal** [comment]
import jwt
from src.config import app_constant
from src.config import mongo
collections = mongo.db

options = "HS256"

admin_sk = app_constant.seckret_keys["admin_seckret_key"]
print("admin_sk : ",admin_sk)

def generate_token(payload) : 

      try :

            print("----------------payload--",payload)
            gen_token = jwt.encode({"admin_id" : payload['admin_id']}, key, options)
            print('--------------------gen_token--',gen_token)

            return gen_token
            
      except Exception as err :
            return err

**Comment by abhishekdhadwal** [comment]
![Uploading Screenshot from 2021-02-21 18-50-52.png…]()

**Comment by jpadilla** [comment]
you should be able to specify a custom json encoder https://github.com/jpadilla/pyjwt/blob/master/tests/test_api_jwt.py#L545
