### ISSUE TITLE
Support from_jwk for Ed25519Algorithm

### ISSUE THREAD

**Issue by dajiaji** [jpadilla/pyjwt#621]
I'd like to use `get_signing_key_from_jwk()`  for JWT with alg=EdDSA.

But, at the moment, it seems that pyjwt does not support it because `Ed25519Algorithm` does not have `from_jwk()`.

Do you have a plan to support that?
If you don't have the plan, I can send a PR for that.

I'd appreciate it if you can tell me the plan to support EdDSA-based token.

**Comment by crgwbr** [comment]
For reference, looks like the spec for this is in [RFC 8037](https://tools.ietf.org/html/rfc8037#section-2).

**Comment by dajiaji** [comment]
Yes, in other words, I need from_jwt()  for JWT kty=OKP compliant with RFC8037.
