### ISSUE TITLE
Ability to remove dictionary value "typ": "JWT" from jwt header

### ISSUE THREAD

**Issue by codrinh** [jpadilla/pyjwt#641]
Suggest an idea for this project.
Hi, I'm hitting a limitation where I cannot use this library as it is adding the "typ": "JWT" dict to the header automatically.

A similar issue has been reported below.
https://stackoverflow.com/questions/61511738/pyjwt-custom-header-remove-type-from-jwt-header

Can you please add "typ" as optional?

Thank you

**Comment by dajiaji** [comment]
@codrinh Could you check the above PR? Is this what you want?

**Comment by codrinh** [comment]
@dajiaji looks great, thanks a lot !
