### ISSUE TITLE
Are there any plans to have classes for parsing RFC 8414 well-known endpoints?

### ISSUE THREAD

**Issue by ekuns** [jpadilla/pyjwt#648]
It would make life easier if there were classes where one could pass the URL as configuration, and the rest of the classes in this library could self-configure from that.  The RFC is at:

https://tools.ietf.org/html/rfc8414

Is this planned at any point?  Or would a pull request implementing something for this be welcomed?  (I don't know if I'd have time myself to work on such a thing or not.)

**Comment by dajiaji** [comment]
I think that RFC8414 is an OAuth2/OpenID Connect related specification that should be implemented outside of the JWT library.
In addition, In the attributes defined in RFC8414, `jwks_uri` is the only URL which is related to JWT. I think there is no reason that RFC8414 should be implemented in this library.

@jpadilla @auvipy If you can agree with me, I think you can close this issue.
