### ISSUE TITLE
Support for providing custom headers in PyJWKClient fetch_data

### ISSUE THREAD

**Issue by gauravvjn** [jpadilla/pyjwt#665]
[This line ](https://github.com/jpadilla/pyjwt/blob/2.1.0/jwt/jwks_client.py#L20) raises 403 for URLs that are expecting some headers, mostly `User-Agent` (e.g. Cloudflare URLs) 

Here is a similar issue from another project: https://github.com/datopian/datahub-qa/issues/81

urllib’s default user agent is "Python-urllib/3.7" (on Python 3.7). https://github.com/python/cpython/blob/3.7/Lib/urllib/request.py#L435

Right now we are monkey patching this method to providing `User-Agent` explicitly to make it work for Cloudflare open endpoints

```py
def _fetch_data(self):
    import urllib.request
    client = urllib.request.Request(self.uri, headers={"User-Agent" : "Mozilla/5.0"})
    response = urllib.request.urlopen(client)
    return json.load(response)

jwt.PyJWKClient.fetch_data = _fetch_data
```

A possible approach can be -

```py
class PyJWKClient:
    def __init__(self, uri: str, cache_keys: bool = True, max_cached_keys: int = 16, **kwargs):
        self.uri = uri
        self.headers = kwargs.get(headers, {})
        ...

    def fetch_data(self) -> Any:
        client = urllib.request.Request(self.uri, headers=self.headers)
        with urllib.request.urlopen(client) as response:
            return json.load(response)
```

**Comment by matpuk** [comment]
This can be extended a bit and make it possible to provide socket timeout to pass to urlopen(client) too.
