### ISSUE TITLE
interested in a meaningful contribution?

### ISSUE THREAD

**Issue by dhh1128** [jpadilla/pyjwt#672]
@jpadilla , I am working on a technology called DIDComm. It makes heavy use of JWKs, JWEs, and JWSs -- but not really JWTs. It's being done in FOSS in conjunction with the Decentralized Identity Foundation, Trust Over IP Foundation, and Linux Foundation. Eventually the spec that we're trying to implement is going to IETF.

After studying various python libs for JOSE, we have concluded that PyJWT is closest to what we'd like to start from. But we need some new features:

* Ability to save a JWK, not just load one.
* Support for JWE -- but only for a subset of the algorithms in the JWT spec.
* Support for JWS.

We could just pull some code out of your excellent library and do our own independent thing, but we're wondering if you'd like a meaningful contribution of the features I listed above. (We'd do the work; we're not trying to find someone else to do the coding for us...)

I feel like these features are outside your sweet spot, since the name of the library has "JWT" in it, and I assume your main use case is JWT usage in enterprise login workflows. But I wanted to check to see how you felt about it, before I jumped to conclusions. What do you think?

(Tagging @vimmerru and @ashcherbakov, who are interested in the answer.)

**Comment by jpadilla** [comment]
Meaningful contributions (fixes, features, improvements, docs, issues, etc) are always welcome! JWK, JWE, and JWS are all still related and I wouldn't let the Py_JWT_ name get in the way of that.
