### ISSUE TITLE
AzureAD JWKS get signing key from jwt failed

### ISSUE THREAD

**Issue by ioxFR** [jpadilla/pyjwt#677]
Hello,

I trying to use pyjwt to validate jwt from azureAD. But i got some issue to get signing key to decode it.

## Expected Result

signing_key = jwks_client.get_signing_key_from_jwt(token) should return the signing key to be able to decode the jwt

## Actual Result

An exception throwed with message:
Unable to find a algorithm for key

Stacktrace:
Traceback (most recent call last):
 File "/var/task/authorizer.py", line 51, in lambda_handler
 payload = verify_jwt(
 File "/var/task/authprovider.py", line 28, in verify_jwt
 signing_key = jwks_client.get_signing_key_from_jwt(token)
 File "/var/task/jwt/jwks_client.py", line 59, in get_signing_key_from_jwt
 return self.get_signing_key(header.get("kid"))
 File "/var/task/jwt/jwks_client.py", line 41, in get_signing_key
 signing_keys = self.get_signing_keys()
 File "/var/task/jwt/jwks_client.py", line 28, in get_signing_keys
 jwk_set = self.get_jwk_set()
 File "/var/task/jwt/jwks_client.py", line 25, in get_jwk_set
 return PyJWKSet.from_dict(data)
 File "/var/task/jwt/api_jwk.py", line 92, in from_dict
 return PyJWKSet(keys)
 File "/var/task/jwt/api_jwk.py", line 87, in __init__
 self.keys.append(PyJWK(key))
 File "/var/task/jwt/api_jwk.py", line 50, in __init__
 raise PyJWKError("Unable to find a algorithm for key: %s" % self._jwk_data)
jwt.exceptions.PyJWKError: Unable to find a algorithm for key

## Reproduction Steps

JWT emit from AzureAD App Registration (token in below code)
jwks_uri is the key azureAD endpoint: https://login.microsoftonline.com/common/discovery/keys

```python
import jwt
 jwks_client = PyJWKClient(jwks_uri)
signing_key = jwks_client.get_signing_key_from_jwt(token)
decoded = jwt.decode(
            token,
            signing_key.key,
            verify=True,
            algorithms=['RS256'],
            issuer=issuer,
            options={'verify_aud': False}
)
```

## System Information

Linux x64 (AWS Lambda@Edge) - Python 3.8

Thanks in advance
Rgds,
Valentin

**Comment by Thanabhat** [comment]
Can you try to install cryptography package on Azure app service?
https://pypi.org/project/cryptography/

**Comment by ioxFR** [comment]
Hello @Thanabhat 

Already tried on local but same thing.
I cannot also keep crypto lib in my package as it is heavy and as i'm in lambda@edge context limit of package cannot be more than 1MB...
But you confirm that pyjwt already including algorithm required to decode jwt right? as this is "classic" algorithm i suppose to.

**Comment by Thanabhat** [comment]
If you are using `RS256`, you need a `cryptography` package.

In this file, https://github.com/jpadilla/pyjwt/blob/master/jwt/algorithms.py#L69, RS256 is imported from `cryptography`.

**Comment by ioxFR** [comment]
Hi @Thanabhat ,

Thanks for your reply.
Maybe we can add this dependency to the doc as requirement...
My package size changed to 5MB with crypto :D 
I have to find solution for that.
Thanks for help!
