### ISSUE TITLE
Support using AWS KMS to sign and verify.

### ISSUE THREAD

**Issue by JosiahDub** [jpadilla/pyjwt#681]
AWS KMS allows for signing and verifying arbitrary binary strings using a variety of algorithms. Create an "algorithm" that wraps the `boto3 kms` methods of `sign` and `verify`. The key would be the key id, key ARN, etc, created in KMS.

This may be slightly difficult as the algorithm would have to handle not only the key but the signing algorithm. If desired, this could be a separate library built on top of PyJWT.

More info:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kms.html#KMS.Client.verify

**Comment by jtemporal** [comment]
Refer to [#issuecomment-966739972](https://github.com/jpadilla/pyjwt/pull/682#issuecomment-966739972).

**Comment by bdw666** [comment]
I've partially implemented some of this, there are advantages to keeping the signing keys in KMS. I've implemented ES256, at least for signing, for verifying I'm still using the python lib to do it with the public key in KMS. the R|S to ANS.1 conversion isn't super easy, ANS.1 to R|S is fairly straight forward.
