### ISSUE TITLE
2.1.0 unable to decode with verify=False when 1.7.1 (and jwt.io) can

### ISSUE THREAD

**Issue by MarcinBMD** [jpadilla/pyjwt#687]
I'm using a decode workflow where I decode an incoming token with `verify=False`, then use the 'iss' inside to retrieve the public key and then RE-decode using the key to ensure authenticity. In 1.7.1 I used another library to convert the key to the expected PEM format which worked fine, but I wanted to use 2.1.0's conversion ability with:

```
pem_key = jwks_client.get_signing_key_from_jwt(public_key)
```

Unfortunately it doesn't work anymore because the key doesn't decode when unverified. Maybe this is specific to the provider (Epic in this case) but it **decodes just fine** (without a key) at jwt.io.

## Expected Result

With 1.7.1:
```
(Pdb) jwt.decode(id_token, verify=False)
{'aud': 'XXXXXX-XXXX-XXXX-XXX', 'exp': 1632501694, 'iat': 12345678901, 'iss': 'https://iss-url-here.com/auth', 'sub': 'e0halh35asdfaq3HKfHF4'}
```

## Actual Result

With 2.1.0:

(Pdb) jwt.get_unverified_header(id_token)
{'alg': 'RS256', 'kid': 'lakjheiubvliaugeflkajdhf=', 'typ': 'JWT'}

(Pdb) jwt.decode(id_token, algorithms=["RS256"], verify=False)
*** ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

## Reproduction Steps

Retrieve an id_token from Epic.com using their SSO process.

```python
import jwt

unverified_token = jwt.decode(id_token, algorithms=["RS256"], verify=False)

```

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": "3.3.2"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.10"
  },
  "platform": {
    "release": "5.10.25-linuxkit",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "2.1.0"
  }
}
```

This command is only available on PyJWT v1.6.3 and greater. Otherwise,
please provide some basic information about your system.

**Comment by geekypandey** [comment]
I think the syntax you are using is not quite correct. We need to pass an `options` dictionary for validation options.
Like this:
```py
import jwt

options = {'verify_signature': False}
unverified_token = jwt.decode(id_token, algorithms=["RS256"], options=options)
```

Link to reference API: [jwt.decode](https://pyjwt.readthedocs.io/en/2.1.0/api.html#jwt.decode)

**Comment by geekypandey** [comment]
That is actually quite strange. It should have given some error 🤔
