### ISSUE TITLE
Windows and Linux jwt encode return differently

### ISSUE THREAD

**Issue by mr-lanholmes** [jpadilla/pyjwt#688]
Hi team,

I realised the return provided by jwt.encode() is different on Windows and Linux.

Came across this as I was deploying my Flask app to include the jwt token to my jsonify return.

On Windows, I can pass to jsonify without problem but on Linux, I should append the jwt.encode() with .decode('utf-8') in order for jsonify to be able to process it.

I believe on Linux the jwt.encode() return bytes while on Windows is string?

Is this a localised issue with my development machine and server? or someone else has come across this?

Thanks!

**Comment by auvipy** [comment]
can you share the code detail and output detail? you can share screenshots too

**Comment by geekypandey** [comment]
Could you share the versions of the library being used in both Windows and Linux?
Starting from v2.0.0, the `encode` function returns string instead of bytes.

Reference commit: 5d33b041f2aeccc653436958c08187f1bd538d94

**Comment by mr-lanholmes** [comment]
Thanks @auvipy @geekypandey for the replies.

I believe is due to the different version, my bad didnt lock the requirements.txt

Linux: 1.7.1
Windows: 2.0.0

I bumped my Linux PyJWT version up to 2.0.0 and fixed the issue.

Thank you so much and have a great day ahead!
