### ISSUE TITLE
Allow to extend at will the list of claims mapped to a time value

### ISSUE THREAD

**Issue by bastantoine** [jpadilla/pyjwt#707]
Hello,

I'm using your lib right now to setup access and refresh tokens for an app in my work. In the specs of the refresh token, I have the `val` claim that represent the validity window of the refresh token. It is a timestamp which represents the datetime before which the refresh token can be used to get a new bearer - refresh token pair.

In my Python model, this claim is handled using an instance of `datetime.datetime`. The thing is that when I try to encode it I get a `TypeError: Object of type datetime is not JSON serializable` error, and I was wondering while this didn't happened for the bearer token.

I managed to track it down to this piece of code at the beginning of the `encode` function:

https://github.com/jpadilla/pyjwt/blob/31a8701d11709ce0807b60f7a5fa604d14175235/jwt/api_jwt.py#L54-L57

I had no issue with the bearer token as in its claims the only time-based ones are `exp`, `iat` and `nbf`, and thus are properly converted to string before the `json.dumps`.

So I was wondering whether you'd be interested in doing something like this:

```diff
def encode(
    self,
    payload: Dict[str, Any],
    key: str,
    algorithm: Optional[str] = "HS256",
    headers: Optional[Dict] = None,
+   time_claims: Optional[Array[string]] = [],
    json_encoder: Optional[Type[json.JSONEncoder]] = None,
) -> str:
        ...
-       for time_claim in ["exp", "iat", "nbf"]:
+       for time_claim in ["exp", "iat", "nbf"] + time_claims:
            # Convert datetime to a intDate value in known time-format claims
            if isinstance(payload.get(time_claim), datetime):
                payload[time_claim] = timegm(payload[time_claim].utctimetuple())
        ...
```

I'd happy to send a PR if you think this is a good idea.

**Comment by jpadilla** [comment]
Passing a custom json.JSONEncoder would also solve this, no?
