### ISSUE TITLE
encode error

### ISSUE THREAD

**Issue by oinklulu** [jpadilla/pyjwt#714]
https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jws.py   line129
In the old version, there was no `return encoded_string.decode("utf-8")`, why add this?
It seems that encode should not be decoded.

**Comment by auvipy** [comment]
why this should not be decoded?

**Comment by jtemporal** [comment]
I'm closing this one since it has been more than 3 months without a response from the issue author.

Please feel free to submit another issue following the issue template if the problem persists.
