### ISSUE TITLE
TypeError: sign() takes 3 positional arguments but 4 were given (not EC key)

### ISSUE THREAD

**Issue by msaba92** [jpadilla/pyjwt#717]
I have a private key extracted from a p12 file with 
`openssl pkcs12 -in my_key.p12 -out my_key.key -nocerts -nodes`

I'm following the docs at https://pyjwt.readthedocs.io/en/latest/usage.html. doing:

```
>>> private_key = Path("path/to/my_key.key").read_bytes()
>>> encoded = jwt.encode({"some": "payload"}, private_key, algorithm="RS256")
```

## Expected Result.

I expect the JWT to be created.

## Actual Result

Same issue as issue #429, but in my case it's not an EC key. The key starts with `b'-----BEGIN PRIVATE KEY-----\n`.

```
    encoded = jwt.encode({"some": "payload"}, private_key, algorithm="RS256")
  File "/home/user/.local/lib/python3.7/site-packages/jwt/api_jwt.py", line 63, in encode
    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
  File "/home/user/.local/lib/python3.7/site-packages/jwt/api_jws.py", line 114, in encode
    signature = alg_obj.sign(signing_input, key)
  File "/home/user/.local/lib/python3.7/site-packages/jwt/algorithms.py", line 378, in sign
    return key.sign(msg, padding.PKCS1v15(), self.hash_alg())
TypeError: sign() takes 3 positional arguments but 4 were given

```

Perhaps I'm missing something, but the docs are not helping here.

**Comment by auvipy** [comment]
TypeError: sign() takes 3 positional arguments but 4 were given

**Comment by msaba92** [comment]
I dug a bit, and apparently https://github.com/jpadilla/pyjwt/blob/master/jwt/algorithms.py#L262 here `key = load_pem_private_key(key, password=None)` returns a `<cryptography.hazmat.backends.openssl.ec._EllipticCurvePrivateKey object>`, despite this not being an EC key. Beyond that, I wouldn't know how to debug any more.
