### ISSUE TITLE
Decode fails after upgrade from 1.7.1

### ISSUE THREAD

**Issue by Spurlock** [jpadilla/pyjwt#735]
Hello.

I'm upgrading PyJWT from 1.7.1 to 2.3.0 (cryptography 36.0.1 also installed).

When using the upgraded library, this call fails:

`jwt.decode(token, self.secret_key, algorithms=["HS256"])`

even though nothing else (token, key, algo) has changed. The exception thrown is: 

"Invalid header string: 'utf-8' codec can't decode byte 0x97 in position 2: invalid start byte" 

Reverting back to the earlier version fixes the issue, so it seems like the API contract has changed in some subtle way and I need to adjust the inputs to the `decode` call (or possibly the `encode` elsewhere). Help?

**Comment by akx** [comment]
You should show the relevant traceback too, not only the exception message.
