### ISSUE TITLE
Third party suddenly does not accept my ES256 token generated with PyJwt, any help appreciated!

### ISSUE THREAD

**Issue by SHxKM** [jpadilla/pyjwt#736]
I've been using `PyJWT==2.1.0` successfully to generate a JWT token needed for a third-party service authentication, it's an ES256 token. Recently though, I've had to upgrade some dependencies and one of them, `cryptography`, was bumped from `3.4.7` to the whopping `36.0.1`. Since then, this third party service has been denying my JWT tokens, even though I can encode and decode them. This third party services also requires signing the token.

Can `cryptography` change the way `PyJWT` works? excuse my general ignorance about this subject

**Comment by SHxKM** [comment]
When I check the token on jwt.io it seems to decode just fine, so I really don't understand if I'm just unlucky. Here's what the requirements about the key say:


> After you create the token, sign it with your private key. Then encrypt the token using the Elliptic Curve Digital Signature Algorithm (ECDSA) with the P-256 curve and the SHA-256 hash algorithm. Specify the value ES256 in the algorithm header key (alg).


And here's how I'm doing that:

```
    secret = my_secret

    keyId = "MYKEYID"
    issId = "MYTEAM"
    alg = "ES256"

    time_now = datetime.now()
    time_expired = datetime.now() + timedelta(hours=120)

    headers = {"alg": alg, "kid": keyId}

    payload = {
        "iss": issId,
        "exp": int(time_expired.strftime("%s")),
        "iat": int(time_now.strftime("%s")),
    }

    token = jwt.encode(payload, secret, algorithm=alg, headers=headers)
```

What am I doing wrong?

**Comment by YongquanYao** [comment]
how do you solve this ?
