### ISSUE TITLE
Typing on the get_unverified_header function

### ISSUE THREAD

**Issue by lindycoder** [jpadilla/pyjwt#745]
Hello, thank you for the tool!

It seems the `get_unverified_header` is missing types to use in a strict mypy configuration!

https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jws.py#L202

If I am not mistaken, this might do it:

```
def get_unverified_header(self, jwt: str) -> Dict[str, Any]:
```

**Comment by lindycoder** [comment]
Actually based on what _load takes, jwt should be a `Union[str, bytes]`

**Comment by lindycoder** [comment]
Removing stale just waiting for a maintainer to comment if this issue is valid or not.

**Comment by jpadilla** [comment]
lgtm, can you open a PR?

**Comment by lindycoder** [comment]
Thanks, I might look into it, might take a couple weeks though, pretty busy
