### ISSUE TITLE
Able to decode a tampered token which is signed using EdDSA encryption

### ISSUE THREAD

**Issue by aniketor** [jpadilla/pyjwt#752]
### Generating token
I generated a key pair using EdDSA encryption and signed the token using the private key.
```
from cryptography.hazmat.primitives import serialization as crypto_serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.backends import default_backend as crypto_default_backend

key = Ed25519PrivateKey.generate()
private_key = key.private_bytes(
	    crypto_serialization.Encoding.PEM,
	    crypto_serialization.PrivateFormat.PKCS8,
	    crypto_serialization.NoEncryption())
public_key = key.public_key().public_bytes(
	    crypto_serialization.Encoding.PEM,
	    crypto_serialization.PublicFormat.SubjectPublicKeyInfo)
	    
payload_data = {"some" : "data"}

token = jwt.encode(payload=payload_data, key=private_key, algorithm='EdDSA')
```
Generated token:

> eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSJ9.eyJzb21lIjoiZGF0YSJ9._3oq_s2sEUJ3hqu5yubnbsVruJDC8D_iSddoUpGyMjC_0jsE8Q3HkcTSaP2dNNKil8PAhCoHRAwy4O52V6eeBQ

Public key:
> -----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAYumW5/xzvN31HiOokLGZuHYcp6CSohd4CyibXz7vDcw=\n-----END PUBLIC KEY-----\n

### Decoding the token
```
>>> pub = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAYumW5/xzvN31HiOokLGZuHYcp6CSohd4CyibXz7vDcw=\n-----END PUBLIC KEY-----\n"
>>> tok = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSJ9.eyJzb21lIjoiZGF0YSJ9._3oq_s2sEUJ3hqu5yubnbsVruJDC8D_iSddoUpGyMjC_0jsE8Q3HkcTSaP2dNNKil8PAhCoHRAwy4O52V6eeBQ"
>>> jwt.decode(jwt=tok, key=pub, algorithms=['EdDSA', ])
{'some': 'data'}
```
### Tampering the token
Replaced the last character "Q" of the token with a small case "d".
```
>>> pub = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAYumW5/xzvN31HiOokLGZuHYcp6CSohd4CyibXz7vDcw=\n-----END PUBLIC KEY-----\n"
>>> tok = "eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSJ9.eyJzb21lIjoiZGF0YSJ9._3oq_s2sEUJ3hqu5yubnbsVruJDC8D_iSddoUpGyMjC_0jsE8Q3HkcTSaP2dNNKil8PAhCoHRAwy4O52V6eeBd"
>>> jwt.decode(jwt=tok, key=pub, algorithms=['EdDSA', ])
{'some': 'data'}
```

Ideally we should not be able to decode the token if it has been changed but I was able to still decode the token.

### pyJWT version
```
2.3.0
```
### Python version
```
Python 3.10.4
```

**Comment by JohnnyRacer** [comment]
@aniketor [aniketor](https://github.com/aniketor) Have you found a solution to this problem? I am having the same issue with encrypting tokens with EdDSA where the output is just an unencrypted b64encoded string. Seems like nothing changed even if I change the keys and generate new ones using OpenSSL.
