### ISSUE TITLE
The Problem header position please update

### ISSUE THREAD

**Issue by Nandoxp** [jpadilla/pyjwt#755]
![gambar](https://user-images.githubusercontent.com/13316777/168331708-e512a6ff-bbbd-4fe7-a840-6a3de3818ff3.png)
i want to create "alg" header on the first one and the second one is "typ" header

**Comment by auvipy** [comment]
can you please share more detail?

**Comment by Nandoxp** [comment]
you can see on here
![gambar](https://user-images.githubusercontent.com/13316777/168452526-06188937-0134-40d8-ae7f-e4ad780fc6c9.png)
I want to sort in order , i want alg header in first , and jwt in the second

**Comment by Nandoxp** [comment]
![gambar](https://user-images.githubusercontent.com/13316777/168466396-392840fb-843a-4597-b6d0-96d1fedd579f.png)
i have solved the problem so everyone if you have same problem with me just edit api_jws.py

**Comment by Nandoxp** [comment]
please update my recommend to your code
