### ISSUE TITLE
Update documentation to reference the latest spec

### ISSUE THREAD

**Issue by mark-adams** [jpadilla/pyjwt#80]
Apparently there have been 30+ iterations to the JWT spec since the pyjwt documentation was created. Do we need to update the docs to reflect that we're up to speed with the latest versions of the spec?

https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32

@jpadilla Thoughts?

**Comment by jpadilla** [comment]
Yeah definitely

**Comment by mark-adams** [comment]
K. I'll create a pull request with updated links and text.
