### ISSUE TITLE
Encoding with RSA public key and decoding with private key

### ISSUE THREAD

**Issue by svnv** [jpadilla/pyjwt#81]
In the documentation it says:
> When using the RSASSA-PKCS1-v1_5 algorithms, the key argument in both jwt.encode() and jwt.decode() ("secret" in the examples) is expected to be either an RSA public or private key in PEM format.

When i try to encode the payload with the public key i get an error:

    >>> jwt_message = jwt.encode(payload, pub_rsakey, 'RS384')
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/Users/sven/code/sso/env/lib/python2.7/site-packages/jwt/__init__.py",
     line 295, in encode
        signature = signing_methods[algorithm](signing_input, key)
      File "/Users/sven/code/sso/env/lib/python2.7/site-packages/jwt/__init__.py",
     line 131, in <lambda>
        'RS384': lambda msg, key: sign_rsa(msg, key, hashes.SHA384()),
      File "/Users/sven/code/sso/env/lib/python2.7/site-packages/jwt/__init__.py",
     line 106, in sign_rsa
        signer = key.signer(
    AttributeError: '_RSAPublicKey' object has no attribute 'signer'

What is happening is that the implementation in [algorithms.py, line 137](https://github.com/jpadilla/pyjwt/blob/master/jwt/algorithms.py#L137) tries to sign with the public key, but the `cryptography.hazmat.backends.openssl.rsa._RSAPublicKey` has no `signer` method: https://cryptography.io/en/latest/hazmat/primitives/interfaces/#cryptography.hazmat.primitives.interfaces.RSAPublicKey

**Comment by svnv** [comment]
So, it look like I misunderstood how jwt works. I somehow thought that the payload was also encrypted with the RSA key. (I edited my previous post in light of my new knowledge.)

The documentation should at least be updated to reflect that encoding (signing) is only possible with a private RSA key and decoding (verification) only works with a private key.

**Comment by jpadilla** [comment]
@svnv a pull request is welcome with your proposal to what the documentation should say about this.

**Comment by mark-adams** [comment]
I think there is a general assumption that users of JWT understand the basics of asymmetric crypto and how a digital signature works. However, it might not hurt to provide a link to [Wikipedia's article on Public-key crypto](http://en.wikipedia.org/wiki/Public-key_cryptography)

**Comment by jpadilla** [comment]
:+1: sounds good to me

**Comment by jpadilla** [comment]
Closed via #88
