### ISSUE TITLE
2.6.0 release missing from github

### ISSUE THREAD

**Issue by bluefish6** [jpadilla/pyjwt#815]
Release 2.6.0 is present on [pypi](https://pypi.org/project/PyJWT/#history) and mentioned in [CHANGELOG](https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.rst#v260), however is not listed as a [release](https://github.com/jpadilla/pyjwt/releases).

Please create a github release of this version. Different versions on pypi and github are a red flag suggesting that **possibly** somebody hijacked the project on pypi and released an unauthorized and malicious version there. However, seeing in CHANGELOG that version 2.6.0 was announced, this probably is only some issue with github release creation (it seems that it's done via some other means than a github action).

Thanks a lot in advance! :)

## Expected Result

Release 2.6.0 is listed as the newest [release](https://github.com/jpadilla/pyjwt/releases)

## Actual Result

Release 2.5.0 is the newest one on https://github.com/jpadilla/pyjwt/releases

![image](https://user-images.githubusercontent.com/84847001/197204327-fa42c158-3cd1-4c14-a6fc-a13ba1d77546.png)

But 2.6.0 is present on pypi: https://pypi.org/project/PyJWT/#history

![image](https://user-images.githubusercontent.com/84847001/197204237-2180fd51-be43-49ec-a708-776d36d61e75.png)

## Reproduction Steps

Open https://github.com/jpadilla/pyjwt/releases and https://pypi.org/project/PyJWT/#history and compare versions

## System Information

N/A

**Comment by jpadilla** [comment]
https://github.com/jpadilla/pyjwt/releases/tag/2.6.0
