### ISSUE TITLE
Can't decode tokens encoded with the "none" algorithm

### ISSUE THREAD

**Issue by seedifferently** [jpadilla/pyjwt#83]
There seems to be some problems with decoding tokens using the "none" algorithm:

    >>> jwt.encode({'some': 'payload'}, 'secret', 'none')
    b'eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJzb21lIjoicGF5bG9hZCJ9.'
    >>> jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJzb21lIjoicGF5bG9hZCJ9.', 'secret')
    [...]
    KeyError: 'NONE'
    [...]
    DecodeError: Algorithm not supported

**Comment by jpadilla** [comment]
I've never understood why we even have that option in the first place. But it's meant to be used like this:

```python
jwt_message = jwt.encode({'some': 'payload'}, key=None, algorithm=None)
jwt.decode(jwt_message, verify=False)
```

**Comment by seedifferently** [comment]
@jpadilla ah, thanks. Sorry about the noise.
