### ISSUE TITLE
ImportError: cannot import name 'smart_text' from 'django.utils.encoding'

### ISSUE THREAD

**Issue by magbanum** [jpadilla/pyjwt#844]
Summary.

## Expected Result
The error mentioned in the title is not expected. This error is because smart_text is removed and replaced with smart_txt in latest Django version.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import jwt
```

## System Information

    $ python -m jwt.help

```
<paste here>
```

This command is only available on PyJWT v1.6.3 and greater. Otherwise,
please provide some basic information about your system.

**Comment by auvipy** [comment]
why you are reporting that here can you elaborate? it is a django issue. I am not sure if pyjwt use any django import?
