### ISSUE TITLE
Type Annotation: key should be of type "str | bytes", not "str".

### ISSUE THREAD

**Issue by tholenst** [jpadilla/pyjwt#856]
In various APIs, most notably "api_jwt.encode" and "api_jwt.decode", key is passed in and annotated to be of type "str" ([example](https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L44)).

However, this does not allow all keys to be used. 

For example, using a token generated with https://token.dev/ the following works with a key of types bytes, but not str:

```
import jwt
import base64
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.e30.3WyMoLZen_KHpOc7iNDmcYixmUPexwuJpZsVeEjnAA8"
key = base64.b64decode('gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA=')
jwt.decode(token, key, 'HS256')
```

This works as expected, but there is no string which can be used here as the key.

**Comment by tdg5** [comment]
The [docs also suggest in several places](https://pyjwt.readthedocs.io/en/latest/usage.html#encoding-decoding-tokens-with-rs256-rsa) that in some circumstances `key` should be a `cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey`, so seems like this type annotation could use work in that regard as well.
