### ISSUE TITLE
kid verification should be optional

### ISSUE THREAD

**Issue by dehy** [jpadilla/pyjwt#857]
The lib cannot get signing keys from the jwks.json file because it checks for json keys that does not exist in the RFC

## Expected Result

It should find signing keys from a compliant jwks.json file

## Actual Result

It raise an error.

## Reproduction Steps

Here is a sample `jwks.json` file
```json
{"keys":[{"alg":"RS256","e":"XXXX","kid":null,"kty":"RSA","n":"3PTkzSp2a0cKN5STYqG86.........","use":"sig"}]}
```

```python
from jwt import PyJWKClient

jwks_client = PyJWKClient(f"https://server.com/oauth/jwks.json")
# jwt.exceptions.PyJWKClientError: The JWKS endpoint did not contain any signing keys
```

The check for valid keys is done on this line https://github.com/jpadilla/pyjwt/blob/9695f4c1d153ed8bf2b9ba0ef232c3a90889a1be/jwt/jwks_client.py#L77
Per the [RFC 7517](https://www.rfc-editor.org/rfc/rfc7517) or this doc from [auth0](https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-set-properties), the parameters does not include neither `public_key_use` (but `use` nor `key_id` (but `kid`)

## System Information

    $ python -m jwt.help

```json
{
  "cryptography": {
    "version": "39.0.1"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.9"
  },
  "platform": {
    "release": "22.3.0",
    "system": "Darwin"
  },
  "pyjwt": {
    "version": "2.6.0"
  }
}
```

**Comment by dehy** [comment]
I've just found that `jwk_set_key` is an abstraction of the json file. Working as expected after setting a `kid`

**Comment by dehy** [comment]
The RFC specifies that `kid` is optional (https://www.rfc-editor.org/rfc/rfc7517#section-4.5) `Use of this member is OPTIONAL.`

**Comment by rlopzc** [comment]
@dehy how did you manage to use it without "kid"?

**Comment by rlopzc** [comment]
I figured out by doing this:

```python
jwk = PyJWK(jwks_key)
jwt.decode(token, jwk.key, algorithms=["EdDSA"])
```
