### ISSUE TITLE
Add docs setup with mkdocs

### ISSUE THREAD

**Issue by jpadilla** [jpadilla/pyjwt#89]

**Comment by wbolster** [comment]
just curious, what is mkdocs?

**Comment by jpadilla** [comment]
http://www.mkdocs.org/

**Comment by wbolster** [comment]
hmm. for python docs sphinx and readthedocs.org is the more obvious solution I think.

"José Padilla" <notifications@github.com> schreef op 12 februari 2015 23:05:08 CET:
>http://www.mkdocs.org/
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jpadilla/pyjwt/issues/89#issuecomment-74163160

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jpadilla** [comment]
Possibly, although I've been using mkdocs heavily for many third party packages for django-rest-framework, it's easier to get it done, and it'll be easier to maintain
