### ISSUE TITLE
PyJWT in docker 

### ISSUE THREAD

**Issue by wuwenhao0508** [jpadilla/pyjwt#899]
Please refer to our [StackOverflow tag](https://stackoverflow.com/questions/tagged/pyjwt) for guidance.
When I use PyJWT in a python project with docker container, I get a error ''Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support." How do I to fix this?

**Comment by jaferrando** [comment]
Does not seem PyJWT related. The exact error message you pasted is .Net related, not Python. Maybe there's something else in your container, a piece based on .Net that if failing with this error.

https://github.com/dotnet/core/blob/main/Documentation/build-and-install-rhel6-prerequisites.md#troubleshooting

A complete log and the Dockerfile would be helpful to help you.
