### ISSUE TITLE
PyPI package cleanup 

### ISSUE THREAD

**Issue by petrrr** [jpadilla/pyjwt#91]
The PyPI packages is somewhat messy and provides some strange copies of PyJWT.egg-info/SOURCES. Maybe this should be cleaned up.

```
> ls work/PyJWT-0.4.1/PyJWT.egg-info/
PKG-INFO
SOURCES (Joses-iMac's conflicted copy 2014-10-17).txt
SOURCES.txt
dependency_links.txt
top_level.txt
```

**Comment by jpadilla** [comment]
@petrrr horrible, sorry about that. Will make sure that gets cleaned up for next release.

**Comment by wbolster** [comment]
@jpadilla perhaps wipe your local `*.egginfo/` dir is enough

**Comment by jpadilla** [comment]
@wbolster yep, will have this in mind on next release.

**Comment by jpadilla** [comment]
https://github.com/jpadilla/pyjwt/releases/tag/0.4.2
