### ISSUE TITLE
Feature request: public function to validate claims

### ISSUE THREAD

**Issue by ericbn** [jpadilla/pyjwt#912]
Hi 👋

First thank you for the great work with this project.

To explain this feature request, let me start with a simple [AWS HTTP API Gateway lambda authorizer](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html) code that uses pyjwt:

```python
import os

import jwt
from aws_lambda_powertools.utilities.data_classes import event_source
from aws_lambda_powertools.utilities.data_classes.api_gateway_authorizer_event import (
    APIGatewayAuthorizerEventV2,
    APIGatewayAuthorizerResponse,
)


OAUTH2_AUDIENCE = os.environ["OAUTH2_AUDIENCE"]
OAUTH2_ISSUER = os.environ["OAUTH2_ISSUER"]


@event_source(data_class=APIGatewayAuthorizerEventV2)
def lambda_handler(event, context):
    token = event.identity_source[0].removeprefix("Bearer ")
    # first decode the token without validation to get the value of claims["sub"]
    claims = jwt.decode(token, options={"verify_signature": False})
    principal_id = claims["sub"]
    try:
        # now actually validate the claims
        jwt.decode(token, audience=OAUTH2_AUDIENCE, issuer=OAUTH2_ISSUER)
    except jwt.InvalidTokenError:
        allow = False
    else:
        allow = True
    policy = APIGatewayAuthorizerResponse.from_route_arn(event.route_arn, principal_id)
    if allow:
        policy.allow_all_routes()
    else:
        policy.deny_all_routes()
    return policy.asdict()
```

As you can see the returned policy needs to contain the principal id, which is the value of the `sub` claim, and that value needs to be decoded from the token regardless if the token is valid or not. If the token is not valid, we respond a policy containing the principal id and all routes denied.

The feature request: Instead of having to decode the token twice -- first time to just decode it without any validation so we can get the value of the `sub` claim, second time to actually validate it -- we'd like to be able to decode it once without validation and the validade the already decoded claims. 

```diff
-        jwt.decode(token, audience=OAUTH2_AUDIENCE, issuer=OAUTH2_ISSUER)
+        jwt.validate_claims(claims, audience=OAUTH2_AUDIENCE, issuer=OAUTH2_ISSUER)
```

The motivation for the feature request: This is just because it better shows the intent of the code -- that we're first decoding the token without validation and then validating the claims afterwards.

**Comment by jaferrando** [comment]
How API gateway authrorizer works, if the token is not valid you would (logically?) return a deny policy. In that case you not don't need to put in the `principalId` attribute any value from the token, but you most probably want to avoid that, and instead common practice is to return the policy with any fixed value such as "unauthorized". That way the API Gateway cache, if enabled won't cache a deny for the principal, and in case the token was not valid for temporary reasons such as being expired you would be safe from the issue of the gateway denying subsequent legitimate requests from the same principal.

I've jut completed a project that will hopefuly become public soon, that provides an API Gateway Authorizer with customizable policy document generation and some advanced performance-oriented features.

There are other reasons to do a first decode without validation anyway. It will get done by the decode itself if it needs to fetch  the JWKS, and as in my case, implementing JWKS caching in AWS Lambda (external to the PyJWT client) requires us to decode the token to get the issuer and find the JWKS in the cache, before of course having the keys available to validate the token.

**Comment by ericbn** [comment]
Hola @jaferrando. Sorry for the delay in replying.

Thank you for your thoughtful response. You're absolutely right, the principalId can be a dummy value if the access is denied. Hence no need to first decode and then validate here.

You mentioned there can be other reasons to work on this feature, so feel free to close this when you prefer.

**Comment by ericbn** [comment]
Leaving the updated code here for reference:
```python
import os

import jwt
from aws_lambda_powertools.utilities.data_classes import event_source
from aws_lambda_powertools.utilities.data_classes.api_gateway_authorizer_event import (
    APIGatewayAuthorizerEventV2,
    APIGatewayAuthorizerResponse,
)


OAUTH2_AUDIENCE = os.environ["OAUTH2_AUDIENCE"]
OAUTH2_ISSUER = os.environ["OAUTH2_ISSUER"]


@event_source(data_class=APIGatewayAuthorizerEventV2)
def lambda_handler(event, context):
    token = event.identity_source[0].removeprefix("Bearer ")
    try:
        claims = jwt.decode(token, audience=OAUTH2_AUDIENCE, issuer=OAUTH2_ISSUER)
    except jwt.InvalidTokenError:
        principal_id = "unauthorized"
        allow = False
    else:
        principal_id = claims["sub"]
        allow = True
    policy = APIGatewayAuthorizerResponse.from_route_arn(event.route_arn, principal_id)
    if allow:
        policy.allow_all_routes()
    else:
        policy.deny_all_routes()
    return policy.asdict()
```
