### ISSUE TITLE
Perhaps allow audience= and issuer= args to .encode()

### ISSUE THREAD

**Issue by wbolster** [jpadilla/pyjwt#92]
This would be nice for API parity with `.decode()` and would allow applications to ignore the `iss` and `aud` abbreviations used by JWT, and it would also give `pyjwt` control over the the way those fields are formatted, making it less likely that `.encode()` spits out a non-conforming token.

**Comment by jpadilla** [comment]
@wbolster hmm not sure I understand your proposal. Mind showing an example or use case?

**Comment by wbolster** [comment]
Code to encode a token, e.g.

```python
payload = {}
token = pyjwt.encode(d, key)
```

takes no `audience=` or `issuer=` args, while this does:

```python
payload = pyjwt.decode(token, key, audience='foo', issuer='bar')
```

This means that application authors need to know internal details of the JWT spec if they want to generate tokens with audience or issuer claims embedded in them, since the only way to do so (currently) is to put `aud` and `iss` keys (with conforming values) into the payload dict.

I argue that this is a discrepancy between encode/decode, since for _decoding_ pyjwt takes care of the correct interpretation of the JWT spec to validate the audience and issuer claims.

Please let me know whether I've explained myself better this time. :)

**Comment by jpadilla** [comment]
@wbolster yeah definitely makes sense now

**Comment by wbolster** [comment]
ok feel free to assign this issue to me. no guarantees about time frame but I'll see what I can do :-)

**Comment by mark-adams** [comment]
So, the big question here would be... how would you handle conflict? If a consumer passed in a payload to `encode()` that already had "aud" set but they also passed in a value for `audience=`

I think the best thing in that situation would be to throw an exception. It seems like any other option would result in a confusing API.
