### ISSUE TITLE
Decoding RS256 JWT

### ISSUE THREAD

**Issue by cancan101** [jpadilla/pyjwt#93]
I am trying to decode a JWT encoded with `RS256`.

When I run the following:
```
secret = Crypto.PublicKey.RSA.importKey(PUBLIC_KEY)
```
I get:
```
ValueError: RSA key format is not supported
```

I suspect something might be wrong with the public key format:
```
PUBLIC_KEY= """-----BEGIN CERTIFICATE-----
MIIDETCCAfmgAwIBAgI....sRPdPR8
-----END CERTIFICATE-----"""
```

**Comment by cancan101** [comment]
Following [this](http://serverfault.com/a/441227/233297) to get a :
```
-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----
```
and then setting this to `JWT_SECRET_KEY` seems to do the trick.

**Comment by jpadilla** [comment]
This might be related to #90

**Comment by cancan101** [comment]
The issue is mentioned here: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#pem and also talked about in #82.

The solution is to load the certificate using:
```
key = cryptography.x509.load_pem_x509_certificate(PUBLIC_KEY, default_backend()).public_key()
```
[rather than](https://github.com/jpadilla/pyjwt/blob/a4c5236e7b2a6e10bcfcaebcf1307122c255db57/jwt/algorithms.py#L130):
```
 key = cryptography.hazmat.primitives.serialization.load_pem_public_key(key, backend=default_backend())
```

**Comment by jpadilla** [comment]
Still not clear with this if there's something we can do to prevent this confusion.

**Comment by cancan101** [comment]
You could make [this logic](https://github.com/jpadilla/pyjwt/blob/eb4bb5346b60d4970687c8db3935f24510b3fa46/jwt/algorithms.py#L124) try to fall back one to one more attempt. You could add some additional logic to look for the begin/end public key string as well.

**Comment by jpadilla** [comment]
Interested in seeing a PR for this. 

@wbolster @mark-adams I'd love your thoughts on this.

**Comment by mark-adams** [comment]
I think we should update the documentation to indicate how to load a key from an x509 certificate.

 I don't think adding more fallback logic is the right approach. The API expects a key and it works when you pass in a key. A certificate is way more than a key so it's a bit outside the scope of our code and would only add complexity.

It should be the consumer's responsibility to make sure they are passing in a key and not something else. If we do something like this, why not check to see if it is ZIP compressed, or embedded in a Word doc, or maybe a reversed string? :)

**Comment by cancan101** [comment]
I would say more important than the fallback logic would just be documentation.

**Comment by jpadilla** [comment]
Sold! If anyone wants to take a stab at that, pull requests are welcome.

**Comment by wbolster** [comment]
+1 on having this as documentation. Adding magic detection logic to the `jwt` API isn't the right way imho, as @mark-adams pointed out.
