### ISSUE TITLE
Got error: Algorithm 'ES256' could not be found. Do you have cryptography installed?

### ISSUE THREAD

**Issue by denisshvayko** [jpadilla/pyjwt#941]
I'm using PyJWT to connect to the Apple API. 
But at the same time I get the error whether I have crypthogaphy installed. I've already completely removed and installed packages a couple of times, but it doesn't help. I can't figure out what I'm doing wrong.

{
  "cryptography": {
    "version": "42.0.1"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "4.19.0-9-amd64",
    "system": "Linux"
  },
  "pyjwt": {
    "version": "2.8.0"
  }
}

**Comment by JamesParrott** [comment]
I don't think Python 3.7 is supported.

The [tests](https://github.com/jpadilla/pyjwt/blob/master/tox.ini) and [metadata](https://github.com/jpadilla/pyjwt/blob/master/setup.cfg) only go back as far as Python 3.8

**Comment by JamesParrott** [comment]
I can reproduce the same issue in Python 3.7.3, and encountered the common "Rust not available" problem with cryptography source distributions.  But this was on windows, so perhaps is not the same underlying cause as yourself.  

Even though Pyjwt 2.8.0 and cryptography 42.0.1 both support Python 3.7, and even though lots of py37 cryptography 42.0.1 binary wheels are provided on [PyPi](https://pypi.org/project/cryptography/#files), these require a later version of pip (v23 works):

```
python -m pip install --upgrade pip
```

An old default version Python 3.7 pip (v19) pulls the cryptography source distribution, which in recent years has required Rust to compile.

This fails to install cryptography entirely, which presumably you were able to do, to read off the version number?  Or perhaps you did you not notice the dependency you actually wanted failed to install, as the rest of pyjwt installed successfully?

```
Collecting cryptography
  Downloading https://files.pythonhosted.org/packages/3f/ed/a233522ab5201b988a482cbb19ae3b63bef8ad2ad3e11fc5216b7053b2e4/cryptography-42.0.1.tar.gz (672kB)
    100% |████████████████████████████████| 675kB 1.1MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done

...

  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

  To update pip, run:

      pip install --upgrade pip

  and then retry package installation.

  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

  This package requires Rust >=1.63.0.

  ----------------------------------------
  Failed building wheel for cryptography

```
