### ISSUE TITLE
When is python 3.12 expected to be released as a package on PIP?

### ISSUE THREAD

**Issue by sgeef** [jpadilla/pyjwt#947]
I've seen that the python 3.12 support has already been added to the main branch, but not yet release. when can we expected it? 
we'd much appreciate it!

**Comment by ezeparziale** [comment]
Any news?

**Comment by codespearhead** [comment]
[v2.9.0](https://github.com/jpadilla/pyjwt/releases/tag/2.9.0) has just been relased.
