### ISSUE TITLE
Cryptography package, needed, but not as a requirement?

### ISSUE THREAD

**Issue by vhdmoradi** [jpadilla/pyjwt#954]
I was working with PyJWT package in my api, and was struggling with "Algorithm not supported" error for over 2 hours; checking each line of my code to figure out where I've made a mistake. Until I came to realization that it is due the fact that I do not have `cryptography` package installed. 
If this package is essential for the usage, shouldn't it be as a requirement and autamitically installed when installing PyJWT?

**Comment by jpadilla** [comment]
some algorithms don't require the package.

**Comment by vhdmoradi** [comment]
Yeah, But som do! I mean, requirements usually are required in some places of a code, not all of it. Still, we name it as a requirement and install it at the beginning. Your repo, your decision, I am just saying requrements are requirements as long as they are used, even once; does not matter on how many places you use them.
