### ISSUE TITLE
Implement sub and jti check

### ISSUE THREAD

**Issue by eddy2by4** [jpadilla/pyjwt#959]
Hello,
As per the jwt.org site, our library does not fully support all checks.
https://jwt.io/libraries?language=Python

Do we have a timeline for when sub and jti check might be implemented?

Thanks

**Comment by Divan009** [comment]
@jpadilla I've opened a PR which can close this issue. Do let me know if it needs changes

**Comment by eddy2by4** [comment]
@Divan009 thanks for the great for fixing this issue. The codecoverage test fails though on your PR. 
When you have some free time, can you please take a look ?

**Comment by Divan009** [comment]
@jpadilla I will write the test cases and fix the issue
