### ISSUE TITLE
Issuer Check Should Canonicalize the URL

### ISSUE THREAD

**Issue by cancan101** [jpadilla/pyjwt#96]
See: https://github.com/jpadilla/pyjwt/blob/5f9bc05803508b844d3fd9c61cd5210af06eecd8/jwt/api.py#L186

Ideally the URL should be canonicalized (ie the trailing slash should be made explicit) rather than just doing a simple string compare.

**Comment by wbolster** [comment]
I don't agree. There's no reason to treat the field as a url, and even if it was defined as a url (it isn't), a url with a trailing slash is different from one without a trailing slash.

Relevant part of the spec (https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32): 

```
4.1.1.  "iss" (Issuer) Claim

   The "iss" (issuer) claim identifies the principal that issued the
   JWT.  The processing of this claim is generally application specific.
   The "iss" value is a case-sensitive string containing a StringOrURI
   value.  Use of this claim is OPTIONAL.
```

**Comment by cancan101** [comment]
[This is what inspired this post](https://ask.auth0.com/t/modify-iss-attribute-for-jwt-possible/498):
>There used to be a bug with Amazon Cognito (We found it a few weeks back) where our iss field was created without the end slash and Amazon didn't work with that (Although it should :)). They fixed it,

**Comment by tilgovi** [comment]
Agree with @wbolster. Particularly where things like security are concerned I'd err on the side of strict, anyway.

**Comment by wbolster** [comment]
The generalized solution would be to have some "issuer validation" hook (callback) to be used instead of the string comparison.

**Comment by jpadilla** [comment]
@wbolster but then would that mean we have to do the same for the other "validations"?

**Comment by tilgovi** [comment]
Supporting callables for all of those wouldn't be the worst.

**Comment by wbolster** [comment]
It can be an optional hook, with the default being an exact string comparison, cf. what `json` does with `object_hook` and so on.

**Comment by mark-adams** [comment]
I agree @wbolster that there's no reason for us ever to assume we know the content of the `iss` value outside of what's in the spec. Like `jti`, I think anything outside of a simple string match should not be the responsibility of the library to handle.

If someone wants to implement more complicated application specific logic on a claim value, they can either do it in their application or by subclassing `jwt.PyJWT` and overriding the `decode()` method.
