### ISSUE TITLE
Document `leeway` for negative values

### ISSUE THREAD

**Issue by luigibertaco** [jpadilla/pyjwt#988]
I am aware that using leeway with negative values works as expected. But I am worried of using it in production as there is no documentation about it and, to me, it could be an undocumented behaviour that can change in future without a breaking change documented.

Is `leeway` expected to accept negative values and help not to use a token if its "almost" expired? If so, can we document it better and make the definition official?

I am happy to to propose a PR to change the docs, just want to check if the behaviour is expected or not.

**Comment by DeD1rk** [comment]
The documentation is definitely not in line with how it works. A positive leeway (e.g. 10) means that a token expires 10s earlier, and is 'immature' for 10 seconds longer, which does not match the docs at https://pyjwt.readthedocs.io/en/stable/usage.html?highlight=leeway#expiration-time-claim-exp.

IMO setting a positive leeway as in the docs should be the correct thing to do, and hence, it would be best to change the behavior. That would be a breaking change though, so changing the docs to clearly indicate this weird thing also works.
