### ISSUE TITLE
Please, add an ES256 example in Usage Examples

### ISSUE THREAD

**Issue by oza4h07** [jpadilla/pyjwt#989]
Please refer to our [StackOverflow tag](https://stackoverflow.com/questions/tagged/pyjwt) for guidance.
Documentation in [1] includes an Encoding and Decoding Tokens with HS256 or RS256.
Those are perfect to get started using PyJWT.

Could it be possible to add a similar example using ES256, including private/public keys examples ?
Ideally, you'll just have to copy-paste this example in a file to get working example of encoding and decoding with ES256.

This could be very valuable for complete beginners who may have a weak confidence about the way they generated private or public keys.

[1] https://pyjwt.readthedocs.io/en/latest/usage.html#

**Comment by syedtalaljilani** [comment]
I want to work on this @jpadilla

**Comment by fadkeabhi** [comment]
I have a working example of ES256. And I would like to contribute to docs. Can you assign this issue to me

**Comment by Dxuian** [comment]
is this still open ?

**Comment by goelnaman66** [comment]
Is this still open?
