### ISSUE TITLE
Support for App Engine

### ISSUE THREAD

**Issue by garyp** [jpadilla/pyjwt#99]
Google App Engine's python runtime environment unfortunately only supports the "pycrypto" library and not the newer "cryptography" library (they have a pre-vetted list of native libraries that are supported): https://cloud.google.com/appengine/docs/python/tools/libraries27. I'm using the 0.3.x branch of pyjwt on App Engine right now and it'd be nice to be able to ugprade to 0.4.x.

The only solution I can think of is to bring back the old pycrypto code and use it as a fallback when the "cryptography" library isn't available. If you're ok with continuing to support pycrypto within pyjwt, I don't mind putting together a pull request to implement the fallback logic.

**Comment by jpadilla** [comment]
GAE strikes again! Are you using RSA or ECDSA signatures? If not you wouldn't need `pycypto` or `cryptography` at all. I think we could definitely evaluate the possibilities of abstracting both libraries, and support both of them without including too much about each in our implementation. Does that make sense?

**Comment by garyp** [comment]
I'm using RS256 signatures. Yeah, abstracting both libraries is what I was thinking. The code already seems pretty well abstracted, so it doesn't seem like it'd be a lot of work to define a common interface.

**Comment by jpadilla** [comment]
@garyp I'm down to seeing a proposal for this.

**Comment by garyp** [comment]
@jpadilla Great. I'll probably work on this in a week or two.

**Comment by mark-adams** [comment]
This can now be accomplished by using `register_algorithm` and the and the jwt.contrib.algorithms.pycrypto classes.

**Comment by johnlockwood-wf** [comment]
@mark-adams, how do you use `register_algorithm` with the `jwt.contrib` algorithms? When I `python setup.py install`, there is no contrib package in jwt.

**Comment by johnlockwood-wf** [comment]
this seems to be an issue with the setup.py. It needs to list all the packages like:

    setup(
        name='PyJWT',
        ...
        packages=['jwt', 'jwt.contrib', 'jwt.contrib.algorithms'],
