### ISSUE TITLE
Replace flake8 with ruff

### ISSUE THREAD

**Issue by cleder** [jpadilla/pyjwt#996]
Ruff is a modern and fast replacement for flake8 which has dozens of flake8 plugin checks integrated and autofixes.
In this repo 79 ruff error can be fixed,

**Comment by gagandeepp** [comment]
Interested please assign @cleder 

can you please add Hacktoberfest label to this issue as well?

**Comment by gagandeepp** [comment]
https://github.com/jpadilla/pyjwt/pull/998


@cleder  Please review my MR

**Comment by gagandeepp** [comment]
@jpadilla can you please review my MR?

**Comment by gagandeepp** [comment]
@jpadilla can you please add hacktoberfest label to this issue?

**Comment by gagandeepp** [comment]
https://github.com/jpadilla/pyjwt/pull/1001
